### ISSUE TITLE
Public Comment on 1.3.1/1.3.3 and strikethrough

### ISSUE THREAD

**Issue by CharlesBelov** [w3c/wcag#1073]
Does 1.3.3 Sensory Characteristics apply to strikethrough, which is commonly used to indicate that content has been deleted? It would be good for this to be made explicit.

**Comment by mraccess77** [comment]
On initial thought I'd say SC 1.3.1 Info and Relationships cover this as it's not so much about instructions -- which SC 1.3.3 is focused on.

**Comment by JAWS-test** [comment]
If it says on the page: "Please pay particular attention to the strikethrough text", this would be in violation of SC 1.3.3. the information itself, which is transmitted by the strikethrough text, would be in violation of SC 1.3.1 unless it is also transmitted in another form

**Comment by CharlesBelov** [comment]
I've retitled this comment to reflect possible applicability of 1.3.1 instead of or in addition to 1.3.3.

Re: 1.3.1 Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text. 
would imply to me that if strikethrough were solely through <span> styling it would not be accessible, but if through <del> styling it would technically be accessible with regard to screen readers even if you have to do something special with most screen readers to get them to announce it.

Thinking about it, though, there is the separate issue that strikethrough text may pose a challenge for people with low vision or cognitive impairments.

**Comment by JAWS-test** [comment]
I think:
* strikethrough with span = violation of 1.3.1
* strikethrough with del = in itself no violation of 1.3.1, but the question is whether it is [accessibility supported](https://www.w3.org/TR/WCAG21/#dfn-accessibility-supported)
* Readability of strikethrough text = there is no WCAG criterion which regulates this, but it is of course in the interest of accessibility to check whether other methods of text highlighting are possible to make the text more readable

**Comment by guyhickling** [comment]
I report strikethrough in my audits as a 1.3.1 failure, if it relies on just the Del element, because it is not passing the information to AT. 

As JAWS-test points out, is it accessibility supported? Neither NVDA nor JAWS support it in their natural default states. JAWS doesn't support it at all according to their documentation - and so far as I'm concerned that means it isn't accessibility supported since JAWS is the most widely used screen reader.

NVDA supports it apparently if you go into their settings customisation facilities but, just for kicks, I tried doing that. I couldn't see how to do it, so I'm sure the little old blind lady down the street won't be able to find it either!

Where "accessibility supported" is concerned, my view is that this must be done in the user agent's default state. We shouldn't expect blind people to go trawling through the extremely complicated settings in their screen reader to turn something on before they can hear it. I doubt if most blind people do more than just turn on their new screen for the first time and just use it. So in my view, the above "you have to do something special with most screen readers to get them to announce it" isn't an option.

The Del element is a good example - only a web developer knows what that does (and only some of them!). You can't expect a non-developer to say to themselves "I must find out how to turn on the strikethrough setting so I can hear deleted text." A blind person won't even know that they occasionally come across websites with strikethrough on it, because their screen readers aren't telling them they are on striken text! Ordinary people just navigate websites, they aren't technical experts like us.

**Comment by CharlesBelov** [comment]
Thank you for that explanation. I see this actually was covered in WCAG 2.0 G117: Using text to convey information that is conveyed by variations inpresentation of text. My apologies. Closing.
