### ISSUE TITLE
SCR37 appears to duplicate SCR26?

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag#108]
Refer to
SCR26: Inserting dynamic content into the Document Object Model immediately following its trigger element
SCR37: Creating Custom Dialogs in a Device Independent Way 

Is the intent and description of SCR37 not covered by SCR26?

All the tests of SCR26 are covered by SCR37 too
Admittedly, SCR37 does say SCR26 is related.
So can both techniques be merged?
By the way should SC 1.3.2 also be listed as an applicable SC?
Thanks,
Sailesh

**Comment by joshueoconnor** [comment]
Item survey for Working group https://www.w3.org/2002/09/wbs/35422/Sept1st2015/

**Comment by joshueoconnor** [comment]
RESOLUTION: Working group discussed, leaving open, this item needs to be reviewed and taking working group responses into consideration. https://www.w3.org/2002/09/wbs/35422/Sept1st2015/

**Comment by joshueoconnor** [comment]
If these are to be merged, we need to call out that the position of the dynamic content is addressing 1.3.2 etc also.

**Comment by mraccess77** [comment]
SCR 37 seems like a specific case of SCR26.    In the case of a properly created dialog the location of the rendered dialog is not relevant as focus is controlled to and within the dialog and other interactive page content should not be available (e.g. with aria-hidden) and managed focus.   In more general cases however such as sub menus/navigation structures the reading order SC 1.3.2 is very important.  We also need to consider the mobile use cases where screen reader users have swipe gestures and where things like role application are ignored and tab key access may not be available.  Whether we combine these are leave them separate we need to distinguish the different scenarios and what is required for each item.

**Comment by spanchang** [comment]
"SCR 37 seems like a specific case of SCR26": 
That is why the issue asks : Is the intent and description of SCR37 not covered by SCR26?

"the location of the rendered dialog is not relevant as focus is controlled to and within the dialog ...":  it implements SCR26 that is why it is  "a properly created dialog" as you put it.

About the mobile use cases ... tab key access may not be available: is this not true of many techniques?
After completing data entry in one form field, a mobile user with a touch screen interface has to  find the next field and activate it before being able to enter data in it. Tabbing  is not possible.
So do H4 or G59 need to be re-written? Reviewing / editing techniques to be mobile-compatible is a large undertaking. Should it be covered by the scope of the change that may be required based  on this specific issue?

**Comment by mraccess77** [comment]
The mobile work will need to be taken up separately from this issue.  As for the SCR techniques -- it really comes down to what is the best way to communicate and provide test steps for each of the two possible situations and different types of content menu, dialogs, etc.  If people feel it is best in one technique then I'm fine with that.  If people feel like having it in one technique may obscure dialog specific content or may be hard for people to distinguish then we should keep it in two.  It seems like the group is open to having one technique but we need a proposal of what the merged technique will look like and how it will differentiate when focus movement is enough and when reading order 1.3.2 must be considered.  Would you (Sailesh) be interested in writing that out?

**Comment by spanchang** [comment]
Jonathan,
I'll take a shot at it. First  I'll write out / edit the description
part and that can be reviewed to see if there is some conceptual
agreement. Then examples / tests can be developed
Thanks,
Sailesh

**Comment by spanchang** [comment]
Here is the promised draft.  (Sorry I am not sure how to get it into this platform)
https://www.w3.org/WAI/GL/wiki/SCR26:_DraftSept2015
Regards,
Sailesh

**Comment by joshueoconnor** [comment]
Thanks Sailesh: I'm pasting your draft proposal here.

SCR26: Inserting dynamic content into the Document Object Model (DOM) in a manner that preserves meaning and operability

Applicability

SC 1.3.2
2.4.3
Description

This technique demonstrates a device independent manner of programmatically inserting content including user interface controls into the Documents Object Module (DOM) so that the newly introduced content is available in an order that preserves meaning and operability. This technique may be employed in a variety of situations, such as:
dialogs - both modal and non-modal, also referred to as popups
menus
tabbed interfaces
Accordion
UI controls that expand (reveal) / collapse (hide) content
content including UI controls that are displayed conditionally when a selection is made or the state of a control is changed (should this be covered ... SCR19 refers to it without alluding to 2.4.3 or 1.3.2)
In order to accomplish this the following needs to be done for the element that triggers content insertion :
that it is a native link or a form control such as a SELECT control, radio button, checkbox or button
a custom element with a suitable role and accessible name with its state (if applicable) available to assistive technologies
For natively focusable elements like links or buttons, the script is called from its onclick event. Keyboard accessibility is implemented using suitable scripting events for other trigger elements.
Depending on the situation one or more of the following needs to be done to the the newly inserted content including UI control :
place it immediately after the trigger element in the Document Object Model (DOM)
absolutely position it elsewhere on the page and control its visibility using CSS; aria-hidden may need to be employed on other portions of the page.
Examples

Dialog
Modal window
Accordion
Key Test

The newly added content or UI control is available right after the trigger element using the tab key, arrow key (down or right) or suitable gesture on a touch screen device to navigate forward
Upon activating the trigger element, the focus remains either on the trigger element updated for its new state or at a logical place within the newly added content
The keyboard focus remains at a logical place within the content (such as the trigger element or the next element in the reading / navigation sequence) when the newly added content is no longer perceivable
Note
This technique does rely on use of other techniques like CSS, ARIA , etc. This seems to be ok because there are documented techniques that do likewise. Refer to:
SCR26: Note that this technique works for synchronous updates. For asynchronous updates (sometimes called AJAX), an additional technique is needed to inform the assistive technology that the asynchronous content has been inserted.
SCR37: also refers to use of a CSS technique: placing the div above the page content using z-order and absolute positioning in CSS.
SCR37: And to "ensure that the HTML inside the dialog div meets the same accessibility standard as other content", other techniques need to be used.
SCR19: Using an onchange event on a select element without causing a change of context refers to 3.2.2 (and 3.2.5) but in the text says 'ensure reading order is proper.

**Comment by spanchang** [comment]
Thanks Josh.
I believe the links to examples did not come through in the above. So I am
including those.
Links to Examples
Dialog:
http://output.jsbin.com/qafomo/3/

Modal window:
http://accessibility.oit.ncsu.edu/training/aria/modal-window/version-3/

Accordion:
https://dequeuniversity.com/library/aria/tabpanels-accordions/tabbed-accordion

Also, the examples in the present versions of SCR26 and SCR37 may be
included too.
Regards,
Sailesh

**Comment by joshueoconnor** [comment]
Test procedures need to be updated to match existing WCAG format.

**Comment by spanchang** [comment]
Josh,
Any decision on the proposed merger of two techniques? Sure the tests
can be  written to match standard format but will it not be better to
get an ok for the proposal including the key tests first? My original
comment only pointed to the duplication of content in the two
techniques. Then there was a suggestion that I should draft one that
merged the two.
Thanks,
Sailesh

**Comment by joshueoconnor** [comment]
Sorry for the delay Sailesh. Looking back at the results, while overall the response to your suggestion was favourable, IIRC there were some reasonable objections to your proposal (which are not reflected at the survey crashed). Also I think the entire proposal needs to be captured in one place (with the updated test procedures to match existing WCAG format as that was group feedback) - and if you would like to draft a single technique that represents the merge - then please do.

**Comment by joshueoconnor** [comment]
https://www.w3.org/2002/09/wbs/35422/charter_policy_update_2015/results

**Comment by joshueoconnor** [comment]
Sailesh, if you wish to pursue this issue can you put together a new technique that represents the final merge? Then we can survey the group. Thanks

**Comment by spanchang** [comment]
Josh,
I read through the comments.
Here is the test section to replace the 'key tests'.
Tests:
1. Check that the newly added content or UI control is  available right after the trigger element using the tab key, arrow key (down or right) or suitable gesture on a touch screen device to navigate forward  
2. Check that upon activating the trigger element, the focus remains  either on the trigger element  updated for  its new state or at a logical  place within the newly added content
3. Check that the keyboard focus remains at a logical place within the content (such as the trigger element or the next element in the reading / navigation sequence) when the newly added content is no longer perceivable  

Expected Results:
Tests 1, 2 and 3 are true

About Examples:
Also, the examples in the present versions of SCR26 and SCR37 may be
included too. Maybe Michael C / Andrew  will be able to pull this in together efficiently.

Finally, I had a query within the description ... look at the statement that has 'SCR19' in it.  

I can do with help on the editorial stuff if someone wishes to  take a crack at it.
Thanks,
Sailesh

**Comment by spanchang** [comment]
Josh,
I went back and edited the technique on the Wiki
https://www.w3.org/WAI/GL/wiki/SCR26:_DraftSept2015

(Please let me know how I can include it in Github in a manner that
includes  markup to convey structure and I will be happy to transfer
it over).
Pending issues:
a. Title of the technique including a number ... it is a new one to
replace SCR 26 and SCR37
b. Please address the question posed in the sixth bulleted point in
the description section that has 'SCR19' in it
c. Please pull in examples from the present techniques SCR26 and SCR37
into the examples for this technique too.

Thanks,
Sailesh

**Comment by jnurthen** [comment]
I'd like to see some changes detailing other possibilities to navigate to content. Sometimes it is not possible to move VoiceOver focus to newly added content (thanks to the VO focus model) and it is also not possible to add the content in the correct place in the DOM due to visual ordering issues. In these cases we add a link (when running on iOS only) immediately after the trigger which allows the user to move focus to the newly added content and another link in the newly added content to return focus to the trigger. This is the only method we have found that works reliably on iOS w/ VO. I want to ensure that the technique allows this kind of approach and my reading at the moment is that it does not.

**Comment by spanchang** [comment]
Hello James,
Good point.
Actually, with iOS and VO,  even activating a simple HTML SELECT
control causes the picker items to become available lower down the
page and one has to navigate down using explore by touch. This has
been reported to Apple as an issue.
Likewise, iOS failing to make the content available in the correct
order for dynamic content is an OS issue. Alright one may provide a
link as a workaround but it is better to report the issue to Apple and
get it addressed. No?
I do not believe the technique should document workarounds for OS or
AT failings.
Thanks,
Sailesh

**Comment by awkawk** [comment]
Reading this through more I have more concerns about SCR37.  I wish that we made a simpler technique about modal dialogs and deal with the non-modal ones separately.  I'm concerned because I can envision interfaces where there are multiple triggers to hide/display a "floating pod" (e.g. a non-modal dialog) and am not sure how to make it always immediately follow the trigger button in the DOM or tab order in that situation.  It may also not be necessarily desirable to make non-modal dialogs follow the trigger button in the dom order - what if the non-modal dialog is triggered from within a menu?

**Comment by spanchang** [comment]
Well I took a shot at combining the two techniques  because there was a suggestion earlier in the threat that I do so. In fact I had merely asked a question: do the two techniques appear to cover the same ground and appear to duplicate  the other.  Most were open to the idea of combining the techniques and after the last survey Josh conveyed that feedback was generally positive for the draft that combined the two. If there is good reason to keep the techniques separate and remove the  duplicated content maybe this  should have been considered. 
Also, a single technique does not apply  to every situation. One has to determine  which technique applies or deviate from it if warranted. 
In the end, consensus trumps!
Best wishes,
Sailesh

**Comment by mraccess77** [comment]
Ø  Reading this through more I have more concerns about SCR37. I wish that we made a simpler technique about modal dialogs and deal with the non-modal ones separately
I would agree that we should either split out or change the evaluation steps.  Steps 1 and 2 from Sailesh’s proposal are listed below:

  1.  Check that the newly added content or UI control is available right after the trigger element using the tab key, arrow key (down or right) or suitable gesture on a touch screen device to navigate forward
  2.  Check that upon activating the trigger element, the focus remains either on the trigger element updated for its new state or at a logical place within the newly added content
IMO if focus moves to the revealed content then the revealed content need not be next in the reading order.  If focus does not move there then it would need to be in the reading order or there would have to be a mechanism to move to the revealed content and the user must be advised of that method.

Jonathan

Jonathan Avila
Chief Accessibility Officer
SSB BART Group
jon.avila@ssbbartgroup.com
703.637.8957 (o)
Follow us: Facebook<http://www.facebook.com/#!/ssbbartgroup> | Twitter<http://twitter.com/#!/SSBBARTGroup> | LinkedIn<http://www.linkedin.com/company/355266?trk=tyah> | Blog<http://www.ssbbartgroup.com/blog> | Newsletter<http://eepurl.com/O5DP>

**Comment by spanchang** [comment]
Jonathan / James / Andrew,
I have revised the tests based on Jonathan's comments.
Please take a look at
https://www.w3.org/WAI/GL/wiki/SCR26:_DraftSept2015#Description

Thanks,

Sailesh Panchang

**Comment by spanchang** [comment]
Sorry that link pointed to the description section. Look at the tests.
https://www.w3.org/WAI/GL/wiki/SCR26:_DraftSept2015

**Comment by mraccess77** [comment]
I would propose the following:
While the purpose of this technique is to make sure access to newly displayed content is available to the user, the technique demonstrates the following additional qualities:
It may apply to link or a form control such as a SELECT control, radio button, checkbox or button 
When a custom element is used a suitable role and accessible name with its state (if applicable) is available to assistive technologies 
For natively focusable elements like links or buttons, the script is called from its onclick event. Keyboard accessibility is implemented using suitable scripting events for other trigger elements.

**Comment by joshueoconnor** [comment]
Jon Avila - Technique needs updating if to be kept separate. There are differences when there are one dialog on a page, or multiple dialog. Focus management need may vary depending on how the dialog is open. So this could describe those situations better.

**Comment by awkawk** [comment]
Preparing to mark as deferred due to inactivity and group resource constraints (https://www.w3.org/WAI/GL/wiki/Handling_Issues).
