### ISSUE TITLE
Challenges Note Challenge 4 last paragraph suggestion

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wcag#1092]
@peterkorn @JaninaSajka 

We have not yet completed a WCAG2ICT for WCAG 2.1 SCs. I think its premature to make a statement. I think the idea can be introduced with a "may" and "yet to be determined".

CURRENT TEXT
It covers the 12 success criteria out of the 38 A and AA criteria in WCAG 2.0 which could be applied to non-web ICT only after replacing specific terms or phrases, as well as a growing list of success criteria introduced in WCAG 2.1 that also pose specific challenges for conformation verification and testing in the non-web ICT context.

SUGGESTED TEXT
It covers 12 success criteria out of the 38 A and AA criteria in WCAG 2.0 which can be applied to non-Web ICT after replacing specific terms or phrases, as well as a list of success criteria introduced in WCAG 2.1 that may pose specific challenges for conformance verification and testing in the non-Web ICT context. This is still to be determined.

**Comment by peterkorn** [comment]
David, thanks for highlighting this; given the applications of WCAG to non-Web technologies, this is an important section of the doc.

Your argument isn't persuading me here.  The challenges that this document is highlighting generally (not simply in the non-Web ICT context) came from the authors analysis of the issues, which were initially discussed and reviewed in discussions in the Silver TF, and are being reviewed by AGWG members now.  As someone who has implemented assistive technologies on 7 non-web platforms (as well as being co-editor/co-author of WCAG2ICT), I don't see why we need to have a formal "WCAG2ICT for WCAG 2.1 SCs" process completed in order to undertake a similar analysis of challenges related to these new SCs, and have language describing those specific challenges reviewed here in AGWG, followed by the larger public in a FPWD.  

That said, this appendix is clearly not yet complete.  Not only are there several places marked with an Editor's Note "Section content yet to be written", but in point of fact, it doesn't yet contain any text for any SC newly introduced in WCAG 2.1.  So the text you are citing above is meant to cover additions to come (hence the "a growing list of" language)

Given that, how would you feel about this text in Challenge #4 instead:

"It covers 12 success criteria out of the 38 A and AA criteria in WCAG 2.0 which can be applied to non-Web ICT after replacing specific terms or phrases.  In future versions of the document we plan to address success criteria introduced in WCAG 2.1 that may pose specific challenges for conformance verification and testing in the non-Web ICT context."


Then connected to that change, I would also change the 2nd and 3rd paragraphs under Appendix B, from the current text: 

"Since publication of WCAG2ICT, [wcag2ict] WCAG 2.1 was published, introducing a number of additional success criteria, at the A and AA levels. Some of these also pose specific challenges for conformation verification and testing in the non-web ICT context. The 18 noted in WCAG2ICT, along with the success criteria new to WCAG 2.1 which pose specific challenges in the non-web ICT context, are discussed below, in four sections.

Finally, 14 of the 38 A and AA criteria in WCAG 2.0 relate to an accessibility supported interface, which may not be possible for software running in a "closed" environment (e.g. an airplane ticket kiosk)." 

to instead read:

"Since publication of WCAG2ICT, [wcag2ict] WCAG 2.1 was published, introducing a number of additional success criteria, at the A and AA levels. Some of these may also pose specific challenges for conformation verification and testing in the non-web ICT context. A future version of this document will address those new success criteria in the non-Web ICT Context. 

The 18 success criteria noted in WCAG2IC, are discussed below, in four sections, the last of which address the 14 of the 38 A and AA criteria in WCAG 2.0 which relate to an accessibility supported interface, which may not be possible for software running in a "closed" environment (e.g. an airplane ticket kiosk)."

**Comment by sajkaj** [comment]
I've added these edits to the current working branch draft so we can see them in context here: https://raw.githack.com/w3c/wcag/conformance-challenges-working-draft4/conformance-challenges/index.html

**Comment by sajkaj** [comment]
Text is now in [Editor's Draft](https://w3c.github.io/wcag/conformance-challenges/).
