### ISSUE TITLE
Challenges: proposed clarification statement

### ISSUE THREAD

**Issue by avneeshsingh** [w3c/wcag#1111]
Having reviewed this document for digital publishing, we’re generally fine with it. The only suggestion we’d like to make is to include a statement like the following to the last paragraph of the abstract:

“It is not to change or lower the conformance requirements for WCAG 2.X.”

A direct statement that it does not change WCAG 2 would help ensure there are no misunderstandings about its intent.

**Comment by JaninaSajka** [comment]
As explained in [Peter's on list response to Afneesh](https://lists.w3.org/Archives/Public/w3c-wai-gl/2020AprJun/0187.html), the erroneous assertion in the Status Section of the current Editor's Draft of this document will be replaced by Michael with correct language during the publication process. The correction will clearly affirm this document is intended to become a W3C Note, and NOT a specification. Also, the rather cumbersome CSS that pervades each page declaring this document is "unofficial" will also be removed. This erroneous Status Section has confused several people during the publication review process in AGWG. It is an unfortunate byproduct of giving the document the "Unofficial" status tag, and is not easily fixed in the draft, but can and will be remedied for the FPWD. I have personally discussed this issue with Michael and we're both keenly aware the situation is wrong and misleading. Furthermore, as Peter's email notes, AGWG is not chartered to make changes to the WCAG 2.x conformance model, so that concern is also not something AGWG could take on without rechartering--a very unlikely prospect.
