### ISSUE TITLE
Challenges: Moving Beyond the Page

### ISSUE THREAD

**Issue by mgifford** [w3c/wcag#1171]
We are still thinking about accessibility on a page by page basis, rather than a series of components. 

In most well built sites, the header and footer are going to be the same across the domain. They are templates (or series of templates) that are repeated everywhere.  To be scalable WCAG needs to embrace this and help accessibility auditors review what pieces are templated and which are unique. 

HTML which is generated by authors is going to have different challenges than that added by the CMS. Approaches to remediate it are going to be different for both as well.  

Furthermore people don't visit one page of a website, they usually go to a site to accomplish a task. This usually involves starting at the home page (or wherever Google drops them) and then navigating a series of pages from there until a user gets what they need. 

WCAG should reflect how sites are built and how users interact with them.

**Comment by patrickhlauke** [comment]
What is stopping you right now from evaluating components, rather than full pages, when doing audits against WCAG? In most audits I've been involved in over the last 7 years, we've always had samples as part of our evaluations that were just isolated complex components (like header, footer, sidebar, a particularly complex single widget, a video player, etc).

Is it just a case of tweaking language (where WCAG talks most often about "pages", both in core WCAG and accompanying documents like https://www.w3.org/TR/WCAG-EM/#step1)?

>  help accessibility auditors review what pieces are templated and which are unique.

This is something that can only be determined by talking directly to the site owners/development team though, as it's dependent on their actual production environment. While auditors can make an educated guess ("this thing that repeats everywhere is likely a single template file that's then included/reused throughout the site"), the reality is often much grimmer (I've had many cases where sites still had flat files for lots of repeated stuff, and when it came time to remediate stuff, they had to do massive find/replaces everywhere to catch these "common" components).

> Furthermore people don't visit one page of a website, they usually go to a site to accomplish a task. This usually involves starting at the home page (or wherever Google drops them) and then navigating a series of pages from there until a user gets what they need.

https://www.w3.org/TR/WCAG-EM/#step2 ?

**Comment by mgifford** [comment]
Again, let's think about what is stopping a reviewer, but what is encouraging the user to think of the system? In Drupal there can be hundreds of templates that are engaged in building some pages. 

This is about facing the challenges to scaling up WCAG for large dynamic sites. If the metaphors that we use to think about and describe accessibility are focused on pages, we are going to miss that. I don't know what needs to be changed to get people thinking about the systems they are using and the tasks that users engage with their websites, but right now WCAG 2.x assumes that reviewers are looking primarily at pages. 

Why aren't accessibility champions embedded in teams of developers and UX folks. I do like the role of an accessibility auditor to be considered more closely to that of an editor. They should work with the team of developers to help identify issues without the understanding and biases that the authors of the site will have. 

https://www.w3.org/TR/WCAG-EM/#step2 is useful. I'd want to be far more specific. If a CMS or framework is used, what is it?  Are there known accessibility issues in it, and with the themes, plugins/modules used? Are there user journeys & personas available for understanding how the site is intended to be used. Are there feedback-loops for users, when accessibility issues are identified.
