### ISSUE TITLE
Please clarify that WCAG's Info & Relationships SC requires that checkboxes and radio buttons have clickable labels, i.e. programmatic "relationship" associations and a title alone will not suffice. 

### ISSUE THREAD

**Issue by pauljadam** [w3c/wcag#122]
There are no examples in WCAG's documentation that show a radio button or checkbox without a visible label that is programmatically connected to the input so that you can click on the label to check the checkbox or radio button. 

A checkbox has at least 3 requirements: 
- accessible name via Name, Role, Value
- visibile label via Labels and Instructions
- programmatic relationship association via Info and Relationships

Take the demo of an ARIA checkbox: 
https://accessibility.oit.ncsu.edu/training/accessibility-handbook/aria-checkbox.html

WCAG requires that the checkbox's label is clickable whether that's a native checkbox or a custom ARIA widget. 

I'm hearing many Accessibility experts, co-workers and in the field, who are saying it's only a "Best Practice" that the label must be associated to the input thereby making it clickable to check the box.

I don't see how this could not be a requirement of SC 1.3.1 Info and Relationships. I don't see how anyone could get that idea when all the WCAG examples show clickable labels on the checkboxes and radio buttons?

Please consider clarifying this further. I appreciate any discussion on the topic!

There's also a thread on the WebAIM email list, http://webaim.org/discussion/mail_thread?thread=7224, and discussion on Twitter. 

Also: I would be very happy to contribute a Failure and Success Technique on lack of clickable checkbox/radio button labels. 

Thanks!

**Comment by MichielBijl** [comment]
+1

**Comment by awkawk** [comment]
We can discuss this in the group.

**Comment by pauljadam** [comment]
Thanks Andrew!

**Comment by MichielBijl** [comment]
@awkawk could you post a link to the minutes once discussed? A notice for when it's on the agenda would be appreciated, too.

**Comment by MakotoUeki** [comment]
Hi Paul and WG members,

The point would be that the SC 1.3.1 reads "conveyed through presentation". The intent of the SC is to make web content machine readable.

If there is a visible label text for a form control and the label text is visually recognized as the label for the form control (e.g. side by side), the label text must be programmatically determined.

> So the code is WCAG Compliant?
> <input title="Sign me up!" type="checkbox" />
> <label>Sign me up!</label>

Regarding your question in the thread on the WebAIM email list, I don't think the code is WCAG compliant. Because the label text itself (<label>Sign me up!</label>) is not programmatically determined.

And whether the label text must be clickable or not is a browser issue. What web content must do is to make the relationship between the visible label text and the form control programmatically determinable, in other words, machine-readable and/or machine-understandable.

**Comment by pauljadam** [comment]
Thanks for the comment Makoto. So yes WCAG does not require that the label be clickable but it does require that the label be programmatically associated with the input and if the developer associates the label to the input with FOR/ID or wrapped labels then the label will become clickable as a result of the programmatic association.

**Comment by MakotoUeki** [comment]
Yes, that's my understanding. We might need to check if UAAG mentions this topic.

**Comment by awkawk** [comment]
@MichielBijl I suspect that we will handle this one entirely on the list rather than on the call and with a CfC process on the response.  You can see the discussion at https://lists.w3.org/Archives/Public/w3c-wai-gl/

**Comment by awkawk** [comment]
@MakotoUeki There isn't a specific reference to this in UAAG that I can find.

**Comment by awkawk** [comment]
Proposed response (to be shared with the WG for approval):
WCAG 2.0's success criteria 1.3.1 does not require that the relationship between the label text and the checkbox or radio button be determined only using the explicit mechanisms where the label element contains the input element or where the label and the input are associated using the 'for' and 'id' attributes.

Both of these mechanisms are effective and in fact are highly recommended, but they do not constitute the only way that an author can satisfy SC 1.3.1.  An author might satisfy this success criteria using the title attribute on the radio button or checkbox, taking care to make sure that the accessibility name provided for the control in the title attribute is equivalent to the content of the visible label.

The HTML examples in WCAG documents utilize the mechanisms that the Working Group feels are ideal for this situation, and they are used to encourage authors to utilize these mechanisms, but that does not mean that other ways are not sufficient also.

In the course of the discussion on this topic we feel that a failure technique is needed which demonstrates a title attribute on a checkbox where the attribute value is not equivalent to the visible label.  The working group would welcome a submission for such a failure.

**Comment by pauljadam** [comment]
Hi Andrew so the labels are not required to be programmatically associated to their inputs? The relationship requirement is not "programmatic association"?

**Comment by srinivasuchakravarthula** [comment]
Paul,

Here I would agree with Andrew and all others. 

If I understand correctly, your ask is to make label of checkbox to select. In fact this should be applicable for radio buttons too. But this behaviour is not something that WCAG should dictate but perhaps HTML spec. 

As far programmatic association is concerned, it does pass with existing SC. 

Just my 0.02 paisas. :-) 

Regards,
Srinivasu Chakravarthula | @csrinivasu

**Comment by detlevhfischer** [comment]
I think that in cases where individual labels are used next to checkboxes or radio buttons, they constitute a part of the respective control. That"s why I think it is fair to mandate an explicit association for those cases to aid the many users with motor impairments that find it hard to place a mouse click on the control itself. 
I would allow for exceptions only in cases where the design does not allow for sufficient space for individual visible labels, as in the case of checkboxes placed within tables. Here, the title attribute, aria-label attribute of some accessibility`supported programmatic association with table headers via aria-labelledby can be used.
So like Adam, I think it fair to define a failure for cases where the label is adjacent to the control but authors have failed to make the connection programmatically determinable,

**Comment by DavidMacDonald** [comment]
Andrew's response is my understanding of WCAG consensus which was in play during the creation of the WCAG. Personally, I would have voted for forcing the "click the label to select" paradigm ... but that was not the consensus. If the title or other invisible label reports the visible label in a programmatic way (today via the API), I believe this was the main concern during the formation of the WCAG. 

I need to put aside my personal preferences in favour of being true to what I know was the consensus of the time, which I respect. I would be fine with revisiting this in an extension spec or even WCAG.next

**Comment by johnfoliot** [comment]
> That"s why I think it is fair to mandate an explicit association for those cases to
> aid the many users with motor impairments that find it hard to place a mouse
> click on the control itself. 

I strongly disagree with this. 

First, it is not WCAG's role (historically or currently) to mandate specific behaviors to user-agents. Even if we were to agree that this is a strict requirement, it would be a User Agent requirement in UAAG, and not an authoring requirement in WCAG. The interactive association that some are seeking is already manifest by using the &lt;label> element, and like it or not, the Accessible Name (the programmatic association) of a radio button or checkbox can also be determined by using @aria-label, @aria-labelledby, and @title. This is how the browsers are wired up, this was how ARIA was designed, and asking them to change now is both irresponsible, as well as breaking at least 2 aria attributes in this example.

>I would allow for exceptions only in cases where the design...

As this thread has pointed out elsewhere, there are instances when this would not work, as in the Gmail example shown by Steve Faulkner (https://lists.w3.org/Archives/Public/w3c-wai-gl/2015OctDec/0194.html). You cannot have a "maybe yes, maybe no" situation, based simply on individual circumstances or design, be an absolute Standard requirement. How would you evaluate the design to determine whether or not a particular instance was conformant or non-conformant? Your proposal now makes accessibility conformance even more subjective than it already is.

The argument here is apparently with the fact that radio buttons and checkboxes are natively too small to be a clickable control for some users. Do we have any proof, anecdotal or otherwise, that supports this claim? Radio buttons and checkboxes have been with us since the dawn of HTML, and if the actual issue is focused on the 'clickability' of these controls then we should focus our concerns there (while still remembering that form inputs can be tabbed into and out-of: there is not a mandated requirement that the only way to interact with checkboxes is via mouse-input).

One possible alternative solution is to change the size of the checkboxes:
<code>
input[type=checkbox] {
  /* All browsers except webkit*/
  transform: scale(1.75);

  /* Webkit browsers*/
  -webkit-transform: scale(1.75);
}
</code>

For these reasons, I reject making any changes here and SUPPORT the current statement:

> WCAG 2.0's success criteria 1.3.1 does not require that the relationship between
> the label text and the checkbox or radio button be determined only using the
> explicit mechanisms where the label element contains the input element or where
> the label and the input are associated using the 'for' and 'id' attributes.

I am in favor of improved author guidance which can outline why using &lt;label> with @for and @ID is the better solution, but I oppose any changes to WCAG that attempts to impose user-agent behaviors, and further point out that whether or not the other 3 techniques meets the needs of ALL users is not the issue: those techniques ensure that the checkboxes are programmatically associated with the Accessible Name in the Accessibility APIs, which is what the current standard calls for. If browser or other user-agents want to change how they interact with these elements and attributes they should be encouraged to do so. WCAG however is not the place or the vehicle to do attempt to affect this change.

**Comment by pauljadam** [comment]
Hi John, all I'm saying is that WCAG's Info and Relationships SC Requires that labels be programmatically related to their inputs. As as result of that relationship then the user can click on the label to check the checkbox. 

I'm not saying that web browsers are required to make the label clickable. They already do if there is a relationship between input and label. 

The requirement is not for blind users only. This is to help people who have shaky hands, difficulty controlling a mouse, tapping tiny checkboxes on a mobile device, people who need to speak the label of a control to activate it.

I'm not sure why you don't think it's easier to check a checkbox with a label connection than to check one without? Here's some "proof":
https://www.aaron-gustafson.com/notebook/labeled-with-love/
http://www.nngroup.com/articles/checkboxes-vs-radio-buttons/
http://zurb.com/article/195/make-web-forms-suck-less-with-labels
http://www.coolfields.co.uk/2011/04/accessible-forms-should-every-input-have-a-label/

**Comment by srinivasuchakravarthula** [comment]
+1 to John. 

Also, nowadays any way we are seeing custom check boxes and radio buttons that are neat and large enough. 

Regards,
Srinivasu Chakravarthula | @csrinivasu

**Comment by joshueoconnor** [comment]
Very interesting issue and thanks to Paul for bringing it up. To me you outline two separate issues. One talking about how the need for programmatic determination and the other, the user agent/user interaction with that content. IMO Makoto framed the current status well - WCAG is largely concerned now with ensuring content has the correct relationships. From a WCAG perspective, we have to be cautious, as John points out.  This could be an interesting one for UAAG - and I'm currently happy with AWKs suggested response, unless I hear more compelling input.

**Comment by MikeElledge** [comment]
Hi All--I find the sentence difficult to understand. Would it be clearer to say something like: 

"WCAG 2.0’s success criteria 1.3.1 allows relationships between label text and checkboxes or radio buttons to be shown explicitly (with labels) or implicitly (without labels), so long as they can be determined programmatically."

**Comment by detlevhfischer** [comment]
Another stab at a formulation:

"WCAG 2.0’s Success Criterion 1.3.1 requires that for checkboxes or 
radio buttons, a label text can be programmatically determined. This 
text may be provided as a visible label element that is programmatically 
linked to the control, or by some other means as long as the text can be 
determined programmatically.
(Note that Success Criterion 3.3.2 requires a visible label for 
checkboxes or radio buttons.)"

Detlev

Am 01.12.2015 um 16:16 schrieb MikeElledge:
>
> Hi All--I find the sentence difficult to understand. Would it be 
> clearer to say something like:
>
> "WCAG 2.0’s success criteria 1.3.1 allows relationships between label 
> text and checkboxes or radio buttons to be shown explicitly (with 
> labels) or implicitly (without labels), so long as they can be 
> determined programmatically."
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/w3c/wcag/issues/122#issuecomment-160997950>.
>


-- 
---------------------------------------------------------------
Detlev Fischer PhD
DIAS GmbH - Daten, Informationssysteme und Analysen im Sozialen
Geschäftsführung: Thomas Lilienthal, Michael Zapp

Telefon: +49-40-43 18 75-25
Mobile: +49-157 7-170 73 84
Fax: +49-40-43 18 75-19
E-Mail: fischer@dias.de

Anschrift: Schulterblatt 36, D-20357 Hamburg
Amtsgericht Hamburg HRB 58 167
Geschäftsführer: Thomas Lilienthal, Michael Zapp
---------------------------------------------------------------

**Comment by goetsu** [comment]
I agree with @MakotoUeki and @detlevhfischer proposal.
If the label is visible and can be identified as a label it must be tagged as a label and relationships conveyed through this presentation must be programmatically determined. To do that you can : 
- use for/id
- use aria-labelledby on the input
- put the input inside the label

title or aria-label can't be use only if the input don't have a visible label or if the visible label isn't explicit enough (for example "yes" / "no" value as label VS "yes I love unicorn" / "no I don't love unicorn" title

**Comment by awkawk** [comment]
@goetsu, I don't think that Makoto and Detlev are saying the same thing.

**Comment by goetsu** [comment]
Yes @awkawk but i agree with both makoto for the need of label when visible label and detlev on need of relationship that his proposal make more clear

**Comment by MakotoUeki** [comment]
@awkawk I think @goetsu has the same understanding with me on what the SC means and what are required to meet the SC. I don't think that using the title attribute would meet this SC when there is a visible label text, even if it could provide the same accessible name to the form control.

**Comment by goetsu** [comment]
just a correction on my previous comment  aria-label can't be use if you don't have any visible label because it doesn't generate visible label (at least like a tooltip with the title)

(And I also think in that case title is a poor solution since it's not visible for keyboard user in most browser and can be tricky for zoom user too but it's conforming)

**Comment by awkawk** [comment]
Official response:
The Working Group view is that WCAG 2.0 does not require that checkboxes and radio buttons have clickable labels.  The Working Group agrees that there is utility for end users when the labels for these (and other) controls are clickable, but there are no success criteria that make this specific requirement.  

Related to this question is whether the page content used as the visible label for the control (in order to meet SC 3.3.2) must be explicitly associated with the control that is being labeled. The proposed consensus view is that the relationship between a control and the content used to label that control may be made implicitly as well as explicitly, and what will really dictate whether SC 1.3.1 (as well as SC 4.1.2) is met is whether the assistive technologies used in the site’s conformance claim are able to provide support for the implicit or explicit relationships provided in the markup. An explicit markup relationship (e.g. Using the HTML for and id attributes to make the association or by enclosing the input within the label element) is preferred as it will increase the likelihood that user agents will support the design pattern and will simplify testing, but implicit relationships may also be supported and as a result may satisfy WCAG 2.0 success criteria.

The working group agrees that there is benefit to many users when they can click on a larger area for a checkbox or radio button and on some user agents using the label element in conjunction with an input can make this happen without any work by the page author.  Despite the benefit, this was not part of the original intent of WCAG 2.0, so the working group will forward this issue to the task forces that are currently working on extensions for WCAG 2.0 for review as a topic for consideration within an extension. In addition, this issue will be added to the “Post WCAG 2.0” wiki page (https://www.w3.org/WAI/GL/wiki/Post_WCAG_2_Issues_Sorted) for issues that the group wants to keep a record of for consideration in future versions of WCAG.
