### ISSUE TITLE
Challenges: Multi-language support

### ISSUE THREAD

**Issue by fredesch** [w3c/wcag#1221]
As a Blue Cross/Blue Shield Affiliate in Florida our websites are in English and Spanish. Content is usually injected as translated resources. Errors we may see on a Spanish language page that isn't on an English page are the occasional img element alt text that has been hardcoded. We do check that page's HTML element have the appropriate lang attribute (language of page) and only one element - the button that toggles between English and Spanish - needs a lang attribute (language of parts).

We do have downloadable Spanish language PDFs which have the same content in English after the Spanish (I believe the English is required for legal reasons).

Beyond language of page/language of parts do we incur an additional accessibility testing burden for supporting both languages? Should we be checking both the English and Spanish pages even though they only differ by text content? We don't have a Spanish language accessibility tester.

**Comment by mraccess77** [comment]
Hi @fredesch it depends on how the Spanish content is translated.  For example, you may be catching image alts - but are there use of aria-label, off-screen text for CSS, or content content a translation service may have missed that might be in an accessibility property?  Also you may need to consider that when something is translated it may take up more room on-screen causing overlfow issues when zoomed or when text spacing is changed.  I often see contrast problems when content overlaps unexpectedly with languages where the translated text may be longer than the primary text was.

**Comment by guyhickling** [comment]
> We don't have a Spanish language accessibility tester.

I would suggest, as a minimum, that you download the NVDA screen reader for the blind (it's free), and listen to all your Spanish pages using that. That will pick up any items inadvertently left in English.

And ask whoever did the translating for you, did they just translate the on-screen content, or were they also given the HTML sources to, as @mraccess77 says, translate all the ARIA, alt texts and other hidden text? That may not have happened.

Also look for English language content on the Spanish screens. If your address is shown anywhere, that will be in English, so will need an English lang attribute round it on the Spanish version! Probably also your business name since it will be in one language and not the other. Check on your Terms and Conditions page for any texts untranslated for legal reasons and give them English lang attributes.

**Comment by JaninaSajka** [comment]
Alastair: I don't see this issue isn't really about the Challenges with Conformance document, so I removed that label. If I'm wrong, I guess I need more info on how it relates.
