### ISSUE TITLE
Challenges: Guideline 1.4.4 and Adaptive Design

### ISSUE THREAD

**Issue by fredesch** [w3c/wcag#1222]
Our sites have 3 views (mobile, tablet, desktop). Headers, footers, eye candy and breadcrumbs are optimized for each view. As the real estate gets smaller, stuff disappears or morphs to a subset of what is in a larger view. We believe this provides a better user experience. 

We also believe that by creating 3 views, we may technically violate guideline 1.4.4 Resize text since the cutoffs between views is not a full 200%. Is there any relief in the works from 200% or is an allowance made for media query based views? If we are not violating guideline 1.4.4 then can you make that clear in the success criterion?

**Comment by patrickhlauke** [comment]
> stuff disappears or morphs to a subset of what is in a larger view

if it completely disappears, then yes you're likely failing both 1.4.4 and 1.4.10 Reflow. regardless of viewport size, users should somehow have access to all content/functionality (even if it means splitting the content that is all available in larger views into sub-pages, modals, disclosure widgets, etc). otherwise, you're disadvantaging users who use resizing/zoom, have smaller monitors/keep their browser window at less than what you deem "desktop-size", etc.

**Comment by guyhickling** [comment]
> We also believe that by creating 3 views, we may technically violate guideline 1.4.4

You are quite correct in having different views or layouts for desktop, tablet and mobile. That is "Responsive Design", and the Reflow SC (1.4.10) in WCAG 2.1 virtually requires responsive design in order to comply with it.

However the media query breakpoint does not have to be at exactly 200%. SC1.4.4 merely requires that, at 200%, whatever media queries that may have been triggered at that magnification have been done without losing any of the content or functionality that was shown on the desktop view. I.e nothing must have 'disappeared' as you describe it. I'm not quite sure what you mean by "morphs to a subset of what is in a larger view", but if that means you are only allowing tablet or mobile users to see part of the desktop content, then that is a failure of SC1.4.4 and/or 1.4.10. And if you are following 'mobile first' practice, you cannot add more content in the desktop view that is not available in the mobile layout - but they can be displayed in different layouts. 

It must all be there somewhere and reachable (and that doesn't mean it can be buried several links away on some other page, only findable by someone who knows it's there!) One very common way to hide content on a small screen is to add a button that reveals it when clicked, and Patrick has just mentioned other ways as well. So there is no need for "any relief in the works from 200% or ... allowance made for media query based views". The purpose of the WCAG is to ensure disabled people (people with poor vision in this case) are not deprived of information or facilities that people with good eyesight enjoy.

Likewise at 400% zoom, regardless of what media queries have been used before that magnification, all the content must be still be available (though 1.4.10 adds the additional requirement that it must all show on the screen without horizontal (on a normal western language website) scrolling. 400% zoom on a desktop PC basically shows the mobile layout.

**Comment by JaninaSajka** [comment]
Alastair: Ditto as per Issue 1221--not really about the Challenges with Conformance document.
