### ISSUE TITLE
Avoid confusion about WCAG versions in the header

### ISSUE THREAD

**Issue by Veyfeyken** [w3c/wcag#1224]
Hi, 

Each version of WCAG, for example 2.0, has several links at the top including a "latest version". The refers to the latest version of a certain version of WCAG. For example 2.0:

> Web Content Accessibility Guidelines (WCAG) 2.0
W3C Recommendation 11 December 2008
This version:
http://www.w3.org/TR/2008/REC-WCAG20-20081211/
Latest version:
http://www.w3.org/TR/WCAG20/
Previous version:
http://www.w3.org/TR/2008/PR-WCAG20-20081103/

One would aspect that the link "latest version" would lead to WCAG 2.1 instead of the latest version of 2.0. 
A visitor of the 2.0 page has no idea a 2.1 version even exists. There no mention of it. No link to it. Clicking 'latest version' enforces the idea that 2.0 is the latest version instead of 2.1.

Only people who are familiar with W3C documents understand the current pattern?
Perhaps an update to the template of these documents can avoid confusing?

Kind regards,

Gijs

**Comment by guyhickling** [comment]
An excellent point, I for one agree. And when 2.2 is released, these links should then be amended to point to 2.2. I suspect a lot of people in the web dev and IT management world still think that 2.0 is the latest version!

Alternatively if it is felt necessary to keep the versions separate in this link list, then I suggest:

1. add a new link "Latest version of WCAG" to this list of links, preferably at the top of the list so it is seen by everyone first
2. amend the existing "Latest version" link to "Latest version of WCAG 2.x"

**Comment by mbgower** [comment]
Draft response

Thank you for your submission. The most recent version of the [WCAG 2.2 editor's draft](https://w3c.github.io/wcag/21/guidelines/) contains a new entry in this top-level template area called "Latest Recommendation", which links to the most recently published recommendation. A "Recommendation" has specific meaning in W3C terminology.
>A W3C Recommendation is a specification or set of guidelines that, after extensive consensus-building, has received the endorsement of W3C Members and the Director. W3C recommends the wide deployment of its Recommendations. Note: W3C Recommendations are similar to the standards published by other organizations.

As such, any new version of WCAG only in working draft will point _back_ to the latest full release. With older versions of prior releases of the standard, it will point _forward_  to the latest recommendation.

**Comment by mbgower** [comment]
@alastc since this change to the template is already in place, I believe this may not even need a survey to be considered closed.

**Comment by alastc** [comment]
@mbgower once a rec is published, it doesn't get updated unless it is replaced, so it can't point forward. (Apparently the world ends if the date on the front changes?! I haven't gotten to the bottom of that reasoning yet.)

When WCAG 2.0 talks about the latest version, that is of WCAG 2.0, it didn't know there would be a 2.1 (and so on for 2.1 to 2.2 etc).

Generally the latest rec version will be at: 
https://www.w3.org/TR/WCAG/ 

And associated resources (like the WAI docs and announcements) will point to the latest version.

> A visitor of the 2.0 page has no idea a 2.1 version even exists. There no mention of it. 

The solutions to this are for other resources to link to the latest version, because at the time 2.0 was published the spec (and group creating it) didn't know there would be a 2.1.

**Comment by alastc** [comment]
Closing this as the only solutions are outside of the specification itself. We can't change the previous template or re-publish the older specs.

**Comment by Veyfeyken** [comment]
> Generally the latest rec version will be at:
> https://www.w3.org/TR/WCAG/

Adding that at the top of the template would be an improvement.

**Comment by Veyfeyken** [comment]
Just noticed this when navigating to an older version:

<img width="830" alt="modal with text This version is outdated! For the latest version, please look at https://www.w3.org/TR/WCAG21/." src="https://user-images.githubusercontent.com/870049/141453591-90eb0858-bfd2-4389-810b-93f761b090bf.png">

Adding exactly that at the top of the page would eliminate any confusion?

**Comment by patrickhlauke** [comment]
problem with that approach is that there's legislation etc still referencing older versions of specs authoritatively (see for instance current 508 refresh that references WCAG 2.0), so for those situations it'd add even more confusion for different reasons. it's a bit heavy handed perhaps

**Comment by Veyfeyken** [comment]
> problem with that approach is that there's legislation etc still referencing older versions of specs authoritatively

Is that really a problem? Legislation points to old standards all the time. Even then, it's good to know it's not the latest version of that standard?

**Comment by bruce-usab** [comment]
@Veyfeyken I have a prejudiced perspective, but yes it would be problem for a finalized version to characterize itself as <q>outdated</q> because (in the U.S.A.) the date certain version is the one that carries weight with regulators and the judicial system.

From a proactive developer perspective, it would be nice if, when landing on 2.0, there a was a link to 2.1 (or should it be 2.2 now).  But I feel like there are already a lot of prominent paths the most current materials.
