### ISSUE TITLE
SC 3.8.8 - duplicating emails in a signup flow: also a 'security verification', or not?

### ISSUE THREAD

**Issue by camusamta** [w3c/wcag#1288]
It's common in signup flows that users are required to repeat an email twice to (supposedly) reduce the error of inputting an incorrect email at the beginning of entering into a service relationship. Is this considered ok per this SC, so long as this repetition is done within one 'step'? Is this something that's instead considered 'essential' or a 'security verification'?

**Comment by wardav** [comment]
I would assume that any duplication required for security or to make absolutely sure that the information is right is out of scope. For example, your bank asks you to re-confirm your sort-code or you need to enter your email twice during sign-up.

In this case, the redundant entry requirement is an intentional part of the design as it is important that the user is absolutely sure that the information is correct. That is, it is by design. It is important to check that the data is accurate.

I would generally assume that _indicental_ duplication is in scope, but that _intentional_ duplication is not. I would assume that it all falls into "Security verification, such as repeating a password, is considered essential."
