### ISSUE TITLE
SC 2.4.12 - want to confirm the requirement for a 'solid' border

### ISSUE THREAD

**Issue by camusamta** [w3c/wcag#1289]
I was always under the (perhaps incorrect!) assumption that, in the instance of say, a button that already has a thick border as its unfocussed style, to add then a dashed and offset outline would be the most significant way to differentiate it from the unfocussed state. Just looking for some clarification.

**Comment by juleskuehn** [comment]
There is no requirement for a solid border. It is only mentioned as an intuitive way of calculating the required focus indicator area.

If you have a 90 x 30px button, the required focus indicator area would be 90 + 90 + 30 + 30 = 240px. You can still use a dashed focus indicator, but the number of pixels that have changed (with a 4.5:1 contrast ratio vs unfocused) would still be 240. In other words, you would have to use a >2px border if it was dashed to meet this requirement.

**Comment by alastc** [comment]
@juleskuehn is correct. It is worded to guide people towards a reasonably thick & solid border, but it does allow for other methods.

**Comment by alastc** [comment]
> in the instance of say, a button that already has a thick border as its unfocussed style, to add then a dashed and offset outline would be the most significant way to differentiate it from the unfocussed state.

What 2.4.11/12 are trying to acheive is setting a minumum bar for visibility, differentiation. 

If a button already has a thick border that contrasts with the background, then adding a thin extra border won't stand out very well. E.g. a 1px dark outline around a button with a 3px dark border.

If you off-set it, then yes, that does help it stand out, that's why the 3rd bullet of 2.4.11 is:
> Adjacent contrast: The focus indication area has a contrast ratio of at least 3:1 against all adjacent colors for the minimum area or greater, or has a thickness of at least 2 CSS pixels.

So if it is adjacent then it is harder to spot (without contrast to the button), but when moved away from the button with offset, it becomes easier to see. Or, it can contrast with the button _and_ background.

Dotted/dashed it easy to see when thick, but the experience with Firefox's default is that a 1px dotted outline is often difficult to see.

Does that clarify things @camusamta?

**Comment by camusamta** [comment]
Completely understand, thanks all.
