### ISSUE TITLE
confusing wording in dfn-pagebreak-locator

### ISSUE THREAD

**Issue by carmacleod** [w3c/wcag#1317]
https://www.w3.org/TR/2020/WD-WCAG22-20200811/#dfn-pagebreak-locator

1. Delete extra "is"
   > A digital book is published ~is~ with no print equivalent

2. Reword sentence, because it currently doesn't make sense
   > Synchronizing reading people with different form factors and platforms, screen sizes, can be on the same page.
   - who/what are "reading people"?
   - who/what can be on the same page? ... "Synchronizing" or "reading" or "people"?

**Comment by gradualclearing** [comment]
Proposed edits to remove confusing and apparently unrelated content, use "electronic publication" as defined, and improve consistency with other definitions.

pagebreak locators
[New]
visual and/or programmatic markers that are arranged in a meaningful sequence to determine the location of a page in relation to others in an electronic publication

Examples include:

- corresponding pages between a print publication and an electronic version of the same publication
- an electronic publication with no print equivalent, where pagebreak locators are inserted to support direct navigation across platforms and form factors

**Comment by alastc** [comment]
Thanks @carmacleod, as those are editorial I'm going to merge straight in.

@gradualclearing - thanks for taking a look, I think in this case the issue is more straightforward and is just a couple of minor updates.
In looking at your proposal, I wasn't sure if you intended to remove the other examples or were just showing the changes? Also, it is generally better to avoid referencing other definitions in a definition, if possible (it isn't always).
