### ISSUE TITLE
Non-visual status message has wrong language - FAIL in 4.1.3, or elsewhere?

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#1342]
I'm looking at a combobox that generates a non-visual status message beautifully announcing the number of matching entries in the dropdown list when entering a search term (and a hint about arrow key navigation) - but in the wrong language. Where would you FAIL this?

- 4.1.3 Status Messages - but what is checked here seems more whether the message is programmatically exposed, not whether it is descriptive
- 3.3.2 Labels and Instructions - but this seems more about whether instructions are visually present, not about their descriptiveness
- 2.4.6 Headings and labels - The text is descriptive and correct, but in the wrong language. From the Understanding text it is unclear whether this SC applies also to additional screen reader hints that are not available for sighted users
- 3.1.2 Language of parts - language markup is not the issue here, or is a separate issue

I am leaning towards failing this under 2.4.6 - any thoughts?

**Comment by awkawk** [comment]
@detlevhfischer I would say that the core issue for this isn't covered by WCAG. I would file an issue if the message isn't indicating the language correctly (3.1.2) but I'd mostly just make sure that the developer knows that they have a problem.

I'm tempted to say that this is a problem that affects all users, but since this is non-visual text that isn't really true. If a status or instructions were shown visually and in the wrong language I would definitely say that, but this is different. Still, I don't think that there is an SC that addresses this, as I understand it.

**Comment by brennanyoung** [comment]
I can find no explicit guidance for how SC 3.1.2 is supposed to work with live regions. 

More than one market-leading AT fails to respect the lang attribute with live regions. The wording of this SC _implies_ that live regions should simply respect any lang attribute like any onscreen text, but when at least two major AT vendors are failing to do this, we might want to look at whether the SC is documented adequately.

In particular I would like to see some indication in the Understanding doc on 3.1.2 about **live regions with content in more than one language**. (If you want a use case, imagine a chat log in Belgium or Canada). 

Could we perhaps develop some sufficient or advisory techniques for these scenarios?

**Comment by patrickhlauke** [comment]
@brennanyoung i think your question here is not related to this issue per se (which was more about the author actually having the message in the wrong language in the content, rather than AT failing to switch to the correct language/pronunciation).

beyond filing bugs against AT, there's little developers themselves can do - can't think of any kind of advisory technique or otherwise that would work around a failing of the AT to correctly switch to the language defined by the content explicitly or implicitly. you can but assess 3.1.2 based on whether the author has done it technically right here ... there's no fallback technique to force a language switch in any other way.

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
