### ISSUE TITLE
What types of electronic publications are intended to be covered by 2.4.13 Fixed Reference Points?

### ISSUE THREAD

**Issue by stringyland** [w3c/wcag#1422]
My reading of this criteria is that if there are pagebreak locators in an electronic publication, the author or user agent should provide a mechanism for the user to jump to specific locators. It would be similar to Bypass Blocks, allowing people to jump to known locations instead of being forced to navigate linearly or rely on search.

However I'm not certain if this criteria applies to electronic publications which are not websites, e.g. PDF, ePub? The phrase _"A web page or set of web pages which is an electronic publication"_ seems to limit this criteria to websites of a specific type. But the example in the [Understanding page](https://www.w3.org/WAI/WCAG22/Understanding/fixed-reference-points.html) is about an ePub document. 

As my own example:
- I think 2.4.13 would apply to the site [EloquentJavaScript.net](https://eloquentjavascript.net/), which is [a set of web pages](https://www.w3.org/TR/WCAG22/#dfn-set-of-web-pages) _and_ an [electronic publication](https://www.w3.org/TR/WCAG22/#dfn-electronic-publications). 
- I don't think it would apply to the ePub version of Eloquent JavaScript, which can be downloaded from the home page. The ePub is an electronic publication, but is not a set of web pages. 
- I wouldn't read this criteria as applying to an Amazon page selling a book about JavaScript, because Amazon.com is a set of web pages but it isn't an electronic publication.  

Is this the intention of 2.4.13? If not, and it should apply to ebooks and PDFs, I'd suggest rephrasing to remove websites as a condition. Something like:

> When an electronic publication has pagebreak locators, a mechanism is available to navigate to each locator and each locator maintains its place in the flow of content, even when the formatting or platform change.

**Comment by AndrewArch** [comment]
yes, definitely needs better clarification

**Comment by alastc** [comment]
@DavidMacDonald could you take a look at this one?

**Comment by alastc** [comment]
Draft response:

<hr>

> I'm not certain if this criteria applies to electronic publications which are not websites, e.g. PDF, ePub? 

We are slightly confined in that the "Web Content" accessibility guidelines have in scope web content, not other digital media. However, that does include PDFs and ePub files when they are accessible at a URL. The "web page" definition revolves around resources available at a URL:

> "a non-embedded resource obtained from a single URI using HTTP plus any other resources that are used in the rendering or intended to be rendered together with it by a user agent"

So anything rendered by a browser from a URL would be in scope, as are PDFs and ePubs when available from a URL and rendered directly by a user-agent. 

For your examples:

- The site EloquentJavaScript.net: It would be an 'electronic publication' because the content of the book is presented as web pages, but unless it has 'page break locators', it is not in scope of the SC. 
- The ePub version of Eloquent JavaScript: The download version would not be in scope, but if it were presented online (e.g. Kindle cloud reader) that version would be in scope.
- An Amazon page selling a book about JavaScript: No, a page about a publication is not the publication.

> [if] it should apply to ebooks and PDFs, I'd suggest rephrasing to remove websites as a condition

Hopefully you can see from our scope and the definitions of web pages that it applies to those files-types in certain conditions (i.e. when available online). Obviously, if you make one file for different conditions then the practical implication is that the files should conform, but that's from our scope.

In practice PDFs will always pass as the page-breaks and user-agent deal with it automatically. However, ePubs are what this will apply to most in practice.

**Comment by alastc** [comment]
Update:
Hi @fstrr, 

We've got a new version which removes the use of electronic publication, so it is basically "if you add page break locators, then add a navigation mechanism":
https://raw.githack.com/w3c/wcag/wcag22-fixed-ref-points-updates-2021-jan/understanding/22/fixed-reference-points.html

Either that will be agreed (and go out for review again), or the SC will be deferred, so I'm closing this issue.

Thank you for commenting, having several comments like this on the SC helped to guide our thinking.
