### ISSUE TITLE
Web-based course - exempted from 1.4.10 Reflow?

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#1465]
SC 1.4.10 Reflow says "except for parts of the content which require two-dimensional layout for usage or meaning." and explains in the second note: "Examples of content which require two-dimensional layout are images, maps, diagrams, video, games, presentations, data tables, and interfaces where it is necessary to keep toolbars in view while manipulating content."

I am trying to work out if and how to apply SC 1.4.10 to web based course that launches in a new browser window without toolbars, where body has role=application, and resizing the window resizes /scales the entire content. The course is timed with a lot of audio and animated images and texts appearing at certain times, has a player controls-like progress bar at the bottom, but it is technically not implementend as video - and there are many views where technically things **could** be presented in another layout (after reflow). ( Other parts of the course have content where arguably two dimensional layout is required, such as diagrams).
What is your understanding of the applicability of 1.4.10 Reflow to courseware like this? Is it a reasonable ask for presentation-like, timed courseware with the occasional interaction (picking the right answer)? Do you think a wholesale exempting of a course in 1.4.10 is justified if (most of) the content would theoretically allow for reflow?

**Comment by patrickhlauke** [comment]
i'd say the case for the exemption are few and very far between. and generally more along the lines of "if it were made to reflow, would it fundamentally break the core purpose of the thing?"

by the sound of it, your case wouldn't ... it would just be lots of hard work, which is not a reason for being exempted.

**Comment by JAWS-test** [comment]
I would be generous in interpreting the exceptions, because the first sentence in Understandig is

> The intent of this Success Criterion is to support people with low vision who need to enlarge text and read it in a single column

I.e. as long as I don't have to scroll text and a certain arrangement of the page is important for the presentation (i.e. even without zooming it can lead to the fact that everyone has to scroll, e.g. on a somewhat narrower display), 1.4.10 could be considered fulfilled, because scrolling from pages is not a problem in itself, as long as I don't have to scroll within texts.

**Comment by alastc** [comment]
In a scenario where "resizing the window resizes /scales the entire content", that does tend towards being 2-dimensional.

However, I think the case would need to be made that it is required for that type of content, and it sounded like that was not the case for all/some of the time. They have made that decision for all the content, or possibly because that is how the authoring tool does it.

It's also complicated by the potential end-user scenarios, particularly with text-size requirements, where you'd need a display with 2x the width of the default windows size of the courseware.

Focusing on reflow, my take is that, **_IF_** that is the desired presentation (and from my experience, it isn't great anyway), then the desired behavour would be:
- It opens with a default size;
- Allows zoom, which for more content will cause vertical scrolling (for horizontally read content);
- Content which is inherently 2d (e.g. diagrams) can be treated like images with max-width of 100%, or allowed to scroll horizontally.

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
