### ISSUE TITLE
Stacked SC: SC 1.4.4: Resize text AND 1.4.3: Contrast and zoom Native  UA elements?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1523]
When I change the size of a default Select element to 200% I get the following result in Firefox:

<img width="265" alt="Screen Shot 2020-11-13 at 11 42 37 AM" src="https://user-images.githubusercontent.com/6384002/99063952-92f08580-25a5-11eb-894e-62ae1d0c2363.png">

The text is clipped in the options popup / panel
The contrast of the black on the blue is not 4.5:1 

Do we fail both 1.4.4 and 1.4.3?
There is no exception for native UA elements.

**Comment by JAWS-test** [comment]
I would consider it a failure (at 1.4.4 or 1.4.3). But the problem does not occur with in my testing environment (Windows 10). The select element is scaled correctly when zooming in the browser and when resizing text in Firefox

**Comment by jake-abma** [comment]
I used: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

But if I copy the select code in: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

I get same bad results...

Copy / paste code in developer.mozilla.org page and set text resize only to 200%

<select name="cars" id="cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="opel">Opel</option>
    <option value="audi">Audi</option>
  </select>****

<img width="554" alt="Screen Shot 2020-11-13 at 12 16 57 PM" src="https://user-images.githubusercontent.com/6384002/99066979-2b890480-25aa-11eb-8117-6651d20227d9.png">

**Comment by patrickhlauke** [comment]
In terms of 1.4.4, a tricky one, because as you say the SC normatively doesn't exempt color choices made by the UA. There is a little note in the key term definition for color contrast

> WCAG conformance should be evaluated for color pairs specified in the content that an author would expect to appear adjacent in typical presentation. Authors need not consider unusual presentations, such as color changes made by the user agent, except where caused by authors' code.

but that doesn't seem to fully exempt this particular scenario ... though it can be argued that without additional styling, it should be up to the user agents to make sure they use sufficiently contrasty foreground/background.

Likewise for 1.4.3 (and probably also 1.4.10) the user agent should really strive to avoid loss of content like that.

Fundamentally, these feel like UAAG failures (if UAs actually cared for UAAG), but of course at the end of the day it's end users that miss out on content, regardless who gets the blame.

**Comment by jake-abma** [comment]
yep, another exempt here... while the content creator 'can' fix it for the user need, smells like Silver... thx @patrickhlauke
