### ISSUE TITLE
The term 'spatial relationships" is undefined

### ISSUE THREAD

**Issue by awkawk** [w3c/wcag#156]
Name: Vic Havens
Email: (removed)
Document: TD
Item Number: G142

Comment (Including rationale for any proposed change):
I expect a "spatial relationship" to involve whether things on a page are above, below, left, right, or superimposed on other things. In the description of G142 it states, "This technique requires that the zoom function preserve all spatial relationships on the page and that all functionality continues to be available."
I think it is definitionally impossible for a 200% zoom to maintain spatial relationships since words, images, and controls are rearranged in the zoom process.
In the Tests section the 3rd bullet of the procedure indicates that "all content and functionality" is available. That makes sense but is not (and should not be) dependent on spatial relationships.

Proposed Change:
Perhaps use the term "logical" or "organizational" to modify relationships, rather than "spatial."

**Comment by awkawk** [comment]
Proposed response:
Vic, thanks for the comment.  The use of zoom in this context is the same as it is when used by browsers that support the zoom feature.  This use describes the way that browsers provide a feature to increase the size of the page apparent to the user. The zoom feature on browsers makes the text and everything else on the page larger and the spatial relationships on the page are all preserved.  This is different from the text resizing feature that is available on some browsers where the text reflows around other objects.

We hope this makes the description more clear.

**Comment by joshueoconnor** [comment]
G142 https://www.w3.org/TR/WCAG20-TECHS/G142.html

**Comment by alastc** [comment]
The original description in 142 is:

> The objective of this technique is to ensure content can be scaled uniformly by using a Web technology supported by user agents that change text size via a Zoom tool.
> 
> Content authored in technologies that are supported by user agents that can scale content uniformly (that is, zoom into content) satisfy this Success Criterion. Because this technique relies completely on user agent functionality, it is critical to test with a wide variety of user agents.
> 
> This technique requires that the zoom function preserve all spatial relationships on the page and that all functionality continues to be available.

I suggest:

**The objective of this technique is to ensure content and functionality is not lost when a user scales the content using the zoom feature of their user agent.**

Content authored in technologies that are supported by user agents that can scale content (that is, zoom into content) satisfy this Success Criterion. Because this technique relies completely on user agent functionality, it is critical to test with a wide variety of user agents.

**This technique requires that functionality and content is still available when using zoom, even if the layout or interface is changed due to restrictions of space.**

I think @jnurthen's changes for the rest of the technique (e.g. removing old browser info) were goo

**Comment by joshueoconnor** [comment]
Surveyed 9th Feb https://www.w3.org/2002/09/wbs/35422/20160209/

**Comment by joshueoconnor** [comment]
Surveyed on 9th Feb https://www.w3.org/2002/09/wbs/35422/20160209/results

**Comment by fstrr** [comment]
Closing this as inactive. If it needs to be re-opened, please do so.
