### ISSUE TITLE
As written the WCAG 2.2 SC 2.4.12 Focus Appearance Enhanced doesn't appear to have any adjacent contrast requirements although this is not totally clear in the understanding doc

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#1573]
Am I correctly reading that SC 2.4.12 doesn't require any adjacent contrast but just a 2px solid focus indicator?   If this is the case we should update the understanding document to clarify this as it states "The other aspects of the success criterion are the same as Focus Visible (Minimum).".      Perhaps we could add some wording indicating that no requirement for adjacent contrast is required because a 2px wide indicator increases the size of the control sufficiently which provides distinction.

**Comment by alastc** [comment]
> Am I correctly reading that SC 2.4.12 doesn't require any adjacent contrast but just a 2px solid focus indicator?

Yes, but since the thickness requirement already meets that bullet in the AA version, it's a nuance without a difference.

I.e. the AA version is:
> **Adjacent contrast**: The pixels in the minimum focus indicator area achieve at least a 3:1 against adjacent colors in the focused control or the minimum focus indicator area has a thickness of at least 2 CSS pixels.

Then at AAA:
> Minimum area: The focus indication area is greater than or equal to a 2 CSS pixel solid border around the control.

So the adjacent contrast is redundant, it is already covered by the other bullet.

If you would like to suggest some wording please do, it just doesn't seem like an issue per-se to me.

-Alastair
