### ISSUE TITLE
Are subtitles baked into a video a failure of 1.4.5: Images of Text?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1615]
Hope this is a simple one, but are subtitles baked into a video a failure of 1.4.5: Images of Text?

They are images of text, not adjustable, and can be offered as text.

**Comment by JAWS-test** [comment]
I don't think so, but the browsers must allow customizing the text properties (color, size etc.) according to [UAAG](https://www.w3.org/TR/2015/NOTE-UAAG20-20151215/#sc_116)

**Comment by bruce-usab** [comment]
> are subtitles baked into a video a failure of 1.4.5: Images of Text?

No, because if it was the intent for WCAG 2.0 to forbid open caption, it would be explicit on that point.

No, because the start condition of 1.4.5 <q>If the technologies being used can achieve the visual presentation</q> is not met.  Burned (open) captions is the technology being used, and a video-only stream is not a technology where (real) text can be used in lieu of images-of-text.


> The reason I ask is because the requirements for people as mentioned are not always possible for all technologies.

**Comment by jake-abma** [comment]
thx @bruce-usab the second does the trick, the first I was not sure about, Cheers!
