### ISSUE TITLE
Test #1 of H39 for table caption needs re-wording

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag#165]
The intent for Technique H39 (table caption) begins with " The objective of this technique is to programmatically associate captions for data tables where captions are provided in the presentation". 
Yet, the first test says:
"1. Check that the table includes a caption element."

This leads to the interpretation that all data tables need a caption  ... disregarding the "where captions are provided in the presentation. " 
So the test needs to be re-worded:
1. Check that the table includes a caption element where captions are provided in the presentation.

And although H39 and H73 (summary attribute) say that caption text should not be the same as summary text, there is no test in either technique to address that. Maybe there should be a test that checks for that. When both are identical, obviously one of them  (most likely the summary), is wrong. It may not  function as an effective summary to aid table comprehension / navigation. 
Thanks,
Sailesh

**Comment by DavidMacDonald** [comment]
Proposed response:
It is correct that Caption elements on tables are not necessary to meet WCAG. Therefore, we will adopt a variation of your wording for check 1.
"Where a caption is visually provided in the presentation, check that the table includes a caption element ."
It is not a failure of WCAG to have an identical Summary and Caption, although it is a best practice that they are different. We don't see a significant problem in the wild with this, and <summary> has been deprecated in HTML5, so we will not do further techniques on it.

**Comment by MikeElledge** [comment]
+1, with addition of "check that the table **code also** includes a caption element" for clarity.

**Comment by spanchang** [comment]
Mike,
The initial proposal already addresses  your concern:
"Check that the table includes a caption element where captions are
provided in the presentation".
I am not sure why  this is not accepted as is.

Besides about table summary:
How is  a table caption that is identical to the table summary
attribute not problematic?
Imagine for a moment, the summary  text is visible. Will the table
then ever pass UI design QA if the caption is the same as the summary?
Why should screen reader users be subjected to the same text  repeadedly?
Or is it the attibude: be thankful you have access to that content at
least once; do not complain if it is repeated?
Or is it a presumption that non-sighted users are nincompoop  and need
text repeated to them?
If the developer fixes it just once all screen reader users will
perpetually enjoy a good experience. No?
It is something that can be  detected by an automated testing tool and
not even require manual verification.
It is immaterial that the summary attribute  is not valid in HTML5:H73
is a valid technique. Does it  cause an SC 4.1.1 failure?
By the way, not using summary attribute   from HTML5 quality of code
point of view may be only a best practice from a code markup
perspective.
It is not an accessibility best practice.
Pointing to HTML5 is an inadequate response for  caption=summary issue
 in the initial representation dated March 01.
For an example of   table caption = summary see:
http://www.mindoversight.com/csun/example/Census_2013_summary.htm
And see the last link on that page for the same table with a useful summary.
And also imagine the same table with the useful summary text  being
repeated for the caption.

Description of an accessibility best practice:
list of 3 items
• Doing more than needed for fixing an accessibility barrier
• Enables exploiting a feature of AT / platform accessibility that
helps a PWD group
• Meeting a Level AAA SC when the goal is say, Level AA
from:
http://www.mindoversight.com/csun/2016/slide9-0.html

Request:
So when, "table summary  is identical to table caption", it may not be
a WCAG 2.0 failure but it is a misapplication of a techniique and
should be called out.
See:
http://www.mindoversight.com/csun/2016/slide17-0.html

Thanks and best regards,
Sailesh Panchang

**Comment by MikeElledge** [comment]
Oops! You're right Sailesh--I didn't notice that it said caption "element". Perhaps David can clarify why having identical Summary and Caption attributes is not a failure, but simply bad practice.

**Comment by DavidMacDonald** [comment]
I simply can't map it to a failure

**Comment by spanchang** [comment]
My message above advocates that it should be flagged as a "technique
misapplied" ... not a failure.
Ttechniques misapplied introduce  accessibility challenges very often
in content that is meant to be more accessible. So "Technique
Misapplied" should be a category in accessibility reports.
Sailesh

**Comment by spanchang** [comment]
Hello David,
Was the change as per your proposed response  taken up for implementation?
The wording in my proposal was simply  from the description part of the technique. But I am ok with the proposed response for the caption test.  
I did note you  remarked editing the test is the 'practical' thing to do and ten WG members accepted the proposal.
Thanks,
Sailesh

**Comment by goetsu** [comment]
Hi @DavidMacDonald  any news regarding update of the testing procedure of this technique

**Comment by awkawk** [comment]
I made a pull request (https://github.com/w3c/wcag/pull/604) to address this issue.

**Comment by awkawk** [comment]
@OlivierNourry I edited the pull request to change "visually provided" to "presented as I agree with your first comment.

Regarding the second part, I think that the intent of 1.3.1 Information and Relationships is to ensure that content that is presented doesn't rely on implicit relationship cues that work for some users and not for others. in the case of tables, it is fairly common for a table to have text that is adjacent to it that needs to be associated with that table explicitly, so this is a technique that people can use to demonstrate that they have met 1.3.1 with a table caption. There are other possible techniques, so this technique doesn't intend to cover all possibilities.

As far as a title attribute on a table, I think that would already pass 1.3.1 as there is an explicit programmatic relationship between the title attribute content and the table that it is attached to. This is hopefully widely regarded as a poor way to convey important information about a table, as it relies on users moving their mouse over the table in order to be aware that the content exists at all and to view that information. I would also be concerned about meeting the keyboard requirement with this approach. 

Overall, WCAG isn't specifically requiring a table caption for tables, but instead is requiring that when content is presented that is intended to provide a title for a table that the content's relationship to the table can be programmatically determined. Some tables aren't viewed as needing a caption by the author and not provided, and in that case WCAG doesn't require that text to be provided and also for that text to be programmatically associated with the table. If the author is incorrect and people find it confusing because a title is needed, all users are affected, not just those with disabilities.

**Comment by OlivierNourry** [comment]
Thanks for the update @awkawk.

Also, thanks for the clarification on the other points, very much needed, indeed!

**Comment by goetsu** [comment]
thanks @awkawk regarding your comment and update I have three more questions 

If you consider the case where an author provide a title to a data table but : 
* make it not visible on screen
* make readable with a screenreader

First question : Will you consider 1.3.1 as not applicable (because title not visible) or not compliant in such case ?

Second question : If you consider it not compliant, to be compliant will you require only that there is a relationship between the title and the table or will you ask to make it visible in addition to that ?

Third question : do we agree that using title attribute (or any other techniques to create relationship) will not be considered as compliant if this technique is not supported in screenreaders (at least for those author will consider as the minimum level of assistive technology support needed)

**Comment by awkawk** [comment]
First off, these answers reflect only my thinking and shouldn't be taken as the official opinion of the WG.

> First question : Will you consider 1.3.1 as not applicable (because title not visible) or not compliant in such case ?

Is the title in a caption element or just a preceding line of text? I think that if it was in a caption element and hidden visually that it would meet 1.3.1, if only because I don't know how it would fail 1.3.1, but since the title isn't really made available to users via presentation one might also argue that 1.3.1 is met because there is no presented title to make the relationships programmatically determinable for (e.g. Not applicable). I'd lean toward the latter - in general this feels like an edge case possibly created when an author thinks that the caption element is required but doesn't want to have one for users in general.

> Second question : If you consider it not compliant, to be compliant will you require only that there is a relationship between the title and the table or will you ask to make it visible in addition to that ?

By choosing the "not applicable" option I've cleverly avoided this! :)

> Third question : do we agree that using title attribute (or any other techniques to create relationship) will not be considered as compliant if this technique is not supported in screenreaders (at least for those author will consider as the minimum level of assistive technology support needed)

Based on Conformance Requirement 4, yes.

**Comment by awkawk** [comment]
> For a visually hidden paragraph or h2 with not associated with the table, will you have same answer to question 1 ;) If not back to question 2

Yes, I would have the same answer. If I published a web page with all text hidden visually but available to screen readers, I don't think that WCAG would have anything to say about it, assuming that most users would have complaints and that would hopefully take care of it.

**Comment by goetsu** [comment]
ok thanks it confirm my opinion is there any way to have official opinion of the working group for such cases ? (I will also have a few other cases for other SC in stock in the coming weeks)

**Comment by goetsu** [comment]
just to let you know I've made some AT support testing for different techniques (still edge to do) : https://codepen.io/goetsu/full/VgMEmV
