### ISSUE TITLE
If an action within a process is NOT required, is it a process at all?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#1685]
The definition of a Process is:

> process
> series of user actions where each action is required in order to complete an activity

Purely based on this text, can I say that if a process (in the way we probably mean it to be) contains actions NOT required / needed to complete an activity, it is not a process anymore in our definition?

Example: If in a multi step form the 'insertion' or 'second name' is asked, but not a required field, does this make the form NOT fit our definition, and thus NOT a process?

It is an action, one of 'each', but NOT required, so not fitting...

**Comment by detlevhfischer** [comment]
@jake-abma The common-sense answer would be that the availability of non-essential actions does not mean process stops to be process as defined, so that formulation may need a slight tweak. Seen in another way, any action that is not required (but possible) may be disregarded in terms in dealing with the process aspect (but of course not in terms of covering WCAG requirements generally).

**Comment by alastc** [comment]
Taking a typical process example of an ecommerce checkout:
- You must have at least one item in your basket to process (so that's required);
- You may add other items (not required);
- You must enter (or confirm) your address and payment details (required);
- You may add giftwrap (not required);
- You must select the final 'confirm' button to complete the process (required).

There can be actions that are not required, but there must be actions which are required.

**Comment by jake-abma** [comment]
@alastc exactly as you say: 

> There can be actions that are not required, but there must be actions which are required.

But the definition says:

> series of user actions **where each action** is required

So, that includes all action, also the one "that are not required

Or does the 'series' in this case is only talking about the 'required' ones (which is not clear)

Also (if so) the "series" suggest it's like a sequential set of actions of the 'required' kind, while in the 'serie' you might have multiple NOT required ones.

**Comment by alastc** [comment]
How about:
> series of user actions where some actions are required in order to complete an activity

Or even simpler:
> series of user actions which complete an activity

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
