### ISSUE TITLE
Visible Required label and 3.3.2: Labels or Instructions

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#1698]
Understanding Success Criterion 3.3.2: Labels or Instructions
https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html

Benefits - bullet point 2
_Providing clear and unambiguous labels and instructions (including clear identification of required fields) can prevent users from making incomplete or incorrect form submissions, which prevents users from having to navigate once more through a page/form in order to fix submission errors._

Is labelling only the optional fields rather than the required fields a fail of 3.3.2: Labels or Instructions? If so, does anyone have any user data to back this up.

I believe it is non-compliant, however, need to get information on why.

**Comment by JAWS-test** [comment]
Understanding Examples: 

> In a form which contains both required and optional fields, the required fields and/**or the optional fields** are clearly labeled as such. 

Thus, it is not a violation if only the optional fields are marked. However, it is more common to mark the required fields

**Comment by LaurenceRLewis** [comment]
Thanks @JAWS-test I missed that in the understanding doc.

**Comment by LaurenceRLewis** [comment]
@JAWS-test I can’t find that paragraph in the understanding document. Can you provide the link to it please.

**Comment by JAWS-test** [comment]
https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html#examples

**Comment by goetsu** [comment]
@detlevhfischer @patrickhlauke to be clear can you confirm working group position on these specific cases : 

- If all fields are required (like a login / password field) 
-- without any visually information that all fields are mandatory
-- without any required or aria-required attributs on the fields 
- If all fields are required (like a login / password field) 
-- without any visually information that all fields are mandatory 
-- with a required or aria-required attributs on the fields

**Comment by goetsu** [comment]
@patrickhlauke thanks for your personal pragmatic opinion that I share ;) 
I think that the understanding text of the SC or at least the text of the [H90 technique](https://www.w3.org/WAI/WCAG21/Techniques/html/H90) will gain to be made more clear on such case with a note in the description for example like "When all fields inside a form a required event if it's a good pratice there is no formal requirement for them to have a visual  indication that they are required before the user submit the form"

**Comment by bruce-usab** [comment]
@goetsu &mdash; I think it is fair to characterize similar WG discussions to focusing on the exact phrasing of the SC.  So I agree with @patrickhlauke analysis.

With regard to suggestions for the Understanding, please be encouraged to submit a PR with your proposed edit, as that is concrete way to get feedback (pro or con).  That said, historically it seems to me, there is a reluctance to have Understanding documents highlight minimally conforming examples which are not good patterns to model.  From that perspective, the detail that <q>there is no formal requirement</q> is something I would suggest trying to soften.  So perhaps:
> Even when all fields inside a form are required, it is a good practice to have a visual indication that they are required before the user submits the form.

**Comment by goetsu** [comment]
thanks @bruce-usab my question was also to know where it's best to make the change in the understanding of the SC or in the description of H90 technique or both ?

**Comment by bruce-usab** [comment]
I suggest H90 over Understanding for 3.3.2.  I see that I used <q>Understanding</q> too broadly with comment above.  Thank you for your interest!

**Comment by rvantonisse** [comment]
Hello,

I am looking for a fixed answer for this particular, asterisk as required field indicator but not explained, case and what have been mentioned by @mraccess77 :

> If you use an asterisk - you have to indicate what it means.

This asterisk (*) thing, that is being used often to indicate required fields, keeps popping up once a while. However, I dont seem to be able to find or save a clear resolution on this topic. A few days ago, discussion around the asterisk popped up again (https://github.com/WCAG-Audit-Discussions/NL-BE/issues/40 - Dutch) and issuer also posted this in the A11y slack #wcag channel.

My opinion on this matter is that the asterisk is beeing used as non-text content, like a symbol of sorts. And therefore should have a text alternative as is required for success criterion 1.1.1 Non-text content. But what this question keeps unanswered are arguments like "It sucks for everyone, thus it is not an (WCAG) accessibility issue..." (this seems to me it is a 100% accessibility issue) or more literall "an asterisk is a text character so it does not need a text alternative" (the asterisk, text, is used as visual indicator, [non-text content](https://www.w3.org/TR/WCAG21/#dfn-non-text-content) or at least not [human language](https://www.w3.org/TR/WCAG21/#dfn-human-language-s)).

What I currently accept as text alternative for a required field indicated with an asterisk is either:
- The asterisk visually explained before (H90) or directly after the form
- The asterisk explained as error message after submission, either or both at the field or before/after the form as visual message. (This still is a UX issue but at least accessible)

Otherwise my resolution would be to fail this case under [success criterion 1.1.1 non-text content](https://www.w3.org/TR/WCAG21/#non-text-content).

This issue is also relevant and beeing referred to: https://github.com/w3c/wcag/issues/2357, I couldn't read a clear consensus there either.

I have looked at WCAG conformance, related success criteria (1.1.1, 3.3.2) and glossary normative sections a few times (and more). The technique H90 is the only place I could find that exactly shows an [example (2)](https://www.w3.org/WAI/WCAG21/Techniques/html/H90#example-2-using-an-asterisk-to-indicate-required-state) of how to use an asterisk for required field indication, but this is informative and missing reasoning for why:

> It is important that the asterisk meaning is defined at the start of the form.

I am looking for a normative way of consensus, but I need help or direction to get there.

**Comment by scottaohara** [comment]
I also think some clarity is needed for this example - because I tend to disagree that it is always necessary to inform people that an very common visual marker - used quite consistently across the web - needs to be constantly prefaced with what it means.  Particularly in regards to modern web apps where people are often needing to input interact with required fields across various pages/screens of the app.  We don't require that people provide a legend for other common form icons, such as warning symbols for errors or checkmarks for valid input.  Asterisks to indicate the required nature of a field is similar to those at this point.

Per the [referenced example 2](https://www.w3.org/WAI/WCAG21/Techniques/html/H90#example-2-using-an-asterisk-to-indicate-required-state) - I would expect this to be qualified with "because the `<input>` in the following code snippet does not use the `aria-required=true` or `required` attribute, and instead relies solely upon the asterisk in the label to indicate that the field is required, the meaning of the asterisk needs to be provided".

However, if the form field were to use either `aria-required=true` or `required`, then I submit it is not necessary to tell people this, as the form field itself will programmatically expose it is required, and the asterisk is now a visual representation of the field's programmatic required state.

**Comment by GreggVan** [comment]
I worry when we say that we don’t have to do something because it is common across the web and everybody knows about it.   If you mean everybody who is already Web savvy — I agree.  But there are many new comers  (and even OLD newcomers) and using these conventions without explanation really falls into the category of jargon — and we speak specifically about not using jargon without explaining it.

So no - I don’t think we should every assume that "people already know what that means" unless we don’t intend to include newcomers (and some people with cognitive, language, and learning disabilities.)

NOW - how do we mark things up so that it will pop out to newcomers and others who need it — but not clutter up the page for everyone else.    THAT is the question. Aria markup won’t solve that because newcomers  (and others who need it) probably won’t know what that is or have tools that will show it. 

hmmmmm


Gregg Vanderheiden
***@***.***

**Comment by patrickhlauke** [comment]
at what point do you make it mandatory though for all sites to be "newcomer friendly"? is that the purpose of WCAG? 3.3.2 is single A, so are you saying no site is ever allowed to use something like an asterisk, or explicitly saying "(required)" even in obvious cases (like a login form with username/password ... it's self-evident that both are required, otherwise what kind of login form would it be) without explaining what it means?

**Comment by GreggVan** [comment]
Asterisks are not a Web Thing

They have been around for 50 years —  but they are always accompanied by a footnote or legend that says what they mean.   

Note that I also said  (and others)  next to newcomers.  There are disabilities that also will not know some of the things that the rest of us notice or know. 

You will also note that I didnt say that I had the answer.   Just that I was not comfortable saying we should just accept things as ok just because those of us who are webbies know that it means

best

g

**Comment by scottaohara** [comment]
@GreggVan well, i never said "everybody knows about it", so I just want to be absolutely clear on that, as you're responding to me as if I had.

I said:
> I tend to disagree that it is always necessary to inform people that an very common visual marker - used quite consistently across the web

emphasis on "always necessary" - which leaves room for situations where it may be necessary, but allows for people to not have to remind someone perpetually what a common visual indicator means when they will be encountering it several times.

**Comment by bruce-usab** [comment]
@rvantonisse 

> I am looking for a normative way of consensus, but I need help or direction to get there.

For <q>normative</q> look to exact phrasing of the SC.  Do we have an SC that states required fields must be marked as being required?  If not, the question is in the realm of best practices, and might documented in a Technique or Understanding document.

The other question to ask:  Is this something which disproportionately impacts people with disabilities?

If so, then the something is a good candidate for the informative documents (if that something is not already a normative SC).

Assuming <q>everyone knows * means required</q> does impact PWD.  It is worth mentioning as a best practice to have that explicitly, at least on longer forms.  @patrickhlauke counterexample of ID/password exemplifies why asterisk on required fields is not universal, and it should not be.
