### ISSUE TITLE
WCAG 2.2 - 3.2.7 Visible Controls (AA)  - difficult to understand meaning

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#1840]
**3.2.7 Visible Controls (AA)**
Where receiving pointer hover or keyboard focus triggers user interface components to be visible, information needed to identify that user interface components are available is visible, except when:

It is hard to understand the meaning of the SC therefore this may require rewording for clarity

Suggestion:

**3.2.7 Visible Controls (AA)**
When receiving pointer hover or keyboard focus triggers a visible user interface component, information needed to identify that user interface component is available, except when:

Changing components to component to align with the description of **user interface component**
_'A part of the content that is perceived by users as a single control for a distinct function.'_

**Comment by yatil** [comment]
I agree that the wording is super convoluted, but I also think that your suggestion describes something else. The original says that user interface components become visible, yours says that visible user interface components are triggered.

I would like to suggest another wording, but I honestly don’t understand the SC at all. Does it want a persistent control that is available? The [understanding examples](https://www.w3.org/WAI/WCAG22/Understanding/visible-controls.html) hint at that, but it is very unclear to me.

The exceptions make this even less easy to understand. Provide visible identification unless persistent visible indication is available? 

I don’t see how this is enforceable or testable.

I also think the name is misleading, as it is about invisible controls that become visible…

What about:

> **3.2.7 Invisible User Interface Components**
> When user interface components are invisible and their functionality is only available after they become visible on hover or focus, provide a visible indicator that functionality is available on hover or focus. Alternatively, provide an option to persistently display the invisible user interface components. 
> Exception: Hiding the component is essential.

I think this wording covers exception 1 (“functionality is only available … on hover or focus”), exception 3 (“Alternatively, provide an option to persistently display the invisible user interface components.”) and exception 4. 

I did not include exception 2 (“The component is provided specifically to enhance the experience for keyboard navigation;”) because it feels untestable. Who decides what is specifically to enhance keyboard navigation? How does that relate with elements that are displayed on hover? This exception also seems to indicate that only screen reader users use keyboards, so having a visible indicator is not as important, which I personally not agree with.

(Sorry for the rambly comment, but I think it’s important to lay out my thought process.)

**Comment by LaurenceRLewis** [comment]
The original says that user interface components become visible…

Reading the original text this is completely unclear, hence the misunderstanding 😀

**Comment by mraccess77** [comment]
The visible identification could be some sort of indicator that more controls are present but not the visually hidden controls themselves.   

Suggested wording:
Where receiving pointer hover or keyboard focus triggers additional user interface components to become visible, one of the following is true:
* a visible indicator that trigger functionality for additional user interface components is available
* an option to persistently display the additional user interface components is available
* the trigger of additional user interface components to become visible is essential functionality

**Comment by LaurenceRLewis** [comment]
@mraccess77  Suggested wording:
Where receiving pointer hover or keyboard focus triggers additional user interface components to become visible, one of the following is true:

That makes more sense.
