### ISSUE TITLE
2.4.13: Is EPUB Web Content?

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1869]
Although the phrase 'content (web content)' exists in the [WCAG glossary](https://www.w3.org/TR/WCAG21/#dfn-content), a link to the definition has not been provided and it unclear whether this definition applies to this SC. We are wondering whether EPUB would be classified as web content or not.

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by alastc** [comment]
In general yes, it can be content available at a URL. 

The note at the bottom of the intent is really key to understanding this, because whilst all web content is in scope, user-agents for PDF & EPUB will generally fulfil the requirement. 

It is HTML versions (e.g. Kindle books read in the browser) that require the navigation mechanism.

**Comment by DavidMacDonald** [comment]
Agree with @alastc 's response. We could provide that.
