### ISSUE TITLE
2.5.8: Minimum Component Size

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1870]
As discussed in #1848, this success criteria does not discourage the use of targets that are too small to be activated for users with motor-skill disabilities.  As this SC has been renamed Target Size (Minimum), it feels prudent that a value for a minimum target size is provided for targets offset by at least 24 CSS pixels.

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by DavidMacDonald** [comment]
This SC has gone through many iterations over the course of WCAG 2.1 and 2.2 and is currently a careful balance of many factors. Requirements that involve a change to the look and feel of a site sometimes require compromises. We feel that in this situation, that any size of target provided in the exception for target offset would fall under the domain of usability. Because targets that are smaller that 24 px are going to affect all users. 

I doubt we could get consensus on any minimum target size less than 24 px in the case of the offset exception and naming a number in that bullet might be confusing.
Do we want to discuss this in the group?

**Comment by jenstrickland** [comment]
Draft proposed response:
<hr>

SC 2.5.8 Target Size (Minimum) (Level AA) is a partner to SC 2.5.5 Target Size (Level AAA).

Regarding the size of 44 x 44: 

- The minimum target size to meet Level AA is 24x24 pixels and includes a target offset of at least 24 pixels, with noted exceptions. There are some interfaces where smaller sizes are appropriate and necessary, for example the toolbars at the top of certain editing interfaces. However, this SC should encourage the move towards larger target sizes and offset spacing in redesign efforts, as appropriate. 

- This SC 2.5.8 includes the range of pointer possibilities, from mouse to touch, with the mobility needs as a consideration. 

- The SC 2.5.5 Target Size (Level AAA) may be perceived as an enhancement increasing target size to 44x44 pixels where that is appropriate to the interface.

**Comment by alastc** [comment]
The group agreed with the response today.
