### ISSUE TITLE
2.5.8: Name Change

### ISSUE THREAD

**Issue by benja11y** [w3c/wcag#1871]
With the current wording, our internal discussions have centered around the spacing exception.  

As interactive controls can easily be given at least 24 CSS pixels of surrounding space due to the amount of height and width available to modern viewports, we feel that the original name of Pointer Target Spacing is more appropriate to our foreseen implications of this SC mentioned in #1870.

This issue has been raised on behalf of [TPGi](https://www.tpgi.com), based on an internal consultation process. [An article containing all of our comments](https://www.tpgi.com/wcag-22-working-draft-feedback/) can be found on our blog, along with an introduction and acknowledgments.

**Comment by DavidMacDonald** [comment]
SUGGESTED RESPONSE:

The SC scope includes the size of the target AND any spacing. This SC has gone through many iterations over the course of 2.1 and 2.2 and is currently a careful balance of many factors. The short handle for an SC is not really its "name". I of the SC number and text wi[hich together form the SC's "name". The short handle is there for quick identification. Originally these handles were added to WCAG 2.0 on the request of the cognitive community who were looking for quick memory aids for the SC numbers and text.

Regarding the wording of this short handle. We want to discourage authors from relying spacing instead of target size for this SC because a larger target is more useful to users than a smaller target with spacing. Therefore, we believe the current short handle is  more appropriate. The main text of the SC is about target size and an exception bullet is there for spacing.

**Comment by jenstrickland** [comment]
Draft proposed response:
<hr>

SC 2.5.8 Target Size (Minimum) (Level AA) is a partner to SC 2.5.5 Target Size (Level AAA).

Regarding the size of 44 x 44: 

- The minimum target size to meet Level AA is 24x24 pixels and includes a target offset of at least 24 pixels, with noted exceptions. There are some interfaces where smaller sizes are appropriate and necessary, for example the toolbars at the top of certain editing interfaces. However, this SC should encourage the move towards larger target sizes and offset spacing in redesign efforts, as appropriate. 

- This SC 2.5.8 includes the range of pointer possibilities, from mouse to touch, with the mobility needs as a consideration. 

- The SC 2.5.5 Target Size (Level AAA) may be perceived as an enhancement increasing target size to 44x44 pixels where that is appropriate to the interface.

**Comment by alastc** [comment]
The group approved the response above.
