### ISSUE TITLE
3.3.7: Accessible Authentication - is it acceptable to only support niche, propriety, OS specific, and potentially inaccessible methods?

### ISSUE THREAD

**Issue by wardav** [w3c/wcag#1899]
Reading through the latest draft, my understanding of 3.3.7 is that the success criterion passes so long as it is **theoretically possible for a theoretical user to authenticate themselves without a cognitive test.** 

There are some questions. For example:

* What if this involves needing to use a very specific device, e.g. the latest Android phone with a specific version of a fingerprint recognition.
* Buy some propriety device that can only be used with the specific website. That is, not some open standard, WebAuth, etc., but an ACME CORP login key that costs thousands.
* Some facial recognition software that relies on using "active gaze" which may be inaccessible to some user groups

My understanding is that none of this is in scope. 

The requirement is that it is simply that users can get through the end-to-end process without a cognitive test, even if process involves a disproportionate burden compared to the cognitive test route.

**Comment by alastc** [comment]
> What if this involves needing to use a very specific device

I'm not sure how you would achieve that for web content? WebAuthN is a standard so that browsers know how to access the on-device biometrics. 
If you did manage to do so, you'd have a very, VERY specific "list of the Web content technologies relied upon" in your conformance claim, which isn't really an approach supported by regulators.

> Some facial recognition software that relies on using "active gaze" which may be inaccessible to some user groups

As a user, you will need your primary login mechanism to work. In that scenario, you would probably fall back to using the on-device pin code/password (or get a device with a finger print reader instead). The point is that the device has a method of authenticating, and the website is off-loading the authentication to the device.

> My understanding is that none of this is in scope.

There are some specific requirements in [accessibility supported](https://www.w3.org/TR/WCAG22/#dfn-accessibility-supported) that are generally interpreted to mean you need reasonably wide usage of a technology you are relying on.

**Comment by alastc** [comment]
Proposed response:

<hr>

In practice, the new SC would mean that a conforming site will need to make it **practically** possible for a user to authenticate themselves without a cognitive test.

In theory a site could claim conformance with just a niche device/setup allowing for authentication, but it would not fit the generally accepted use of "accessibility supported".

Also, no **website** can implement facial recognition, they would have to use a mechanism to access the on-device authentication, which is customisable by the user.

**Comment by mraccess77** [comment]
This seems related to accessibility supported use in the conformance requirements section of WCAG.

**Comment by alastc** [comment]
Response above was accepted by the group.
