### ISSUE TITLE
Broken link(s)

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag#1983]
From https://www.w3.org/WAI/WCAG21/Techniques/general/G88#test-rules

Link: see _Understanding Test Rules for WCAG Success Criteria_.

goes to: https://www.w3.org/WAI/WCAG21/Understanding/understanding/understanding-act-rules.html

404

**Comment by fstrr** [comment]
@michael-n-cooper I think this bug is in the [generate-techniques.xslt file](https://github.com/w3c/wcag/blob/f57d623f421f698e01c517053bc071d15d3b897a/xslt/generate-techniques.xslt) as I can't find that section of content in [G88](https://www.w3.org/WAI/WCAG21/Techniques/general/G88). The link should go to this [Understanding Test Rules for WCAG Success Criteria](https://www.w3.org/WAI/WCAG21/Understanding/understanding-act-rules) page, but the link has an extra /understanding/ in the URL.
