### ISSUE TITLE
H40 Consider new description of `dl`

### ISSUE THREAD

**Issue by momdo** [w3c/wcag#207]
https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H40.html

HTML4 defined dl element as *definition* lists, but current HTML 5.1 defines that the dl element represents a *description* list of zero or more term-description groups.

furthermore, I feel that we need to update following links to resources section:
https://www.w3.org/TR/html51/grouping-content.html#the-dl-element
https://www.w3.org/TR/html51/grouping-content.html#the-dt-element
https://www.w3.org/TR/html51/grouping-content.html#the-dd-element

**Comment by awkawk** [comment]
This is more complicated since the technique needs a full re-write of the description.

**Comment by awkawk** [comment]
@adamsolomon We need this ASAP.  Can you get this done in the next day?

**Comment by adamsolomon** [comment]
can be ready by nightfall - meaning earl y monday afternoon new york time

**Comment by adamsolomon** [comment]
Here are my suggested changes:
to h40 (https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160719/H40.html):

(Title) Using description lists (instead of "Using definition lists")

(Description) The objective of this technique is to provide the description of names or terms by presenting them in a description list. The list is marked up using the dl element. Within the list, each term is put in a separate dt element, and its definition is provided in the dd element directly following it. Multiple terms can be asscoiated with as single description, as can a single term be associated with multiple descriptions, provided that a semantic order is maintained. The title attribute can be used on the containing dl element to provide additional information about the description list. Usage of description lists ensures that terms and their descriptions are semantically related even as presentation format changes, as well as insuring that these terms and descriptions are sematically grouped as a unit.
Description lists are easiest to use when the descriptions are put in alphabetical order. A common use for description lists would be a glossary.
(instead of 
"The objective of this technique is to provide the definitions of words or phrases by presenting them in a definition list. The list is marked up using the dl element. Within the list, each term is put in a separate dt element, and its definition goes in the dd element directly following it. The title attribute can be used to provide additional information about the definition list.
Using dl, dt, and dd ensures that relationships between terms and their definitions are preserved if the presentation format changes and that the list of terms and definitions is treated as a unit.
Definition lists are easiest to use when the definitions are put in alphabetical order. Definition lists are typically used in a glossary".)

(Example 1) A list of descriptions of nautical terms used on a Website about sailing.
(instead of "A list of definitions of nautical terms used on a Website about sailing".)

(Procedure) For any set of terms and their associated descriptions:

Check that the list is contained within a dl element.
Check that each term described in the list is contained within a dt element.
Check that the description for each term appears in the dd element immediately following the term's dt element .

(instead of "For any set of words and their definitions that have the appearance of a list:

Check that the list is contained within a dl element.
Check that each word defined in the list is contained within a dt element.
Check that the definition for each word appears in the dd element immediately following the word's dt element".)

(To WG: Perhaps we need to update g62 as well. Regarding the other links suggested for update by the commenter, i didn't see any place for updates there. They seem to be in line with html5 specs.)

**Comment by alastc** [comment]
I think the other links were for the resources section of H40, which currently links to HTML4.0 spec of DL.

**Comment by awkawk** [comment]
Proposed response:
Thank you for your comment.  We are implementing the changes you suggest: https://github.com/w3c/wcag/pull/235/files?diff=split

**Comment by awkawk** [comment]
Proposed response accepted by WG and changes implemented.
