### ISSUE TITLE
Does textual information on focus/hover meet visual alternative for SC 1.4.11

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#2157]
Take the following example:
A chart exists where you have to focus/hover each trigger in a chart in order to display the text for the bar because the bar itself does not meet SC 1.4.11.  However, the trigger does meet the contrast minimum and text equivalent is displayed visually and the text meets contrast requirements.  Does this conform to SC 1.4.11?  

I assume that a visible data table that is available via a link or disclosure does meet the SC - but in the example above no data table is available visually.

**Comment by JAWS-test** [comment]
I think the Understanding say YES: https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#dynamic-examples

**Comment by mraccess77** [comment]
That's how I read it - but others seemed to say no on another thread.

**Comment by patrickhlauke** [comment]
> That's how I read it - but others seemed to say no on another thread.

the other thread was a different situation (which is why these things can't be easily generalised). The gist of the other thread was emoji that themselves don't have sufficient non-text contrast. As they would be the "triggers" for tooltip that clarifies (in a sufficiently contrasty way) what they are, this would not be sufficient, because if the user can't see/discern the actual *trigger*, then they would potentially not even know that they *can* hover/focus on them to get the sufficiently visible alternative/addition.

**Comment by alastc** [comment]
The idea behind the example from the understanding doc is that you can use dynamic features to make the (conforming) content available. There should be enough to distingiush the chart is there, but not having to distinguish individual elements/data within it.

I suppose you could apply the same logic to emoji, so long as there are some distinguishing features to discern there is an icon, you could then pass with hover (and focusable) text popping up. Although that then triggers content-on-hover-or-focus...

**Comment by JAWS-test** [comment]
I don't like the example in Understanding, by the way, because it means that a person who can't see low contrast distances well has to move over all the diagram parts to be able to perceive its values. Perceiving the complete diagram is not possible. In addition, this means a high additional effort in operation. But probably it is too late to change this...

**Comment by alastc** [comment]
It was also necessary for this SC to be accepted.
