### ISSUE TITLE
WCAG 3.0 Draft Review Suggestions on Guidelines

### ISSUE THREAD

**Issue by PoornimaSubramanian** [w3c/wcag#2195]
@rachaelbradley , @shawna-slh , @michael-n-cooper , @jspellman,

Hello WCAG Team, 

I am a Digital Accessibility SME in Holland America Group. I had an opportunity reviewing the draft version of WCAG 3.0 and proposing few suggestions based on my knowledge. Please see my suggestions documented in the attached PDF file. 

Feel free to let me know for any questions via email [psubramanian@hagroup.com](url) 

**Note:** I also submitted an [application to join the WCAG working group ] (https://www.w3.org/groups/wg/ag/invited-experts/3371) for the individual invited expert, can you please review and let me know for the opportunity?

[WCAG_3.0_Draft-Review-Comments_PoornimaSubramanian.pdf](https://github.com/w3c/wcag/files/7922389/WCAG_3.0_Draft-Review-Comments_PoornimaSubramanian.pdf)

**Comment by bruce-usab** [comment]
Thank you @PoornimaSubramanian for these, and for submitting via GitHub.  It is more work for you, but if you are willing, I think it would be helpful if you post your suggestions as individual issues.  Your PDF is not so long, so I think that might just be 7 new issues (one per table row).  Or maybe its 5 new issues (one per guideline).

As a generally rule, we take comments in whatever format is convenient to the person posting, and that includes email attachments.  But it seems to me that one of the more time-consuming steps is chucking free-form documents into correctly-sized bites.  Somebody has to do that labor, and since you are clearly comfortable with GitHub, I will take the liberty to ask, are willing to do that step with your comments?

Thanks very much!

**Comment by PoornimaSubramanian** [comment]
Hello @bruce-usab , Absolutely! I'll post my suggestions on each guideline as individual issues. 

Thank you

**Comment by PoornimaSubramanian** [comment]
Hello, I submitted my suggestions on the WCAG 3.0 draft guidelines as individual issues listed below - so, closing this issue. 

[https://github.com/w3c/wcag/issues/2196 ](url)
[https://github.com/w3c/wcag/issues/2197 ](url)
[https://github.com/w3c/wcag/issues/2198](url)
[https://github.com/w3c/wcag/issues/2199](url)

Thank you!

**Comment by bruce-usab** [comment]
Thank you @PoornimaSubramanian !
