### ISSUE TITLE
Focus Appearance and what counts as the "real" size of an element/component

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#2226]
Splitting this off from https://github.com/w3c/wcag/issues/2222#issuecomment-1035099989, based on @alastc's answer to my question https://github.com/w3c/wcag/issues/2222#issuecomment-1036230167

I would strongly urge to reconsider just focusing on the element's raw CSS dimensions, but rather what their apparent dimensions are.

See the expanded example here https://codepen.io/patrickhlauke/pen/xxPdQOd - it makes no sense that one would fail, while the other one would pass, and all that simply because of how they're coded when visually they're exactly the same. there's a risk here that we create another SC that we then have to preface to clients with "yes, it's not logical, and i really can't explain its actual real-world practical benefit...but it is what it is and you have to follow the wording of the SC even if it makes no sense"

**Comment by patrickhlauke** [comment]
In my mind, the SC should focus on what the apparent/perceived perimeter/size of the control is, and not rummage around in the underlying markup/CSS to determine what the actual element's sizing is. you're opening up a pandora's box if you start to then also take into account things like clipping paths, and SVG shapes, etc, which will simply lead to instances of "it normatively fails, but only because of the way you built this control behind the scenes, and even though the way you built it is perfectly valid"

**Comment by JAWS-test** [comment]
I agree with you, but I think we should clarify what is the perimeter of an object that has no frame. For example, a link that consists only of text. Is the perimeter 
* then the irregular shape of the letters
* the smallest rectangle in which all the letters fit in
* the size of the click area
* the size of the focus frame
* something else

**Comment by JAWS-test** [comment]
I think the simplest thing would be to always take the visual size of the element as the scale, regardless of click area or other invisible sizes of the element. And then it would be best that, for irregular objects, the smallest rectangle that can be placed around the visible object (and is not rotated) is used to determine the size. Everything else can become very complex: Of course, with a circle I can take the circumference of the circle, but what about a link that consists of many letters, or just one letter, or a font icon: do I then have to take the circumference as well? Calculating this quickly becomes too much complex (Latin letters are already difficult, but what about Chinese calligraphy?). To be able to test the criterion sensibly, I would suggest drawing a rectangle around the visible object.
At most, the question would be where a visible object begins if the border of the object itself consists of a colour gradient, such as a shadow. I would suggest that all visible pixels, regardless of contrast, should then be taken into account.

**Comment by patrickhlauke** [comment]
> I would suggest that all visible pixels, regardless of contrast, should then be taken into account.

that would not work, as if for instance you had a clearly defined button, but a very large smudged drop shadow or glow behind it, by your definition the latter would also have to be taken into account.

unfortunately, i don't think there's a simple/easy way to define this. yes, for complex shapes, it will get complex. but it's a complex SC, no way around it. any simplification ("for this exercise, we'll assume that the cow is spherical...") will invariably lead to false positives/negatives

**Comment by patrickhlauke** [comment]
> It goes both ways though, if you expand the clickable area with JavaScript then you'll get odd pass/fails if it is based on visuals

why would you? focus indication for keyboard users is unaffected by how large the actual mouse/touch clickable/tappable area is, no?

**Comment by patrickhlauke** [comment]
perhaps the SC needs to aknowledge that there is still a level of subjectivity and human judgement required to determine what the actual "element" is that would reasonably be considered by a sighted keyboard user to be the control/element that receives focus. (and incidentally, this in my view is why it's so dangerous/difficult to try and define unambiguous SCs that deal with design/visual aspects, as there can be some many different approaches, styles, variations to begin with, and *then* there are a myriad of different ways to actually implement those visual ideas - using plain HTML/CSS, using SVG, clipping paths, overlaid transparent images with cut-outs, etc etc)

**Comment by scottaohara** [comment]
i share patrick's concerns here.  Reviewing the demos and seeing things like "Passes 'component'; fails 'visual'."   I am not sure what that even means.... or why it matters so long as there is still a clear visual indicator of focus.

I honestly have no idea if the following examples 'fail' this SC as written. 

Radio buttons presented as "cards" but which require additional explainer content and might even have other interactive elements in those explainers.
https://codepen.io/scottohara/details/yLzYLdW

A heading which contains a disclosure widget where the left portion is a button, then there are other 'quick' pieces of data, and then the right side has a CSS chevron that is 'clickable' - as it is technically part of the button, but it is positioned at the end of the heading... so is not included in the focus outline 
https://codepen.io/scottohara/pen/yLoeYpV

Visually hidden checkboxes to allow for entire table rows to be 'selected'.  The focus outline for the 'row' needs to be inset otherwise it would either be cut off, or awkwardly be positioned within other siblign rows
https://codepen.io/scottohara/pen/gOWerPr

**Comment by alastc** [comment]
> why would you? focus indication for keyboard users is unaffected by how large the actual mouse/touch clickable/tappable area is, no?

Sure, but look at the card example in the [test page](https://codepen.io/alastc/pen/eYGoKyP). The link is the interactive element, but CSS is used to both increase the hit area and (not always aligned) it also puts the focus indicator around the card instead of the link inside.

I'm not arguing that pointer use should be included, but we have discussed various ways of defining the size of the keyboard operable item, including:

- User Interface Component
- Target size
- Visual size
- Element size

The other nuance is that the "user interface component" doesn't always mean what is focused. E.g. for things with aria-active descendant, where the user thinks the keyboard focus is located is within the _component_.

Target size is problematic because increasing the hit area for pointer usage then requires a larger focus indicator which sets up a negative incentive for designers.

Visual size is problematic because decorative things around the control count towards it's size. Also, I think it's hard to determine what the size of some controls is (such as the card example).

The size of the element is problematic in that it requires a method of determining what it is.

> Reviewing the demos and seeing things like "Passes 'component'; fails 'visual'." I am not sure what that even means.... 

Sorry, the demo was a quick thing to show the differences between using the visual size and the element size. The question is: If you had a contrasting 1px thick indicator, would it fulfil the size metric?

> or why it matters so long as there is still a clear visual indicator of focus.

The problem comes when you define 'clear'.  We're starting from a 1px outline of the 'thing', so you have to know the size of the thing to know if it passes.

> Radio buttons presented as "cards"

The thick border/outline on the radio buttons is more than enough. If you take an 'element' approach the border is around the input. I'm not sure what you would measure from taking a visual approach, but if you took it as the circle inside, then the outer focus indicator would be more than enough.

> A heading which contains a disclosure widget

A 1px black outline passes around the button (the grey border is light enough to contrast with the black for adjacent contrast), and for the link.

> Visually hidden checkboxes to allow for entire table rows to be 'selected'. 

An interesting case, if I'm scanning the output correctly the hidden inputs being selected don't have focus as such, but the rows do? 

So sticking with the rows, the focus isn't great in terms of contrast, but from a size point of view I think it's ok. (Are the links supposed to be separate?)

In the vast majority of cases each method above would produce the same result. In order to implement it, we need to pick a method and accept a set of "odd" results.

**Comment by patrickhlauke** [comment]
> Sure, but look at the card example in the [test page](https://codepen.io/alastc/pen/eYGoKyP). The link is the interactive element, but CSS is used to both increase the hit area and (not always aligned) it also puts the focus indicator around the card instead of the link inside.

For a keyboard user, i'd posit that they'd expect the small link to be the focusable element when first seeing this. When they then tab to it, the card as a whole appears to receive focus. The user then realises that the whole card is treated by the page (author) as a component. And for that, the focus indicator should be around the whole card, which it is, so for an auditor, it's a case of evaluating it like that.

In the second example, the keyboard user will see that the element that gets focused is in fact the link in the card. Cool. and it has a corresponding focus indicator. for an auditor, they assess that focus indicator.

So it will depend on the experience itself, rather than trying to preempt what it should be when first seeing it / without interacting with it?

> Target size is problematic because increasing the hit area for pointer usage then requires a larger focus indicator which sets up a negative incentive for designers.
>
> Visual size is problematic because decorative things around the control count towards it's size. Also, I think it's hard to determine what the size of some controls is (such as the card example).

so it seems that the SC is at an impasse...after trying to more specifically define what "visible" means (vis-a-vis the handwaving in 2.4.7), it defined reasonably clear rules anchored on the component/element, but now it has trouble defining what this anchoring component/element actually is?

it may well be that the SC has to accept that "it depends", and that in some cases it may be subjective or require some nuance on what gets evaluated (with extensive examples in the understanding, similar to what had to be done for 1.4.11) ? because otherwise, if we flip a coin and say it should be one or the other, we'll end up with illogical situations and an SC that seems rather arbitrary, or lead to false positives/negatives either way.

**Comment by alastc** [comment]
> So it will depend on the experience itself, rather than trying to preempt what it should be when first seeing it / without interacting with it?

I'd _like_ that approach, but it's a self-referential definition, I'm not sure how to word that.

I guess another approach would be to set the minimum size as the content of the component. E.g. the text in a link/button, or an icon. (i.e. bounding box approach).

That would have a smaller area than the default in many cases, but then I guess it's easy to tell it passes?

**Comment by patrickhlauke** [comment]
will still end up with vagueness. imagine a checkbox and label text next to it. the checkbox is clearly the "thing" that should have focus. what if both are now wrapped in a border, and look almost like a giant button that contains a checkbox? now it's less clear...does it fail in that case if only the checkbox itself shows a focus outline?

**Comment by guyhickling** [comment]
All the examples offered in this discussion so far are all contrived examples done for purposes of discussion. Does anyone have real examples of websites out in the wild where developers have deliberately changed the keyboard focus outline to take it off the HTML button, or other interactive element, and make it smaller? And if so, is it a common practice on websites generally? Maybe this is not a big issue anyway?

**Comment by alastc** [comment]
> imagine a checkbox and label text next to it. the checkbox is clearly the "thing" that should have focus. what if both are now wrapped in a border, and look almost like a giant button that contains a checkbox? 

If (according to the SC) the checkbox is the thing, and the author decided to outline the input & label, that's their prerogative and it easily passes the size metric. If the SC had defined it by target size and the developer put the outline around the checkbox, that would have become one of the 'odd results' I was talking about.

If the scope was to the content of the keyboard-operable user-interface control, then I'd argue the checkbox is the thing, the label expands the hit area but is not part of the UIC.

> Does anyone have real examples of websites out in the wild where developers have deliberately changed the keyboard focus outline to take it off the HTML button, or other interactive element, and make it smaller?

A client of ours was using outline offset to bring the focus within the links on the main navigation because it allowed for a more consistent appearance across different backgrounds. In that case (with our influence) they'd used a 2px thick indicator which would pass, but it seems odd fail case with 1px.

There are also instances of web-components where the actual button is 1 by 1px and the visual is produced by non-interactive markup.

Overall I'm coming around to the idea scoping to user-interface controls, with the size metric based on the contents of the UIC, which allows for flexility for things like rounded corners.

**Comment by patrickhlauke** [comment]
> If (according to the SC) the checkbox is the thing, and the author decided to outline the input & label, that's their prerogative and it easily passes the size metric.

yes but what about the other way around? when the thing that actually receives focus is the whole of the checkbox+label, but then it's styled so it appears to be just a regular checkbox inside that gets the focus? for instance,  a large `<button aria-pressed="...">` or even `<div role="checkbox" aria-checked="..." tabindex="0" ...>`, with the "checkbox" itself only a little SVG inside it (not uncommon approach).

we're back at the potential mismatch/tension between defining what is the "actual" UIC is. but yes, treating it more from a "what a user likely understands/interprets the control to be" (which may even differ, depending on who you ask) makes more sense than looking at the actual underlying way it was coded (and the border-box stuff etc)

**Comment by alastc** [comment]
> but what about the other way around? when the thing that actually receives focus is the whole of the checkbox+label, but then it's styled so it appears to be just a regular checkbox inside that gets the focus? 

Scoped to a user-interface control, it is what is perceived as the control, which I would argue is the checkbox. And, like your approach to the cards above, scoping to UIC means that you can take it on a case by case basis according what the control 'says' it is, which is partly defined by the behaviour of the focus indicator.

I think this approach maps best to what you're saying. The 'hole' it opens up is that the minimum area is smaller. However, if we emphasise the simple ways of meeting it (1px outline meeting both types of contrast,  or 2px outline meeting change-of-contrast), hopefully that doesn't make it harder to understand.

**Comment by scottaohara** [comment]
here are some more examples to show how not contrived this topic is:
https://codepen.io/scottohara/pen/ZEaXjQw

that codpen first has a custom listbox where, on hover the entire background of the option gets a background color with 1.16:1 contrast ratio.  however on focus, a 1px black outline with 1px offset goes around the inner "checkbox" that represents the entire options selected / not selected state.

In this example, clearly the option is the interactive control is the option but the nested visual indicator is what gets focus / visually communicates state.

for comparison, the next 2 items are checkboxes.  the first, similar to the listbox>options, is a custom aria checkbox where the entire container is given `role=checkbox`, but again the visual indicator of the control is a smaller checkbox within.  This behaves similarly to the options.

In contrast to that is a native checkbox within a label.  using CSS to mimic the custom examples, this label also gets the same background on hover, and the same focus treatment.  being within a label, it too has a much larger hit areas than what the visible control/hit areas appear to be.

what is the status of _very real_ examples like these?  if these fail, then this SC will fail a bunch of similar controls...

**Comment by alastc** [comment]
That's a useful example to consider. If we go with UIC (based on perception of what is the control) then it would be scoped to the visible checkboxes in both cases.

What it does trigger for me is the use of 'content' for a UIC. These don't have content (until you check them), so it would need to include the border (or whatever would fulfil 1.4.11) as the content for inputs which start blank.

**Comment by scottaohara** [comment]
here's another example I happened across this morning where the radio buttons don't get a focus indicator at all, but rather the content next to the radio buttons get a visible background change (i significantly bumped up the background coloring for my quick demo based on the design i saw)

https://codepen.io/scottohara/pen/yLPzGBB

**Comment by alastc** [comment]
That would pass (with that change of contrast), there is no requirement for the location of the indicator. (Which some people considered an issue, but we thought was best leaving flexible.)

**Comment by mbgower** [comment]
> There are also instances of web-components where the actual button is 1 by 1px and the visual is produced by non-interactive markup.

@alastc but that would fail target size, right?

**Comment by guyhickling** [comment]
@scottaohara That last codepen, is it showing something seen on a real website? If so, do you have the URL of the actual occurrence?

**Comment by guyhickling** [comment]
> ....is it a common practice on websites generally? Maybe this is not a big issue anyway? - That's beside the point.

I take it then that you don't know of any actual live websites that do this. If you want the SC to require something different from the default size of focus indicator, that browsers currently put round HTML components, surely someone can quote URL's of actual websites that have done this to support why they think some other meaning of the SC is needed. 

As it is, this makes me more worried that an excellent SC is going to be made more difficult to follow just to cater for situations that a) rarely arise in practice, and b) which could in any case be marked up better where they do occasionally occur! Don't get me wrong, I'm not saying I am unwilling to be convinced a different interpretation of "component" is needed. But I would like to be shown some real life evidence for it first (i.e. URLS of real websites), not just examples created artificially here.

> you'd be surprised what tricks and trickeries designers and developers often employ 

Now you are saying that to the wrong person! I am usually auditing a different website every week, and I am constantly being surprised by something new that I've never seen before. Indeed I sometimes wonder what planet some designers and developers think they are on! That's why the WCAG is so good, it helps to bring their feet back to the ground, benefiting all users!

**Comment by patrickhlauke** [comment]
> @scottaohara That last codepen, is it showing something seen on a real website? If so, do you have the URL of the actual occurrence?

and again...this misses the point. even IF examples were not used in production, they show things that can and will be done/attempted by developers, and a robust SC should not fall apart/cause doubts because of them

**Comment by patrickhlauke** [comment]
> this makes me more worried that an excellent SC is going to be made more difficult to follow just to cater for situations that a) rarely arise in practice, and b) which could in any case be marked up better where they do occasionally occur! 

since WCAG SCs effectively become "the law" (with legislation leaning on WCAG to provide a benchmark), we need to be very careful not to make things "illegal" because "well, we didn't think people would be doing this, and anyway they can do it another way", especially when the "illegal" way has absolutely no logical/discernible accessibility impact other than "the way we wrote it, this would fail, even though it's exactly the same as this other thing that does pass"

**Comment by scottaohara** [comment]
@guyhickling  all of my examples come from real designs that i have come across.  i have recreated the situations accurately (and sometimes with 'improved' color contrast accessibility) as not all websites / web applications can actually be linked to due to logins n' such.

**Comment by mbgower** [comment]
At the most basic level, if we are talking about assessing the focus _appearance_ we must be considering what an interactive component looks like before and after it gets keyboard focus.

Users interacting with a web page are not expected to inspect the code to figure out what the 'actual' size of the element is behind the scene. They just interact with the page. So at a basic gut level, how something is implemented should **not** be as important as whether a sighted user can easily tell what has focus and see where focus goes when they press Tab.

That is ultimately what the debate comes down to for me.

So I'm wondering if we can look at the wording in Non-text Contrast to help us with this, since it is wholly concerned with visuals...

> For active controls any visual information provided that is necessary for a user to identify that a control is present and how to operate it must have a minimum 3:1 contrast ratio with the adjacent colors. Also, any visual information necessary to indicate state, such as whether a component is selected or focused must also ensure that the information used to identify the control in that state has a minimum 3:1 contrast ratio.

Is there a way we can use this to help us improve:
> at least as large as the area of a 1 [CSS pixel](https://w3c.github.io/wcag/guidelines/22/#dfn-css-pixels) thick [perimeter](https://w3c.github.io/wcag/guidelines/22/#dfn-perimeter) of the unfocused component

Second thought, we've done a pretty good job of the second bullet with "a [minimum bounding box](https://w3c.github.io/wcag/guidelines/22/#dfn-minimum-bounding-box) of the unfocused component"

The core part of the definition is:
> the smallest enclosing box within which all the points of a shape lie. 

Do we get anything by tweaking the definition of minimum bounding box to have the parts of it that meet 3:1 contrast to something like:
> the smallest enclosing box within which all the points of a shape's minimum sufficient contrast lie.

**Comment by patrickhlauke** [comment]
> If you want the SC to require something different from the default size of focus indicator, that browsers currently put round HTML components

what i *want* is an SC that is specified in a way that takes account of many different approaches HTML/CSS (not even jumping into SVG, clip-path, heck... `<canvas>`) rather than taking some shortcut "for simplicity" of wording/testing, and then leads to all sorts of false negatives/fails that we can then only describe to clients with "yeah, i know this makes no sense, but that's the normative wording, and the spec writers didn't foresee you doing it this way"

**Comment by mbgower** [comment]
@patrickhlauke this is verging on an abstract debate :) But if the component isn't visually obvious without interaction, then the focus indicator clarifies what the component is (just as hover effects may help define it for a pointer user).

Maybe we can somehow **start** with the focus indicator, and let it help define the component...?

**Comment by patrickhlauke** [comment]
problem is that this becomes a circular argument (but maybe that's ok?)

"when something receives focus as denoted by receiving a visible focus indication, then that visible focus indication must be at least ..."

**Comment by patrickhlauke** [comment]
Sorry Guy, but that's an exceedingly naive answer. And it still doesn't address how you'd apply the SC to situations like SVG based, `<canvas>` based, etc interfaces (unless the answer here is also "developers just shouldn't do it"), or even perfectly common ARIA patterns with `aria-activedescendant` (where no, there is no default focus indication given by the browser, not in the place you'd want it anyway).

**Comment by guyhickling** [comment]
@patrickhlauke You don't win arguments by being insulting. Insulting remarks are just obstructive and have no place on a forum like this. We could consider how things like SVG and canvas might fit in, but that requires a willingness to discuss rationally rather than be obstructive.

**Comment by patrickhlauke** [comment]
fair enough, not "naive" then - "overly simplistic"

**Comment by guyhickling** [comment]
@scott, In your earlier codepen today, that first "My custom checkbox" would pass the SC. It uses a < div > with an ARIA role="checkbox" and tabindex attributes on it, which makes it an interactive element (and there would presumably be a click event on the same div and some JavaScript as well in the live website, to make it do what is required). 

Your focus indicator is larger than that interactive div, so it would pass the SC.

**Comment by patrickhlauke** [comment]
>  In your earlier codepen today, that first "My custom checkbox" would pass the SC. 

no it wouldn't if, as this whole discussion is about, you take the thing that actually receives focus (the outer `<div role="checkbox">` and use THAT as the anchor for then working out the necessary minimum area etc, as that outer `<div>` spans the whole width of the page.  so taking a "just take the size to mean the element that receives focus" approach would mean scott's example *fails*

> ![screenshot of the div in question, with chrome devtools highlighting to show it spans the whole width of the browser](https://user-images.githubusercontent.com/895831/154117030-a16a886c-8ff1-46b1-ad1c-14cb1659e8fe.png)

**Comment by guyhickling** [comment]
@scottaohara, Likewise, the first two "checkbox" lookalikes, that are each divs with a role="option" and tabindex, again they are the interactive components. The focus outline goes round them so is bigger and passes.

As I suggested in #2222, I think we would need to add a sentence or two to the Understanding doc (or maybe a green note under the SC?) to say that custom components using ARIA are the "component" for purposes of 2.4.11. They are very common on commercial websites. 

It would have to say that the div or span with the tabindex attribute and the click event is the one that is the interactive "component", but devs would naturally assume that anyway. (True, less experienced devs sometimes put the click event and tabindex on different elements, but that then tends to fail in screen readers so will usually have to be corrected anyway!)

**Comment by scottaohara** [comment]
@guyhickling your descriptions seem to not align with what is actually happening

>Likewise, the first two "checkbox" lookalikes, that are each divs with a role="option" and tabindex, again they are the interactive components. The focus outline goes round them so is bigger and passes.

that's not what's happening.  focus is going around the inner faux checkbox.

**Comment by patrickhlauke** [comment]
so guy...you just demonstrated that the whole foundation of the SC can vary depending on whether or not you actually look at/dissect the underlying code, since you flipped from a solid "they pass" to "ah, no, hang on, they fail". which is exactly what this issue here was arguing against.

> However this example is a supporting argument for the "visual appearance" lobby in this SC.

indeed.

**Comment by patrickhlauke** [comment]
> this is a big problem with this SC as written

and probably not even the normative SC per se, but it hinges on the normative definitions for https://w3c.github.io/wcag/guidelines/22/#dfn-user-interface-components and https://w3c.github.io/wcag/guidelines/22/#dfn-perimeter (or rather, what this gets replaced with ... bounding box, border-box) and the need for the latter to clarify that in some cases this may not be the *actual* thing that receives focus, but what a user would reasonably perceive as being the control

**Comment by mbgower** [comment]
@alastc as per the post-agwg 'hallway chat', in my [comment above](https://github.com/w3c/wcag/issues/2226#issuecomment-1040423501), I wondered about putting the emphasis on bounding box, and updating it to include a concept of minimum contrast. This is sketchy wording, but meant to convey the basic sense:

> at least as large as the area of a 1 [CSS pixel](https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html#dfn-css-pixel) thick  [minimum bounding box](https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html#dfn-minimum-bounding-box) of the unfocused component,

> bounding box: the smallest enclosing box within which all the sufficiently contrasting points of a shape lie.

**Comment by alastc** [comment]
Co-chair comment: @patrickhlauke  & @guyhickling please see the CEPC message to the group recently: https://lists.w3.org/Archives/Public/w3c-wai-gl/2022JanMar/0060.html

I see re-phrasing later, so I won't ask for edits.

On the topic, chair hat off:

> @alastc but that would fail target size, right?

No, JS is used to provide the hit area and CSS the focus indicator, but the focused item (in browser terms) is the background button so it could be an 8px area if it's based on the focused element


> problem is that this becomes a circular argument (but maybe that's ok?)

That's ok until you have to define size, which is the issue here. I don't think you can define a min size of the focus indicator if that is then defined by the focus indicator.


> I wondered about putting the emphasis on bounding box, and updating it to include a concept of minimum contrast. 

I've been thinking along similar lines, but want to avoid issue #2222 so I think the bounding box should go around the _content_ of the UIC, rather than the whole UIC.

That reduces the size requirement in many cases, but the simple case (contrasting outline) passes more easily.

I've put a few things together in #2230, so the key bit is:

> the area of a 1 <a>CSS pixel</a> thick <a>minimum bounding box</a> around the content of the component

Also adding a note, rough, but something like:
> The content of the component can be text or images. For blank inputs the bounding box contains the area that content would go if it were filled.

I think the definition of [bounding box](https://w3c.github.io/wcag/guidelines/22/#dfn-minimum-bounding-box) is ok, or at least I can't think how to improve it.

**Comment by guyhickling** [comment]
That definition would allow developers to put focus outlines inside the border on all components, regardless of how much empty space there is inside the component. Some developers do that already - on two or three sites I have even seen them put a dashed outline inside checkboxes and radio buttons, which just goes to show the lengths some designers will go to make keyboard focus indicators as inconspicuous as possible because they fear they spoil their design. (And an outline of 4 pixels squeezed inside a standard radio button makes it superlatively hard to tell when focus is on it!) 

This new SC would at least stop them doing that on radio buttons of course, but you get the point. Outlines inside a component's border are generally much harder to see, especially if the user's sight isn't good to begin with. 

I also worry that putting this reduced-size definition into a WCAG SC would actively encourage devs to put their outlines round a button's content instead of round the outside, even on standard text buttons that don't require any special treatment.

**Comment by alastc** [comment]
Hi @guyhickling,

First, let's work from a solid proposal, this is the [latest proposal](https://raw.githack.com/w3c/wcag/focus-appearance-content-term/understanding/22/focus-appearance-minimum.html) applying all the updates from various places.

> That definition would allow developers to put focus outlines inside the border on all components, regardless of how much empty space there is inside the component. 

Yes and no. It was already possible to put the focus indicator inside the border, in fact that's one of the examples at the top of the understanding doc. 

What this change (to bounding box of the content) does is slightly reduce the minimum size requirement. Before we were looking at the perimeter, but because it is the bounding box that makes a 1px outline fail in cases where you'd think it passes, e.g. due to border-radius.

What it does not do is reduce the contrast requirement, so if you do an internal indicator that must contrast with both the non-focused state AND adjacent colours. You'd also need a solid indicator, unless you have a very large button with small content a dotted/dashed indicator would still not meet the size requirement.

Whilst we are adjusting the minimum size slightly, we should make clear that the easiest way to meet it is a simple (contrasting) outline. We aren't doing this to encourage internal indicators.

**Comment by scottaohara** [comment]
so per the latest proposal (thank you for the link Alastair)
>the area of a 1 CSS pixel thick minimum bounding box around the content of the component

one could still interpret this to mean that my previous examples fail depending on what ‘component’ means.  e.g., the `role=option` and `role=checkbox` wrapping elements would be the ‘components’, but the visible ‘checkbox’ and the text is the content of those components.  But, being that only the ‘checkbox’ has a focus indicator which does not include the text - does that fail per this wording?

Again, if the checkbox is an actual checkbox though, there is no ambiguity because the text is not a child of the component.  so that’s still somehow fine for the same visual treatment?

I think it's important any wording that is used is clear about what is acceptable.  Which has gotten me wondering further about this SC, as it _seems to also be saying_ that something [like these examples](https://codepen.io/scottohara/pen/OJOOOKE) would fail because they are essentially not outlines around the content, or not a 4px thick line along one side of the element?

Honestly, I’m far more concerned with my original examples.  The new examples I provided just now could be rectified by adding a focus outline, even with `:focus-visible` so that the outline only shows up on focus... but I am asking to be absolutely clear.  Because the SC reads as if only an outline or a 4px line along a side of the focused element are sufficient indicators of being focused.  I do realize that’s not necessarily the intent of the wording... but I am having a really hard time reading it otherwise since the wording is so specific... and arguably other types of focus indicators have and should be fine... but if they’re no longer so, then I want to make sure that there is some solid language I could point at to say “yeah, i know your button is much bigger now... or that you have added an icon that wasn’t there before... but wcag says those aren’t allowed because X.  Only outlines or a 4px line along a side are allowed.”

**Comment by alastc** [comment]
Hi Scott,

User interface component is defined as:
> a part of the content that is perceived by users as a single control for a distinct function 

So for this:

> But, being that only the ‘checkbox’ has a focus indicator which does not include the text - does that fail per this wording

It doesn't matter what it is under the hood, if the checkbox is perceived as the control, that's what we start the measure from. Going from that definition means it is essentially based on the visuals.

> it seems to also be saying that something [like these examples](https://codepen.io/scottohara/pen/OJOOOKE) would fail

It's worth a look through the (now outdated but still somewhat helpful) understanding doc, at least at the examples.

It is taking a size metric, so although those examples are unusual, we can walk through the SC for button 1:

- Contrasting area: Massively more than the requirement, it counts the area that goes from black to white around the button. 
- Adjacent contrast: It is adjacent (as it is an expansion) and doesn't contrast with the component itself, but it's more than 2px thick. 
Pass

Button 2:
- Contrasting area: This one is tricky to work out as the change is the text moving and the addition of a (1px thick?) little arrow. If you super-impose the focus on the default state:
<img src="https://user-images.githubusercontent.com/216630/154309972-fda54903-fff6-4d45-8096-5247d06eb828.png" alt="Black background with the word 'two' on it twice, slightly overlapping.">
If you compare that to the bounding box around the content, I don't think the grey pixels here would be enough:
<img src="https://user-images.githubusercontent.com/216630/154315772-88e2de8a-30f8-4b6f-a7d1-90cbd2d159cd.png" alt="The same button with a red outline around the words.">

- Adjacent contrast: It is adjacent (as it is an internal), but as the contrasting area is white text to a black background that would pass this bullet.

So button 2 fails (I think, it's difficult to count the pixels there, but I'd strongly encourage people to avoid that sort of situation. If it were an audit I would pixel count, but regardless of pass/fail I'd suggest they use a better indicator.) I think it is also an indicator that the people most affected by this would find difficult.

> I am having a really hard time reading it otherwise (that as an outline) since the wording is so specific... and arguably other types of focus indicators have and should be fine...

Indeed, this is a **_size metric_**, a basis for comparison to something that is proportional to the thing with focus.
 
Outline is a good way to meet it, but anything with sufficient size & contrast can pass.

**Comment by aardrian** [comment]
@alastc Above you link a sample (https://codepen.io/alastc/pen/eYGoKyP), which includes examples pulled from my block links post. Following the examples you write:

> From a visual point of view, I find it impossible to evaluate these two 'card' examples without knowing what the interactive element is. The HTML for each is the same, but the first one uses CSS to increase the hit area and

It stops at the "and". I am very interested to know the rest of the sentence and if that pattern (either variation) passes this SC as written. If not, then that tells me I still am not following the language used. If so, it would be helpful to understand how.

This is not meant to be a "please audit my work for me" request. Your example just happens to use a thing I made.

**Comment by scottaohara** [comment]
@alastc really appreciate you taking the time to go through these and explain.  thank you.

>User interface component is defined as:

Thanks on the reminder there, and yes that's what I had understood.  But per the previous review where at first my examples failed, but then once it was noticed that the focused element was the larger container and the 'checkboxes' were within... it became unclear and the wording hadn't changed enough to make me think this was addressed.  But if the interface component in this instance can be understood as "what looks like the interactive element" rather than "what is actually the interactive element" then yeh, that seems clearer and that these examples should be fine.

>Indeed, this is a size metric, a basis for comparison to something that is proportional to the thing with focus.
>Outline is a good way to meet it, but anything with sufficient size & contrast can pass.

maybe that's what is tripping me up then.  I don't read the current text to indicate "these specific points are used as examples of sizing" so much as they read as "these are the two things you can do.  an outline, or a 4px line along the shortest side...."

i realize the text says "and that area is at least as large as either:" but until right now, I read the list as I would other instances of lists in other SC - specific requirements or specific exceptions.  Could this potentially be revised to a list that represents three items, where the two that exist represent two focus indicators that the WG has deemed as acceptable indicators, and a 3rd that is more ambiguous and specifically notes that another sort of indicator could be used if it comparatively meets the sizing metrics of the former two items?   

essentially something to normatively indicate:
>Outline is a good way to meet it, but anything with sufficient size & contrast can pass.

thanks

**Comment by alastc** [comment]
Hi @aardrian,

> It stops at the "and". I am very interested to know the rest of the sentence and if that pattern (either variation) passes this SC as written.

Ach, I'm juggling too many things for my current brain. I think I was just going to finish the statement of fact: and the second does not. 

As for how that evaluates, I think it's more or less like [Pat's comment](https://github.com/w3c/wcag/issues/2226#issuecomment-1040441218): If you interact with it and it appears to be the link, you evaluate the link. If it appears to be the card, you evaluate the card. (I think both pass, assuming the indicator has contrast.)

Most things are more straightforward, but if the appearance of the control is ambiguous then there is going to be some working out of what it is. 

@scottaohara :
> But per the previous review where at first my examples passed, but then...

Sorry, it's confusing because we've been discussing [various ways](https://github.com/w3c/wcag/issues/2226#issuecomment-1038447602) to define the component, and therefore the size. The current proposal (sent to the group for discussion next week is the one I linked above using UIC.

>  they read as "these are the two things you can do. an outline, or a 4px line along the shortest side...."

The SC text does refer to it as an "area" three times before it lists the basis for the size of that area. I'd like to keep the normative text as clear and short as it can be (in keeping with the others), but tackle that misconception either in the first note, and/or the understanding doc. 

E.g. the first note could be: 
"The contrasting area is a minimum size, there is no requirement that the indicator matches the shape of an outline. The content of the component can be text or images. For blank inputs the bounding box contains the area where content would go."

Also, if you scan down the understanding doc, there is an 'unusual shapes' section where the indicators are not simple outlines/lines.

**Comment by alastc** [comment]
> I would strongly urge to reconsider just focusing on the element's raw CSS dimensions, but rather what their apparent dimensions are.

The changes since this issue came up the text has changed to "Encloses the visual presentation of the user interface component;".

So I'm closing as this has been addressed.

**Comment by patrickhlauke** [comment]
Thanks, happy with that.
