### ISSUE TITLE
Have a document about how to find the reading order of elements on the page

### ISSUE THREAD

**Issue by ollie-iterators** [w3c/wcag#2290]
I was working on finding how to analyze the reading order of elements on a website using Selenium and I was having difficulty finding a way to determine what the reading order of elements on the page was.

I know that the reading order is different than "Tab Order", in that there are no attributes that are available to determine Tab Order like tabindex, but I think that it would be a good thing to have something like the algorithm about accessible name generation: https://www.w3.org/TR/accname-1.1/, to determine the value in the reading order for elements.

**Comment by patrickhlauke** [comment]
reading order is generally the same as source/DOM order (which can often differ considerably from visual layout/order).

**Comment by patrickhlauke** [comment]
as you can't automatically determine if the reading order makes sense or not, it's likely easier to look for "code smells" that may mean the layout is different from the source order, so that a human auditor can then go and manually verify. anything like `float`, absolute positioning, flex/grid layouts, are usually good candidates for "this may be visually shown in a different way, verify that this still makes sense"

**Comment by ollie-iterators** [comment]
The ANDI (https://github.com/SSAgov/ANDI) tool for Accessibility Testing has a feature that is about overlaying the reading order on the elements on the website.

**Comment by ollie-iterators** [comment]
This is less important now. So I'm closing the issue.
