### ISSUE TITLE
1.3.1 requirements for chats - explicit vs. implicit semantics

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#2346]
Hi,
1.3.1 Info and Relationships stipulates that information conveyed visually should also be available programmatically. In a chat interaction (technical support), when the messages of the user seeking help and replies of support staff are clearly differentiated visually through color AND text alignment, would you think that **explicit** semantics, some programmatically available marker (e.g., an automatically generated date / user stamp preceding each input) are a normative requirement of 1.3.1? 
In many cases, it seems that the exchange itself has sufficient **implicit** semantics for the user re-reading the conversation to work out what he or she wrote, and what the support staff wrote. And while interacting, the distinction is clear anyway as the exposure of own messages immediately follows the user's input. In re-reading, there is also less noise caused by the repeated output of the date/user stamp befor each message, so there may even be a slight cognitive advantage in avoiding them. Any opinions? Will a stream of unmarked messages fail 1.3.1? (I am aware that there need to be appropriate roles like `role=log` to ensure new chat input is exposed to the user, this concerns the **re-reading** of the conversation).

**Comment by patrickhlauke** [comment]
i'd say if it's not explicitly present visually, can't require it be explicitly present programmatically. though of course as best practice, it's always good to add as much extra info as possible programmatically (though you could then argue that AT users are at an advantage compared to non AT users?)

**Comment by bruce-usab** [comment]
FWIW, I would be inclined to fail it against 1.3.1.  Ping to my colleague @kengdoj who might say if TT or baseline would catch this.  I would inclined to delve into the user experience.  Presumably the chat is otherwise accessible, so if someone using a scorereaders reviews the chat thread, is there really no cue as to what the user wrote versus support staff reply?  Visually, it is obvious, so IMHO there needs to be something programmatically exposed to the AT.

This is kind of a long standing issue.  A string of integers with a certain pattern is obviously visually a phone number.  That gets a pass (usually) since it is something a screen reader user learns to recognize.  More problematic is a static 7 by 5 grid of integers.  Visually it is obviously a calendar, and 2.x does require date pickers to be keyboard accessible.  In the U.S., the middle column of numbers are Wednesdays.  Even though this sort of unlabeled static grid has much less utility for someone using screen reading software, I think it would be a stretch to fail against 1.3.1.

**Comment by bruce-usab** [comment]
> I may have given the wrong impression of the visual aspect. In the chatbot I refer to...

No, I think I understand your scenario. During the chat, I don't think there is a barrier, since keeping track live of you said / they said is no problem.  It kind of reminds me of old-school TTY calls: it is all running text.  Reviewing the call, for whatever reason, maybe even in print (!), it is hard to tell who said what.

Your scenario is more like IM where reviewing you said / they said, it is obvious who wrote what.  So if on a web page, where the you said / they said is informational presented visually &mdash; that needs to be available to an AT user.  But the WCAG definition for <q>programmatically determinable</q> is pretty loose &mdash; so I would argue an auditor needs to be flexible as what counts for exposing the you said / they said aspect of the conversation.  But there does need to be something, and it can't be too subtle.

**Comment by mbgower** [comment]
Some visuals would help here, because ultimately if you're talking about 1.3.1 in this context, we are talking about "Information, [structure](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#dfn-structure), and [relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#dfn-relationships) conveyed through [presentation](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#dfn-presentation)"

By far the easiest way to resolve this may be to simply have a "[username]:" at the start of each comment (and it could be as simple as "support"/"you").

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do so and move it to Discussions.
