### ISSUE TITLE
Expect difference in Sufficient Techniques 3.3.7. and 3.3.8, at least one

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2378]
https://w3c.github.io/wcag/understanding/accessible-authentication.html
https://w3c.github.io/wcag/understanding/accessible-authentication-no-exception.html

Sufficient Techniques are exactly the same for both 3.3.7 and 3.3.8, would be good to see a difference as they are 2 SC where one will be sufficient for 3.3.7 but not 3.3.8

**Comment by alastc** [comment]
Sure, just need to find someone with time to write such a technique...

**Comment by mbgower** [comment]
@jake-abma 
I agree it seems rather odd when even the future techniques are essentially the same for both the AA and AAA.

Examining the differences between the SCs, I think the thing to do is add a technique to 3.3.7 (the AA, not the AAA) that covers the use of the CAPTCHA 'select objects' technique, since as far as I can tell that is what the exception is there for. That provides a clear difference between the two SCs in regard to implementation.

Of course, focusing on the CAPTCHA highlights a problem with this SC since it's not an authentication method. It's a human validation process that for whatever reason pops up after an authentication process in some circumstances. Since we don't actually define authentication, I guess we can just let it pass...

**Comment by alastc** [comment]
> Of course, focusing on the CAPTCHA highlights a problem with this SC since it's not an authentication method. It's a human validation process that for whatever reason pops up after an authentication process in some circumstances. 

If it isn't part of the authentication process then it's out of scope, but there are instances when it pops up _during_ an authentication process. Those are the ones it is intended to catch.

**Comment by awkawk** [comment]
Seems like "authentication process" is the parent and it includes the human validation/verification process that is the basis of the exception. I agree with @mbgower that the "click on all of the cars" challenges are not authentication but do thing that they are part of some authentication processes.

**Comment by alastc** [comment]
> It would be good to understand if this really is the only intended difference between the AA and AAA requirements. 

That aspect used to be part of the cognitive function test (CFT) definition, but the separation came about because we had two things in conflict: 

- Folks in COGA objected to object-recognition not being covered by CFT. 
- There are instances where those types of CAPTCHAs are used as part of an authentication flow to prevent automated abuse.

I didn't think we could ban people from using something that prevents that type of abuse, they are often triggered by too much traffic from a particular IP address ranges, or sometimes just have an empty cookie. 

So we put in an exception at the AA level (with text pointing out it's still not good to do), and removed it from the AAA level.

It is a niche but important case.

**Comment by jake-abma** [comment]
Checked this one and we still have no difference, will this be added before final launch?

**Comment by alastc** [comment]
Backlog meeting notes:

We're not comfortable with adding a specific technique that implies we encourage CAPTCHAs at the AA level. Perhaps we can adjust the examples in the AA understanding document instead?

Or add a note to each technique saying that it would pass AA if it included a object recognition CAPTCHA, but not at AAA.

**Comment by JohnRochfordUMMS** [comment]
"We're not comfortable with adding a specific technique that implies we encourage CAPTCHAs at the AA level" seems the antithesis of "... add a note to each technique saying that it would pass AA if it included a object recognition CAPTCHA...". I apologize, I don't understand. Would you please elucidate? Thank you.

**Comment by alastc** [comment]
Hi John,

The difference is that if we create a new technique, e.g. "Email link authentication with object recognition", that comes across as something we recommend.

I think it would be more efficient to include an optional step in the test procedures to differentiate the AA/AAA levels.

From further discussion, we could in G218:
```
Procedure:
For websites which allow users to login by emailing a link to the email address associated with the account:

1.  Enter a valid email address (with an account on the website) and use the email-link feature.
2. Check that the email is received.
3. Check that selecting the link opens the website.
4. Check that the user account is logged in.
5. Check that no object recognition test is used as part of the authentication process.

Expected Results

- #2, #3 and #4 are true.
- For Accessible Authentication at AAA level, #5 is also true.

```

**Comment by alastc** [comment]
We have 3 techniques for AA, 2 for AA (and no requirement for different techniques for each) so I'll close this one now.
