### ISSUE TITLE
Why a different writing for the same idea 2.4.11 Focus Appearance (Minimum)?

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2446]
First part of SC text and second part seem to have the same rule but different writing, why?
https://w3c.github.io/wcag/guidelines/22/#focus-appearance-minimum

First part:

> the [focus indicator](https://w3c.github.io/wcag/guidelines/22/#dfn-focus-indicator) has a contrast ratio of at least 3:1 between its pixels in the focused and unfocused states;

Second part (exception)

> An area of the focus indicator has a contrast ratio of at least 3:1 against the same pixels in the unfocused state, and

(shouldn't they be written exactly the same for clearness and consistency or do I miss something here?)

**Comment by bruce-usab** [comment]
The first part is about the focus indicator itself, and presumes a solid line as border.

The second part (exception) could be inside that (i.e., an area of the focus indicator) because maybe the indicator area _starts_ as light gradient.

So the parts can't be written exactly the same, but I am less comfortable with this than I was before your comment!

**Comment by jake-abma** [comment]
Exactly @bruce-usab writing it in the same way to me is the same but consistent:

> An area of the focus indicator has a contrast ratio of at least 3:1 between its pixels in the focused and unfocused states;

**Comment by alastc** [comment]
They are now aligned in the [CR version](https://www.w3.org/TR/WCAG22/#focus-appearance), so closing.
