### ISSUE TITLE
F78 and F55 can be added to Focus Appearance

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#2474]
F78 and F55 can be added to 2.4.11
https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html#techniques

Just like in 2.4.13 F78 and F55 can be added to 2.4.11

> [F78: Failure of Success Criterion 2.4.7 due to styling element outlines and borders in a way that removes or renders non-visible the visual focus indicator](https://w3c.github.io/wcag/techniques/failures/F78)
> [F55: Failure of Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus when focus is received](https://w3c.github.io/wcag/techniques/failures/F55)

https://w3c.github.io/wcag/understanding/focus-appearance-enhanced.html

**Comment by mbgower** [comment]
**Draft Proposed Response**
Neither failure is a precise match for 2.4.11

F55 is not a precise match for 1.4.11. The wording of the SC is (with my emphasis):
> **_When_** a [user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html#dfn-user-interface-component) receives keyboard focus, the component is not entirely hidden due to author-created content.

The wording of F55's test shows that it is only failed if focus does nor remain until the user moves it; however, 2.4.11 only requires the _component_ not to be hidden **when** it receives keyboard focus.
    
> Tests
Procedure
Use the keyboard to verify that you can get to all interactive elements using the keyboard.
Check that when focus is placed on each element, focus remains there until user moves it.

F78 is not a precise match because it only measures whether focus is visible, not whether the item with focus is visible.
> Tests
Procedure
Set the focus to all focusable elements on a page using the keyboard.
Check that the focus indicator is visible.

**Comment by patrickhlauke** [comment]
noting this now refers to https://www.w3.org/TR/WCAG22/#focus-appearance 2.4.13 Focus Appearance

**Comment by alastc** [comment]
@mbgower I think there's a little confusion, this is focus-appearance rather than focus-not-obscured (I'm going to avoid numbers here!)

I think F78 might be, but F55 would be for focus-not-obscured.

**Comment by mbgower** [comment]
Originally I got confused and made a draft response comparing these techniques against 2.4.11 Focus Not Obscured (Minimum), since the original heading for this issue was " F78 and F55 can be added to 2.4.11". 

The confusion arose because at the time the issue was open, 2.4.11 was the number for Focus Appearance, and that is the SC that is intended to be addressed. However, at the time of publication, 2.4.11 became the number for Focus Not Obscured (Minimum).
 
Although I have updated the draft response to address Focus Appearnace, I thought I would preserve my comments here regarding Focus Not Obscured, in anticipation of anyone desiring to apply the same two failure techniques against Focus Not Obscured.

---

Neither failure is a precise match for 2.4.11

The wording of the SC is (with my emphasis):
> **_When_** a [user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html#dfn-user-interface-component) receives keyboard focus, **_the component_** is not entirely hidden due to author-created content.

The wording of F55's test shows that it is only failed if focus does nor remain until the user moves it; however, 2.4.13 only requires the _component_ not to be hidden **when** it receives keyboard focus.
    
> Tests
Procedure
Use the keyboard to verify that you can get to all interactive elements using the keyboard.
Check that when focus is placed on each element, focus remains there until user moves it.

F78 is not a precise match because it only measures whether focus is visible, not whether the item with focus is visible.
> Tests
Procedure
Set the focus to all focusable elements on a page using the keyboard.
Check that the focus indicator is visible.
