### ISSUE TITLE
ARIA2 example 3 is invalid

### ISSUE THREAD

**Issue by alastc** [w3c/wcag#251]
From an external discussion, [example 3 in technique ARIA2](https://www.w3.org/TR/WCAG20-TECHS/ARIA2.html#ARIA2-ex3) uses:
```
 <ul  id="rg" role="radiogroup" ...>
    <li id="rb1" role="radio">Yes</li>
```

According to [ARIA in HTML](https://www.w3.org/TR/html-aria/), radiogroup isn't allowed on UL, and radio (or radiogroup) on LI.

I suggest updating the example with something more like the [ARIA 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/examples/radio/radio.html) example:

```
<div role="radiogroup" ...>
  <div role="radio"...>
```

**Comment by jnurthen** [comment]
Seems inconsistent that LI allows menuitemradio but doesn't allow radio.

**Comment by mcking65** [comment]
I would push for a formal response to w3c/html-aria#30 because I believe that issue is a bug, which would make this issue invalid.

**Comment by jongund** [comment]
Matt,

This seems like a bug to me

Jon  Gunderson
Sent from my iPhone

On Nov 8, 2016, at 4:29 AM, Matt King <notifications@github.com<mailto:notifications@github.com>> wrote:


I would push for a formal response to w3c/html-aria#30<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_w3c_html-2Daria_issues_30&d=DQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=REZD8fc2AwufInstfW3L5jSLVS8bjZtAodDOhat7yAI&m=TZzdhlNKR_Aeg0OOWE4V-6VP3nms9VZ-pV4nW89gc2I&s=6aKuai26EgfxzE6usiQEbKdM-tc6OTfhaRn1gvFQrGM&e=> because I believe that issue is a bug, which would make this issue invalid.

**Comment by awkawk** [comment]
I think that waiting for the html-aria#30 issue to be resolved makes sense.

**Comment by alastc** [comment]
Sure, is there an 'on hold' status or something?

**Comment by alastc** [comment]
This was closed on html-aria, ul/li is valid, so closing this issue.
