### ISSUE TITLE
WCAG Supporting Documents links are almost all wrong

### ISSUE THREAD

**Issue by jribbens** [w3c/wcag#2572]
At https://www.w3.org/TR/WCAG22/#wcag-2-2-supporting-documents there are 4 main links to supporting documents. Three out of four of these links ("How to Meet", "Understanding", and "Techniques") wrongly link to the WCAG 2.1 versions of the documents, instead of the WCAG 2.2 versions.

At https://www.w3.org/TR/WCAG22/#numbering-in-wcag-2-2 the "Quick Reference" link has the same problem.

**Comment by cstrobbe** [comment]
* "How to Meet WCAG 2.2" now links to https://www.w3.org/WAI/WCAG22/quickref/
* "Understanding WCAG 2.2" now links to https://www.w3.org/WAI/WCAG22/Understanding/ 
* Techniques for WCAG 2.2 now links to https://www.w3.org/WAI/WCAG22/Techniques/ 

So it seems that the links have been fixed since this issue was submitted. Can the issue now be closed?

**Comment by jribbens** [comment]
Yes, it looks like somebody fixed it without closing the issue.
