### ISSUE TITLE
Does WCAG apply only to English (or the like), or does it aim to cover all languages?

### ISSUE THREAD

**Issue by kidayasuo** [w3c/wcag#2680]
Hi, I am from the W3C Japanese Language Enablement Task Force (aka [JLReq TF](https://github.com/w3c/jlreq)).

I am wondering if WCAG is supposed to cover all languages or if it is limited to English and similar languages. I am asking because it came to our attention that some descriptions do not or might not apply to the Japanese language. Examples we noticed are sections 1.4.8 Visual Presentation and 1.4.12 Text Spacing. I would much appreciate your help understanding this document's nature so we can make appropriate comments.

Thank you!

**Comment by JAWS-test** [comment]
The WCAG, as far as I know, claims to serve all languages of the world. However, it was written mostly by people from the US, European and Japanese language areas, so other languages may be underrepresented. 

For example, 1.4.8 explicitly states:

> Width is no more than 80 characters or glyphs **(40 if CJK)**.

It would be helpful if you could explain why 1.4.8 and 1.4.12 do not apply to Japanese?

**Comment by kidayasuo** [comment]
These are ones we noticed.

>- Line spacing (leading) is at least space-and-a-half (1.4.8)
>Line height (line spacing) to at least 1.5 times the font size; (1.4.12)
Japanese text (and probably Chinese?) requires wider line spacing compared to English. For example, regular books for ones with normal eyesight have line spacing of around 150% to 200%. Books for ones with special needs have wider line spacing. I believe I can post an example later.

> paragraph spacing is at least 1.5 times larger than the line spacing (1.4.8)
>Spacing following paragraphs to at least 2 times the font size; (1.4.12)
Japanese do not use an empty line to indicate a paragraph. Instead, the first character of a paragraph is indented. While many recent digital contents, such as the web, follow the English style, books follow the traditional rule, including ones created for dyslexia. I guess this one falls into the exception category described in the last part of 1.4.12 (but the exception clause is not in 1.4.8).

>Letter spacing (tracking) to at least 0.12 times the font size;(1.4.12)
The letter spacing in Japanese text is zero, including contents created for dyslexia.

>Text is not justified (aligned to both the left and the right margins). (1.4.8)
I have a question on this. What is the reasoning behind this rule? I would like to figure out if this one equally apply to Japanese.

---
Please note that these are ones we happened to notice. Also there are rules that apply to Japanese text (and possibly to some other languages) but not to English such as handling of ruby.

**Comment by alastc** [comment]
WCAG aims to be applicable to all languages, although I'd note most people working on it are from western countries. It also goes through an internationalisation review process.

@MakotoUeki is probably the best person to ask how the current criteria have been applied in Japanese. There is also an [unofficial translation of WCAG 2.0 into Japanese](https://waic.jp/docs/WCAG20/Overview.html) which might have some clues.

**Comment by murata2makoto** [comment]
Here is a screen copy of a Japanese DAISY reader (ChattyBooks).  

The default value for line spacing is 2.6 and that for letter spacing is 0.2.  I guess that 2.6 means 260%.

![ChattyBooksLineSpacing](https://user-images.githubusercontent.com/5499496/191405513-fe919a04-f393-4127-a6e1-c94af8a21322.png)

**Comment by kidayasuo** [comment]
ah, the letter spacing was not zero. I misunderstood.

**Comment by JAWS-test** [comment]
I think WCAG should aim to apply to all cultures, all languages, and all writing systems. I understand that this is not the case. This should be fixed. Regarding writing systems, criteria 1.4.8 and 1.4.12 should be adjusted. 

For 1.4.8, I have no idea regarding the maximum number of characters (40 and 80).

For 1.4.12, it might be possible not to define values relative to the font size, but only relative to the default spacing (e.g. the line spacing must be able to be increased to 1.5 times the default line spacing). However, I don't know if the browsers define a uniform default spacing for each language.

**Comment by JAWS-test** [comment]
@alastc Can you please assign the correct labels: 1.4.8, 1.4.12 and a new one: "internationalisation"? "Discussion" is a bit too general. This seems to me to be an important topic that should not be lost.

**Comment by MakotoUeki** [comment]
Interesting topic.

Here is the historical note. I was involved in the development of both WCAG 2.0 and JIS X 8341-3.

The JIS X 8341-3 working group checked success criteria in WCAG 2.0 which could introduce language specific issues, including 1.4.8, when JIS X 8341-3 adopted WCAG 2.0 success criteria in 2010. 

For example, there is a note for "[large scale text](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum#dfn-large-scale)" in 1.4.3, which reads:

> The 18 and 14 point sizes for roman texts are taken from the minimum size for large print (14pt) and the larger standard font size (18pt). For other fonts such as CJK languages, the "equivalent" sizes would be the minimum large print size used for those languages and the next larger standard large print size.

So the JIS X 8341-3 working group looked for the "equivalent" sizes in Japanese and set different font sizes based on the standard large print sizes. The sizes were specified in the JIS X 8341-3:2010 and [Japanese translation of WCAG 2.0](https://waic.jp/docs/WCAG20/Overview.html#larger-scaledef).

For another example of 1.4.8, JIS working group asked the WCAG working group to specify the number of characters for Japanese. Then the 1.4.8 had "(40 if CJK)" at last.

> Width is no more than 80 characters or glyphs (40 if CJK).

This is my personal opinion, but we'll be able to address any other language issues in the same way. I think JIS X 8341-3 will be updated once WCAG 2.2 become the W3C recommendation and it is adopted as the new version of the ISO/IEC 40500. That will be the next opportunity for us.

@kidayasuo 
If you have any suggestions for Japanese web content, that will be super helpful for the next update of JIS X 8341-3. The JIS X 8341-3 working group will need the research-based evidence to address these issues. 

And I'm very curious about how China and Korea has been addressing these language issues.

@GreggVan would have insights and thoughts on how we should address these kind of issues in WCAG.

**Comment by murata2makoto** [comment]
Here goes my first comment.

>This is my personal opinion, but we'll be able to address any other language issues in the same way.

I do not believe that WCAG can cover details of all natural languages.   Who knows appropriate line spacing for Korean, Mongolian, Tibetan, Arabic, Hebrew, Thai, and so forth?  Rather, I would like to allow each language group to create a separate specification for that language when the group is ready.  This is similar to JLreq, ILreq, CLreq, KLreq, HLreq, ALreq, and so forth.

**Comment by JAWS-test** [comment]
So either we formulate the SC universally and if that is not possible, it should be mentioned in the Understanding that they only apply to certain writing systems.

**Comment by kidayasuo** [comment]
@MakotoUeki thank you very much for your comments:
> If you have any suggestions for Japanese web content, that will be super helpful for the next update of JIS X 8341-3.

I am not knowledgeable about this area, so I just listen to what experts, like you, say. The Japanese Language Enablement Task Force is planning to develop a digital text version of [JLReq](https://www.w3.org/TR/jlreq/), called [JLReq-d](https://github.com/w3c/jlreq-d). In this new document, we plan to include rules and guidelines to make text layout more accessible to a broader audience; it is something everybody who deals with text content needs to be aware of. We need help from area experts like you, and I would very much appreciate it if you could.

> The JIS X 8341-3 working group will need the research-based evidence to address these issues.

I agree that basing on research-based evidence is important. I wonder that not necessarily all practices applied by books developed for dyslexia are backed by research however. Some of them are based on accumulated feedback from its users, and many of them would be, I guess, legitimate. How do you handle them in JIS X 8341-3?

>Text is not justified (aligned to both the left and the right margins). (1.4.8) ... What is the reasoning behind this rule?

I am particularly interested in this rule. Are there research papers that back up this rule for English and/or Japanese text? I would like to learn.

>The sizes were specified in the JIS X 8341-3:2010 and [Japanese translation of WCAG 2.0](https://waic.jp/docs/WCAG20/Overview.html#larger-scaledef).

Should they be reflected back in WCAG considering it aims to cover all languages?

**Comment by MakotoUeki** [comment]
> How do you handle them in JIS X 8341-3?

The working group should also hear users voices where possible, especially when the research-based evidences are not available. 

When the JIS was revised in 2010 to adopt WCAG 2.0, the working group solicited public comments and invited opinions on the draft as much as possible. The working group addressed the issues they got from the public. Since 1.4.8 was at level AAA, they may not have shown much interest though.

If you know there is an issue for some users, I'd like to listen to them so that I could share it with the working group and the committee ([WAIC](https://waic.jp/)) at least. And they will be able to discuss the issue for the next update. 

> I am particularly interested in this rule. Are there research papers that back up this rule for English and/or Japanese text? I would like to learn.

@bruce-usab explained the rationale. And I'm not sure if there is the back-up for Japanese text, but it is understandable that some users would get overwhelmed if letter spaces are not equal line by line.

If the issue won't happen or different issue happens in Japanese text, we probably can add a note to next version of JIS X 8341-3 and Japanese translation of Understanding WCAG document.

> Should they be reflected back in WCAG considering it aims to cover all languages?

I don't think so. WCAG says "For other fonts such as CJK languages, the "equivalent" sizes would be the minimum large print size used for those languages and the next larger standard large print size." This would be enough. JIS working group addressed this and found the "equivalent" sizes for JIS X 8341-3. Any other non-English speaking countries can do the same way if WCAG shares how it was set/defined for English text like this success criteria.

I don't think so. It would be difficult to set an universal numeric criterion especially for text/font related issues, which covers different lanaguages. 

In this case, WCAG says "For other fonts such as CJK languages, the "equivalent" sizes would be the minimum large print size used for those languages and the next larger standard large print size." This would be enough. 

JIS working group addressed this and found the "equivalent" sizes for JIS X 8341-3. Any other non-English speaking countries can do the same way if WCAG shares how it was set/defined for English text like this success criteria.

**Comment by murata2makoto** [comment]
Let me give more background information.  I am the chair of the technical committee of the Japan DAISY Consortium.  I was the chair of the JIS Committee for EPUB Accessibility.  I am also the leader of a research project for evaluating the readability of Japanese text using eye-tracking machines (Tobi).  More about this project is available [here ](https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-19H01705/)(but in Japanese).

> What are the special properties for Japanese content created for dyslexia? For example, in the U.S. there are specialized font faces and AT that highlights word-by-word.

Ruby between lines obviously makes line-spacing difficult.  No space occurs between words in typical Japanese text, but this might not be good for dyslexic people.  (This is the main topic of the research project mentioned above.  Adding space between words is good for some (though not all) dyslexic users.))  I know little about character-spacing, but the Japan DAISY consortium chose 0.2.

>>The JIS X 8341-3 working group will need the research-based evidence to address these issues.

>I agree that basing on research-based evidence is important. I wonder that not necessarily all practices applied by books developed for dyslexia are backed by research however. Some of them are based on accumulated feedback from its users, and many of them would be, I guess, legitimate. How do you handle them in JIS X 8341-3?

Having done the research project mentioned above for three years, I start to trust feedback from practionners more.  Research is not allmighty.  ;-(

> If you know there is an issue for some users, I'd like to listen to them so that I could share it with the working group and the committee (WAIC) at least. And they will be able to discuss the issue for the next update.

I am afraid that JDC has not provided enough feedback.  Will try harder next time.

>>Rather, I would like to allow each language group to create a separate specification for that language when the group is ready.

>I agree with you. That is exactly what JIS X 8341-3 has addressed the language issues when adopting WCAG 2.0.

But the hands of JIS drafting committees are tied.  There are some strict rules about changes to normative requirements.  It would be much better if WCAG does not say anything not applicable to all natural languages.

**Comment by MakotoUeki** [comment]
@murata2makoto 
> Having done the research project mentioned above for three years, I start to trust feedback from practionners more. Research is not allmighty. ;-(

Yes, feedback from practitioners can also be the evidence. No doubt about it.

As to [SC 1.4.12](https://waic.jp/docs/WCAG21/Understanding/text-spacing.html), it was introduced in WCAG 2.1 which means JIS X 8341-3 hasn't include it yet. JIS working group will discuss it once the working group is organized for the next update. And they will look for papers and inputs from experts.

> It would be much better if WCAG does not say anything not applicable to all natural languages.

I'd like WCAG to share the rationale where possible so that the criterion can be applied to any languages. I think we are on the same page. And I'll keep it in my mind as one of the participants in the AG working group.

**Comment by r12a** [comment]
Fwiw, these are some related issues (all now archived):
- https://github.com/w3c/wcag21/issues/677
- https://github.com/w3c/wcag21/issues/388
- https://github.com/w3c/wcag21/issues/389
- https://github.com/w3c/wcag21/issues/390

**Comment by bruce-usab** [comment]
Thank you @r12a for the link to that 18n article on justification

But FWIW, I think one or two new labels would have been more functional (in the context of this repo) than six.

@JAWS-test wrote:
> So either we formulate the SC universally and if that is not possible, it should be mentioned in the Understanding that they only apply to certain writing systems.

The SC are formulated to be universal and known exceptions are already included in Understanding and sometimes the SC themselves.

**Comment by r12a** [comment]
> But FWIW, I think one or two new labels would have been more functional (in the context of this repo) than twelve.

Each label routes notifications about this thread to a different group of experts. Given the original title of this thread, it seems that all of our lreq groups may be interested in following the discussion. Omit a label, and the group won't be notified.

**Comment by murata2makoto** [comment]
> @JAWS-test wrote:
> 
> > So either we formulate the SC universally and if that is not possible, it should be mentioned in the Understanding that they only apply to certain writing systems.
> 
> The SC are formulated to be universal and known exceptions are already included in Understanding and sometimes the SC themselves.

I think that every SC should be universal.  If an SC has exceptions, it is not universal enough and should be reformulated.  SCs 1.4.8 and 1.4.12 should be reformulated.  It is either impossible or prohibitively difficult to create a JIS standard that overrides these SCs.

**Comment by MakotoUeki** [comment]
@murata2makoto
> SCs 1.4.8 and 1.4.12 should be reformulated.

Your point is that any SC must not specify numeric criterion which can affect different languages. Am I right?
 
> It is either impossible or prohibitively difficult to create a JIS standard that overrides these SCs.

I think we should ask the ISO/IEC 40500 to consider these kind of language issues as well. JIS doesn't adopt WCAG directly. I'm not sure, but it might also be meaningful to reach out to the ISO/IEC working group. They may adopt WCAG 2,2 as the next version of ISO/IEC 40500.


As to the justification, Japanese text can become harder to read like [this example](http://guide.withabout.net/guide/gp332/24009/justify.html) because letter-spacings are not equal. Japanese text on the web pages are not justified in general. Are we on the same page on this point?

**Comment by murata2makoto** [comment]
> @murata2makoto
> 
> > SCs 1.4.8 and 1.4.12 should be reformulated.
> 
> Your point is that any SC must not specify numeric criterion which can affect different languages. Am I right?

Right.

> > It is either impossible or prohibitively difficult to create a JIS standard that overrides these SCs.
> 
> I think we should ask the ISO/IEC 40500 to consider these kind of language issues as well. 

In my understanding, the PAS submitter status agreement between W3C and ISO/IEC allows _no_ changes.  Even editorial ones.  ISO/IEC attaches cover pages.  That's all.

>JIS doesn't adopt WCAG directly. I'm not sure, but it might also be meaningful to reach out to the ISO/IEC working group. They may adopt WCAG 2,2 as the next version of ISO/IEC 40500. Then JIS X 8341-3 will have to follow the update.

WTO/TBT ties the hands of member countries.  For more about this, please see [this document](https://www.jisc.go.jp/jis-act/pdf/jis-seigouka.pdf), for example.  All JIS standards I have been involved in are classified as IDT (identical).  Those classified as MOD (modified) are rare.  NEQ (not equal) is basically forbidden.  Even if MOD JIS standards are created, they are very likely to be ignored by international companies.

**Comment by bruce-usab** [comment]
> Each label routes notifications about this thread to a different group of experts...

Thanks @r12a for the explanation.  I knew there was effort to keep labels consistent across repos, I had no idea adding the right labels would ping folks not otherwise tracking/subscribed to this repo.

**Comment by bruce-usab** [comment]
> SCs 1.4.8 and 1.4.12 should be reformulated.

Please be encouraged to make a suggestion as to what that might be exactly.  It is almost certainly too late for 2.2, but your recommendation could inform work on WCAG3.

**Comment by murata2makoto** [comment]
> Please be encouraged to make a suggestion as to what that might be exactly. It is almost certainly too late for 2.2, but your recommendation could inform work on WCAG3.

I will try.  I will also contact JP, CN, KR, and other W3C members before the W3C ballot starts.

**Comment by murata2makoto** [comment]
Here is my write of 1.4.12.

> In content implemented using markup languages that support the following text style properties, no loss of content or functionality occurs by adjusting all of the following appropriately and by changing no other style property.  
> 
> - Line height (line spacing),
> - Spacing following paragraphs,
> - Letter spacing (tracking), and
> - Word spacing.
> 
> Appropriate values for these style properties depend on the natural language, script, and culture among others.

**Comment by kidayasuo** [comment]
Thank you, @r12a . What you mentioned is the reason I am particularly interested in the justification. Also, in jlreq-d, I would like to include ragged right as one of the possible Japanese layouts. It is already widely accepted on the web and email, but there is opposition from people who work on traditional media such as books. It would be readily justifiable if we can find firm evidence that the ragged right is better for accessibility.

@MakotoUeki mentioned:
> As to the justification, Japanese text can become harder to read like [this example](http://guide.withabout.net/guide/gp332/24009/justify.html) because letter-spacings are not equal. [Japanese text on the web pages](https://waic.jp/docs/UNDERSTANDING-WCAG20/visual-audio-contrast-visual-presentation.html) are not justified and have an empty line to indicate a paragraph in general. Are we on the same page on this point?

Thank you. What I am looking for is a paper that backs up the impression. A history of customer feedback works also. If we lack evidence, including the requirement for Japanese would become harder to justify.

@murata2makoto , do you know if DAISY or other Japanese books formulated for people with dyslexia are justified or ragged right, and if there is feedback from customers regarding the justification?

**Comment by murata2makoto** [comment]
@kidayasuo 

>@murata2makoto , do you know if DAISY or other Japanese books formulated for people with dyslexia are justified or ragged right, and if there is feedback from customers regarding the justification?

I have not heard of any discussions about this, but all made-in-Japan DAISY readers adopt ragged right.  I will ask my DAISY colleagues.

**Comment by murata2makoto** [comment]
Will this issue be addressed before WCAG 2.2 becomes a REC?

**Comment by alastc** [comment]
> Will this issue be addressed before WCAG 2.2 becomes a REC?

Changes to WCAG 2.0/2.1 criterion were not in scope of the 2.2 update, with the exception of removing 4.1.1 which started in #770 back in 2019.

Changes to normative text for previous SCs are very difficult to get agreed, as they are then not aligned with where WCAG has been used in laws and regulations. Previously we've only done additive updates, where requirements are added but not changed/removed. That means that passing the latest version automatically passes previous versions.

The [suggested update above](https://github.com/w3c/wcag/issues/2680#issuecomment-1256354690) removes the values from the normative text, which would run into issues of backwards compatibility.

In the short term, if we can come up with what is considered the best practice for non-western languages, that could be added to the understanding document, or even a separate note.

In the longer term, I think we should look at having multiple guidelines/methods/tests for different languages.

**Comment by murata2makoto** [comment]
@alastc 

>The [suggested update above](https://github.com/w3c/wcag/issues/2680#issuecomment-1256354690) removes the values from the normative text, which would run into issues of backwards compatibility.


Can we then make clear that currently recommended values apply to Western languages only and that different values are required for non-Western languages in WCAG 2.2?

**Comment by r12a** [comment]
Or perhaps add a requirement that for non-Western languages (which probably actually means non-Latin orthographies), local adjustments should be made to typographic aspects of text based on the writing system being used?  Add to that the admonition to develop local guidelines, as suggested above.

**Comment by murata2makoto** [comment]
WCAG 2.2 will become an ISO/IEC standard and a Japanese Industrial Standard.  Having seen WCAG 2.1 did not become an ISO/IEC standard, I guess that any version beyond 2.2 is unlikely to become an ISO/IEC standard in the foreseeable future.  Thus, I very strongly want to address this issue in 2.2.  I think that I have to take any possible action to get this issue addressed before WCAG 2.2 becomes a recommendation.

**Comment by yyyug** [comment]
> WCAG aims to be applicable to all languages, although I'd note most people working on it are from western countries. It also goes through an internationalisation review process.
> 
> @MakotoUeki is probably the best person to ask how the current criteria have been applied in Japanese. There is also an [unofficial translation of WCAG 2.0 into Japanese](https://waic.jp/docs/WCAG20/Overview.html) which might have some clues.

I agree with this. Chinese commonly have line spacing of 150% to 180%. So it seems not applicable to Chinese.

**Comment by alastc** [comment]
For those who have been looking for rational, it is worth reading the links @r12a [posted above](https://github.com/w3c/wcag/issues/2680#issuecomment-1254793896), which was from the WCAG 2.1 horizontal review (the expected time to raise issues on WCAG 2.1 criteria). I scanned back and was reminded that:

- The aim of the SC is to allow for more spacing, it is not intended to say that those values are what the user must have. Users adjusting (for example) Japanese text-spacing do not have to use the values specified, they can use the most appropriate values for them. 
- From [677](https://github.com/w3c/wcag21/issues/677) we added the exception ("Human languages and scripts that do not make use of one or more of these text style properties in written text can conform using only the properties that exist for that combination of language and script.")
- From [388](https://github.com/w3c/wcag21/issues/388), the criterion does say "at least", so there is no need to reduce line height to test the condition. If a language uses larger values (e.g. line height), the SC wouldn't have any effect.

So when there are questions such as: 
> "Japanese text (and probably Chinese?) requires wider line spacing compared to English. For example, regular books for ones with normal eyesight have line spacing of around 150% to 200%."

The SC will have no effect if the value is already greater than the value from the SC. It isn't requiring an increase, or a decrease, or for the author to test at a lower value than they are already using.

Going back to the original question (coverage of languages): The aim was to provide a benefit to people with disabilities in the languages where this SC makes sense, and not harm others.

For a normative update to the SC, I think there would need to be evidence of harm to other languages. Lack of benefit for some languages was already understood. Also, this would need to apply to WCAG 2.1 as well, so we would need to apply the errata process rather than the PR process that WCAG 2.2 is currently in.

If experts in non-latin based languages can provide research and/or alternative values, that would be great. We could add that to the understanding document, or create a separate note document to provide preferred values for different languages.

However, requiring that WCAG 2.2 include different values normatively would mean an indefinite delay for something that the AG group does not have the expertise to add.

**Comment by murata2makoto** [comment]
> Also, this would need to apply to WCAG 2.1 as well, so we would need to apply the errata process rather than the PR process that WCAG 2.2 is currently in.

Is this claim backed by the W3C process?  In the ISO world, any mechanism in a new version can be revisited during the ballot.  Updating WCAG 2.1 certainly requires the errata process, but this does not imply that 2.2 has to be updated using the errata process.

**Comment by xfq** [comment]
> > "Japanese text (and probably Chinese?) requires wider line spacing compared to English. For example, regular books for ones with normal eyesight have line spacing of around 150% to 200%."
> 
> The SC will have no effect if the value is already greater than the value from the SC. It isn't requiring an increase, or a decrease, or for the author to test at a lower value than they are already using.

> Going back to the original question (coverage of languages): The aim was to provide a benefit to people with disabilities in the languages where this SC makes sense, and not harm others.

But in this case, this SC is less useful (and potentially harmful) for these writing systems, because these writing systems ​​need a larger minimum value than Latin, and if the author uses the minimum value from the SC, it may have a negative impact on the readability of the text.

**Comment by alastc** [comment]
> Is this claim backed by the W3C process? In the ISO world, any mechanism in a new version can be revisited during the ballot. Updating WCAG 2.1 certainly requires the errata process, but this does not imply that 2.2 has to be updated using the errata process.

I'm not sure, I don't think it is explicitly covered in the process. As mentioned, WCAG 2.2 has added some features, but this was not one of them. The time in the process to object to a 2.1 SC was during the 2.1 process.

> But in this case, this SC is less useful (and potentially harmful) for these writing systems, because these writing systems ​​need a larger minimum value than Latin, and if the author uses the minimum value from the SC, it may have a negative impact on the readability of the text.

Why would an author use the SC as a minimum value, unless they misunderstand the SC? 

If the value they wish to use is greater, that passes the SC. The point of the SC is that _users_ can increase the sizing, and the SC says what authors should test. If they have already tested to a greater value, there is nothing for them to do.

**Comment by murata2makoto** [comment]
@alastc 

> The time in the process to object to a 2.1 SC was during the 2.1 process.

I don't buy this argument. 

In Success Criterion 1.4.12 Text Spacing, it is required that spacing following paragraphs to at least 2 times the font size.

In Japan, no additional spacing is used between paragraphs.  Even DAISY textbooks in Japan do not have such additional spacing.

**Comment by patrickhlauke** [comment]
> In Success Criterion 1.4.12 Text Spacing, it is required that spacing following paragraphs to at least 2 times the font size.

Not quite. The SC doesn't require authors to set a specific spacing at all. The SC requires that *if* a user sets their own browser to have those particular metrics, the content doesn't get cut off or otherwise unusable/unreadable.

**Comment by murata2makoto** [comment]
>Not quite. The SC doesn't require authors to set a specific spacing at all. The SC requires that if a user sets their own browser to have those particular metrics, the content doesn't get cut off or otherwise unusable/unreadable.

Then, do some perfectly accessible fixed-layout Japanese contents become non-conformant because unnecessary space between paragraphs are required by WCAG 2.2?

**Comment by patrickhlauke** [comment]
if i understand your premise correctly, yes - a fixed-layout site that can't adapt to users setting larger spacing metrics will fail

**Comment by murata2makoto** [comment]
@patrickhlauke 

Thanks for your clarification.

**Comment by scottaohara** [comment]
We spoke about this issue during a working group call today, and I would like to suggest those who have raised concerns in this issue to provide suggestions on what might be updated in the understanding doc to make the requirements of this SC clearer.

As @alastc has mentioned in this issue, and the understanding doc already states - the SC's minimum metrics are not author requirements.  Rather what is required is that web authors don't prevent users from being able to apply these metrics through their own user styles they've applied to a web page.


In an attempt to help move this issue towards resolution, here are a few modifications to the Author Responsibility section. If there are other changes that could be helpful for the understand document, please make those suggestions so that the WG might incorporate them.  Or, if there is a specific Note that someone would like to draft for consideration, that would be very helpful.

Drafted text for potential update (new text is bold and wrapped in [[ ]] characters to help identify the changes):
>This SC does not dictate that authors must set all their content to the specified metrics, **[[nor does the SC intend to imply that all users will adjust the specified metrics]]**. Rather, it specifies that an author's content has the ability to be set to those metrics without loss of content or functionality. The author requirement is both to not interfere with a user's ability to override the author settings, and to ensure that content thus modified does not break content in the manners shown in figures 1 through 3 in Effects of Not Allowing for Spacing Override. The values in the SC are a baseline. **[[For content written in languages where the specified metrics would help increase readability]]**, authors are encouraged to surpass the values specified. **[[These metrics are not meant to represent a ceiling for authors to build to, nor as minimum requirements to adhere to, as some metrics may not even be applicable to certain languages. For example, languages such as Japanese do not use spacing following paragraphs, meaning that users won't necessarily force any paragraph spacing metrics in practice]].** If the user chooses to go beyond the metrics specified any resulting loss of content or functionality is the user's responsibility.

Feedback and additional suggestions more than welcome.

**Comment by aphillips** [comment]
Hello WCAG, I18N reviewed this issue and some investigation performed by members of our working group in our call yesterday (2023-08-10). I intend to file new issues with specific commentary/requests, mentioning this issue (so that followers of this issue can find the others easily), so that this issue does not become clogged with comments on separate threads of commentary.

Some of the above discussion is helpful. In general, we think the specification is unclear about the scope of its applicability with regard to non-Latin-script languages. There are many languages in the world that are neither Latin script nor CJK and for which non-specificity could result in issues. There are also places where reasons behind the guidance are difficult for us to guess.

Under separate cover I have contacted the WCAG chairs in hopes of arranging some joint meetings ASAP to discuss. In the meanwhile, watch for a few new issues with the `i18n-needs-resolution` label which we hope will allow for progress.

(Note: I have just seen @scottaohara's [comment](https://github.com/w3c/wcag/issues/2680#issuecomment-1675092086) just above and will respond to it separately. Perhaps copy @xfq, @r12a, and myself @aphillips on any PR to assist in reviewing wording??)

**Comment by murata2makoto** [comment]
I find that [Success Criterion 1.4.8 Visual Presentation](https://www.w3.org/TR/WCAG22/#visual-presentation) does not cover vertical writing. It mentions "width", "left", "right", and "horizontally".

**Comment by alastc** [comment]
> > The time in the process to object to a 2.1 SC was during the 2.1 process.
> 
> I don't buy this argument.
> 
> In Success Criterion 1.4.12 Text Spacing, it is required that spacing following paragraphs to at least 2 times the font size.
> 
> In Japan, no additional spacing is used between paragraphs. Even DAISY textbooks in Japan do not have such additional spacing.

In the 2.1 process we had [issue 677](https://github.com/w3c/wcag21/issues/677) on this topic, which was resolved at the time. (Well, it was on word spacing, but the same resolution would apply to all the characteristics included.) That may not be satisfactory now, but it has been in place for 5 years. (15 years for the WCAG 2.0 SC mentioned.)

We should tackle these issues in the understanding documents and potentially as errata for WCAG 2.1 and 2.2, but I'm going to ask for clarification on how it would impact the 2.2 publication process.

Now that separate issues have been raised on each item, is this issue needed?

**Comment by aphillips** [comment]
@alastc Are you saying that changes to 2.2 to address I18N's concerns is not a possible outcome?

I am mainly interested in ensuring that we collectively produce the "right" Recommendation. 

> I'm going to ask for clarification on how it would impact the 2.2 publication process.

Please include me in any clarification.

**Comment by alastc** [comment]
@aphillips I don't know, but it seems odd to have a horizontal review process, wide reviews, and then publication if it can be picked apart 5 / 15 years later.

I'm also interested in the "right" recommendation, but also by the right process. These are WCAG 2.0 / 2.1 SCs, so (IMHO) the process should be errata rather than the WCAG 2.2 PR.

**Comment by alastc** [comment]
As this has been split into multiple issues (and at @aphillips suggestion) I'll close this issue.

Overall, WCAG _aims_ to cover all languages, but there are some issues which are being picked up in different threads, and we're putting in a process for WCAG 3.0 to incorporate i18n early in the development of requirments.
