### ISSUE TITLE
Editorial - Understanding 1.4.6: Contrast Enhanced references to other standards are broken

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag#2756]
The references shown in the understanding document appear like this: [[ISO-9241-3]] and [[ANSI-HFES-100-1988]] and don't have links to a document reference like other standards references have. This used to work in WCAG 2.0, but the links /references are all broken in WCAG 2.1 and 2.2.

**Comment by fstrr** [comment]
This looks like a bug rather than a simple fix to some broken links. Note that is also is a problem in 1.4.3. @michael-n-cooper : could you look at this please?

**Comment by michael-n-cooper** [comment]
@daniel-montalvo pinged me on this. This issue is probably dangling from porting the 2.0 content. I can think of 2 ways to fix: 1) manually expand the references in the understanding file, along with a references section in files that need it and support from the generator; 2) add ability to the generator to process these references in Understanding files, so we know it's fetching the latest version.

The issue with option 2 is it's a new feature, that doesn't integrate as easily into the XSLT based generator. If we need it, I think it's doable, but would take some time. I suggest unless it's important, we take option 1. That will take a little time but a lot less. I'd like input before implementing, pinging @alastc to start.

**Comment by kfranqueiro** [comment]
I'm looking into resolving this in the new Eleventy build system. This is another instance of what's mentioned in #2535, and some instances are more resolvable than others; I'm closing this as a duplicate and will post a more detailed report there.

FWIW, this is also a problem in the version of the 2.0 Understanding Docs hosted under w3.org/WAI; it is only working under w3.org/TR/UNDERSTANDING-WCAG20.
