### ISSUE TITLE
1.4.1: Use of Color - Button border line

### ISSUE THREAD

**Issue by Ignacio-de-Loyola** [w3c/wcag#2833]
![image](https://user-images.githubusercontent.com/80868256/206328122-533a3349-51c0-45af-9499-841d85d48519.png)
As in the example above, if the brightness contrast is more than 3:1 when the error is classified only by color, can it apply under the NOTE? In other words, if it is 3:1 or higher, the difference is distinguished?

NOTE
If content is conveyed through the use of colors that differ not only in their hue, but that also have a significant difference in lightness, then this counts as an additional visual distinction, as long as the difference in relative luminance between the colors leads to a contrast ratio of 3:1 or greater. **For example, a light green and a dark red differ both by color (hue) and by lightness, so they would pass if the contrast ratio is at least 3:1**. Similarly, if content is distinguished by inverting an element's foreground and background colors, this would pass (again, assuming that the foreground and background colors have a sufficient contrast).

**Comment by JAWS-test** [comment]
When the contrast is 3:1 or more, the difference is noticeable. However, this does not fulfill the SC 1.4.1 and neither does 3.3.1. Because if the border is about an error representation, applies:
* 1.4.1: "However, if content relies on the user's ability to accurately perceive or differentiate a particular color an additional visual indicator will be required regardless of the contrast ratio between those colors. For example, knowing whether an outline is green for valid or red for invalid." (same note in the understanding, just below)
* 3.3.1: "If an [input error](https://www.w3.org/TR/WCAG21/#dfn-input-error) is automatically detected, the item that is in error is identified and the error is described to the user in text."

**Comment by JAWS-test** [comment]
See also: https://www.w3.org/WAI/WCAG21/Techniques/failures/F81

**Comment by Ignacio-de-Loyola** [comment]
If so, in what cases does the criterion of contrast 3:1 in 1.4.1 apply?

**Comment by JAWS-test** [comment]
There are very many examples. Just one: You have a toggle button. If you only convey the status difference between pressed and not pressed by color, then 3:1 contrast is sufficient.

**Comment by JAWS-test** [comment]
Or: You have links in the running text. The links stand out from the text only by color (no underlining, no different font style). In this case, 3:1 is also sufficient according to WCAG (although this is not recommended in any case, because 3:1 contrast is very difficult to see with some colors).

**Comment by Ignacio-de-Loyola** [comment]
![image](https://user-images.githubusercontent.com/80868256/206639244-4ec98ed1-2c5f-4fed-af5b-e17e36b4acde.png)
In the example, only the color provides whether the radio button is checked, is this a 1.4.1 error?

**Comment by GreggVan** [comment]
Actually  - color alone is not used in this example

The selected side has a WIDER border and a DARKER border. Neither of these is color (Hue)

So this has three indications — only one of which is color. 

gregg

———————————
Professor, University of Maryland, College Park

**Comment by JAWS-test** [comment]
Contrast of the borders of the "radio buttons" is 3,2:1  - not good but enough
