### ISSUE TITLE
Label in name SC 2.5.3: Technique in the Guise of an SC?

### ISSUE THREAD

**Issue by spanchang** [w3c/wcag#2930]
The Understanding Label In Name begins, "The intent of this Success Criterion is to ensure that the words which visually label a component are also the words associated with the component programmatically". Is this not precisely what SC 1.3.1 requires? Success Criterion 2.5.3 is merely describing a finer point of how a relationship can be made programmatically determinable. Perhaps that's why the SC text is almost identical to the sufficient techniques introduced specifically for this success criterion:
• G208: Including the text of the visible label as part of the accessible name;
• G211: Matching the accessible name to the visible label.
Consider the following:
1. ARIA8 Using aria-label for link purpose also suggests what is recommended by G208 when it says, "it is recommended to start the text used in aria-label with the text used within the link". (By the way, this should be incorporated within the test procedure for ARIA8 to make the guidance stronger and the technique more robust).
2. Should an SC describe how to make A relation programmatically determinable? Or is that not the role of the techniques supporting WCAG.X?
3. Several HTML and ARIA techniques which are not normative suggest how different elements like data tables, lists, groups of form controls etc. can be marked up in order to make content WCAG 2.X conformant without the need to author additional success criteria. 
4. The term "equivalent purpose" is not defined in WCAG 2.X and neither SC 1.1.1 Non-text Content nor the term "text alternative" mandate that text contained within an image of text must be used as the text alternative for the image. Yet technique H37 and its test procedure advises exactly that in certain situations for benefit of vision impaired users.
Why can the same logic not be used to enhance existing ARIA-label techniques instead of defining a new SC and new techniques?
5. The assumption underlying SC 2.5.3 appears to be that needs of voice input users were overlooked by WCAG 2.0. So WCAG 2.1 introduced SC 2.5.3 at Level A. However, the documentation for another success criterion, namely, Understanding SC 2.1.1, (Keyboard Accessible) has always stated unequivocally, "Keyboard emulators include speech input software, sip-and-puff software, on-screen keyboards, scanning software and a variety of assistive technologies and alternate keyboards." This statement surely suggests that the needs of voice input AT users were not unknown to or overlooked by the authors of WCAG 2.0.  
6. Employ a failure technique to promote conformance.  Failure techniques document situations that result in a transgression of a success criterion. They offer an avenue for enforcing conformance without changing normative WCAG. Therefore, the failure technique F96 (newly introduced since SC 2.5.3's addition) "Failure due to the accessible name not containing the visible label text" should instead be associated with SC 1.3.1 and perhaps SC 4.1.2. This is like other situations that result in a failure of SC 4.1.2 which are described via a failure technique like:
• F15: Failure of Success Criterion 4.1.2 due to implementing custom controls that do not use an accessibility API for the technology, or do so incompletely;
• F20: Failure of Success Criterion 1.1.1 and 4.1.2 due to not updating text alternatives when changes to non-text content occur.

Summary of recommendations:
• Enhance existing techniques for naming user interface controls with guuidance that is now part of G208 and G211
• Associate failure technique F96 with SC 1.3.1 and perhaps SC 4.1.2
• Deprecate SC 2.5.3
• Urge development teams to always pick the most appropriate technique based on the context
Thanks for your attention.
Sailesh

**Comment by JAWS-test** [comment]
> Is this not precisely what SC 1.3.1 requires? 

At 1.3.1 there is the possibility to express something with other words. Visually the button can be labeled "Empty shopping cart" and programmatically the button can be called "Delete all products in the shopping cart".

2.5.3 thus closes a gap that existed in WCAG 2.0 and should therefore not be deprecated! 

On the contrary, it can be considered whether a new SC also requires that not only the labeling matches visually and programmatically, but also the role, because speech input also works by naming the role.

**Comment by detlevhfischer** [comment]
> it can be considered whether a new SC also requires that not only the labeling matches visually and programmatically, but also the role, because speech input also works by naming the role.

This will be tricky, for example for the murky area around buttons / links (links looking like buttons and vice versa)

**Comment by patrickhlauke** [comment]
indeed, i'd really wouldn't want an SC that tries hard to then list explicitly what does/doesn't look like a button, or what looks like a tab panel, etc. and this would immediately make it invalid/illegal to do anything like styling radio controls or checkboxes as if they were switches/toggles etc ... a very big step backwards. more generally, any time we try to have an SC that tries to hang off of visual styling/presentation, it gets very difficult to write unambiguously very quickly, because visual/design is not as cut and dry (and AGWG should not be the arbiter of normatively defining "a button looks like THIS, while a link must look like THIS")

**Comment by spanchang** [comment]
@JAWS-test: It appears you did not read through  or take cognizance of the six numbered items or beyond the statement  you quoted about SC 1.3.1.
Please note,  that for the most part in my write-up I am merely referencing text and documentation authored by the WG to reason my case, highlighting what I consider to be some inconsistencies / gaps in the manner in which some techniques are written.
Thanks,
Sailesh

**Comment by JAWS-test** [comment]
@spanchang I read and understood your entire text, nevertheless have a differing opinion. Of course, the recommendations of other SCs are compliant with 2.5.3, but not because the other SCs like 1.3.1 require so, but because it is best practice. However, best practice is not normative. So I can comply with 1.3.1 without complying with 2.5.3. That is why it is good that there is 2.5.3.

**Comment by spanchang** [comment]
@JAWS-Test:
So when techniques are inappropriately applied leading to more accessibility problems, should there be more SCs to handle these issues?
Or should the technique documentation not be updated to provide clear guidance?  
That is the gap in technique description and  expected results I refer to which should not be solved by drafting more SCs.
So here is another situation: one has assigned  aria-label or title to every form control disregarding the need to apply technique H44 even when a visual label is present. In doing so a group of users loses the benefit of a larger clickable area - an accessibility feature builtin natively into label-for-id method while claiming WCAG conformance. 
You  stated the accessible name can use other words disregarding the visual label. Does the developer marking up content for accessibility have license to alter authored content as he / she pleases? 
Is it not the role of the accessibility specialist to point out which technique should be used? And advocate for its correct application?Or should more SCs be drafted to fix something which is not a problem of the guidelines but the techniques and a failure of the accessibility consultants? 
Thanks,
Sailesh

**Comment by JAWS-test** [comment]
The SCs are normative, everyone must comply with them.
The techniques are not normative, they are ways and recommendations to fulfill a SC, but:
* there are many other ways to fulfill a SC for which there is no technique.
* there are also bad ways to fulfill a SC - we should not recommend those, but when we check websites for accessibility, we have to accept those if they do not contradict the normative text of the SC.

To your example: 
If I label an input field with a label element, then the increased click area for the input field remains, even if I also label the field with aria-label. This can sometimes even be very useful, if the visible label is not sufficiently meaningful for blind users, because, for example, for sighted users the purpose of the input field is clear from the visual context, but for blind users it is not. So here an aria-label is even perfectly suitable in addition to the label element. Until WCAG 2.0, the label in the aria-label could use a different wording, but with SC 2.5.3 it is now required that the visible label must be included in the aria-label. This is good and should not be deprecated!

**Comment by spanchang** [comment]
@JAWS-Test:
Sighted voice input users are able to use the programmatically labelled visible label ... until it is undone by the introduction of the aria-label which takes precedence in the naming sequence. An ill-formed aria-label value is the result of gaps in the techniques documentation and their expected results.  
So what kind of logic or justice is this? Accessibility available through native markup (first rule of ARIA use)for one group of users is sacrificed in favor of vision impaired users by employing WAI-ARIA which is considered fashionable?
And then everyone is free to say WCAG gives greater preference to blind / vision impaired users!
So aria-describedby (if possible) or title attribute or off-screen CSS text should be used in addition to the programmatically marked up visible label to aid vision impaired users when an accessible name is already present.  

That is precisely what I am battling against: accessibility consultants fail to understand the onerous task of picking the correct technique  and educating developers whoare less informed of the implications of selecting any technique.   
This compounds the other problem: inconsistent / incomplete techniques documentation referred above.
That is why I suggested some 18 months ago the gaps in the aria-label techniques  should be addressed. See tickets 1986 (ARIA14), 1987 (ARIA6) and 1985 (ARIA8). 
Supplement that with a failure technique: see item #6 of the first post created for this issue. Developing and publishing normative text is time consuming and expensive as we all know.
Your statements thus far have only strengthened my  case. BTW I am fully aware of normative / informative  parts of WCAG.
Thanks for your comments.
Best wishes,
Sailesh

**Comment by JAWS-test** [comment]
> Sighted voice input users are able to use the programmatically labelled visible label ... until it is undone by the introduction of the aria-label which takes precedence in the naming sequence. 

That's exactly why 2.5.3 exists, to prevent this. 
Furthermore, the problem hardly ever occurs in practice, because the speech input also works when the visible label is overwritten with aria-label. The activation of the elements via speech input is possible in the cases with the visible label as well as with the aria-label label.

I think it's a principled decision whether a WCAG technique that always refers to one SC or a small number of SCs should refer to many SCs - which is your concern. I don't think that's necessarily wrong to pay attention to or refer to 2.5.3 in a technique on aria-label that refers to 4.1.2 or 1.3.1. However, if WCAG decides to do so, many techniques would have to be adapted

**Comment by alastc** [comment]
> The Understanding Label In Name begins, "The intent of this Success Criterion is to ensure that the words which visually label a component are also the words associated with the component programmatically". Is this not precisely what SC 1.3.1 requires? 

No, 1.3.1 doesn't require anything specific about the wording associated with controls.

I'm afraid that undermines the rest of the argument and recommendations in the original post. Without some basis in the normative text, that isn't a hole that can be plugged via techniques.

I can tell just from the comments above that the proposed changes would not be supported, therefore I'm going to close this issue. 

The comments above, particularly the last two from @JAWS-test include the reasoning.
