### ISSUE TITLE
2.5.8: Definition of target offset returns wrong results

### ISSUE THREAD

**Issue by JAWS-test** [w3c/wcag#2973]
[definition of target offset](https://www.w3.org/TR/WCAG22/#dfn-target-offsets):

> Two targets are horizontally aligned if a horizontal line can be drawn that goes through both targets, but no vertical line can be drawn that goes through both targets. Two targets are vertically aligned if a vertical line can be drawn that goes through both targets, but no horizontal line can be drawn that goes through both targets..

If I position two mirrored triangles side by side so that they are almost diagonal but not quite, i.e. there is a horizontal line but not a vertical one, then they may be far apart, but since I have to measure horizontally, target offset is small.

![258b1](https://user-images.githubusercontent.com/52748763/215019234-ba3e77a2-1bf1-412f-9f2f-67576cc84f06.jpg)

If I position the same triangles diagonally so that there is a horizontal and vertical line through both, I have to measure diagonally. Now I can position both triangles very close to each other, but because of the diagonal measurement target offset is much larger

![258b2](https://user-images.githubusercontent.com/52748763/215019309-4584442f-2f31-4bd2-8798-1c724a5e1f45.jpg)

Thus, I propose to return to the previous definition of target offset, since it was clearly more correct than the current one

**Comment by JAWS-test** [comment]
I also suspect that the definition is difficult to understand. In the figure, many would probably guess that the longest line of the right triangle starts at the farthest corner of the triangle. But it is the case that the longest line starts at the top corner, which appears to be closest to the left triangle. 

![258e](https://user-images.githubusercontent.com/52748763/215318234-11c18e20-75c0-4806-aaa7-7b80aef27d47.JPG)

**Comment by alastc** [comment]
Whilst true, there is a balance between complexity and simplicity.

From the previous decisions, the group was trying to make common cases (which triangles are not) easier to measure, rather than be the 'correct' metric for all cases.

This is not new information, so i don't think the decision would change.

**Comment by JAWS-test** [comment]
@alastc 

I know there was a long discussion on target offset. I think the current solution is worse than the previous ones, hence my objections.

I admit that triangles are rare as click area, but what is common are:
* objects with rounded corners
* irregular shapes in image maps

I understand that a simple solution for the most common objects (rectangles) is most important. But the current definition of target offset is unnecessarily complicated and error prone on top of that. Either complicated and correct or simple and correct in standard cases. Neither is given at the moment.
Simple would be, for example, every target is either 24x24 px or is in an area that is 24x24 px and in which no other target is located. Here 24x24 refers to square, which is not rotated.

**Comment by alastc** [comment]
Suggested response for the group to consider:

<hr>

We have tried to prioritise making common cases easier to measure, rather than be the 'correct' metric for all cases.

The main consideration is that target-offset is an exception to an already very small hit area. It only applies if the target is smaller than 24 by 24 px. The simple solution is to make the targets bigger, which would be of benefit anyway.

The more common configuration of wide and short targets is stacked, e.g. 
<img src="https://user-images.githubusercontent.com/216630/219494549-b97652aa-6211-4d28-9e28-9fe27bf31002.png" alt="A screenshot from WCAG showing the left navigation, several narrow but wide links.">

Allowing for overlapped targets and/or diagonal measures leads to odd results, which is why we made the change.

**Comment by JAWS-test** [comment]
@alastc 

> Allowing for overlapped targets and/or diagonal measures leads to odd results, which is why we made the change.

I don't think your objection applies to my proposal either:

> every target is either 24x24 px or is (partly) in an area that is 24x24 px and in which no other target is located

**Comment by alastc** [comment]
We went through a [couple of versions of that in December](https://docs.google.com/document/d/1qhh9VgBC_6HD2emkvql2Hn83iSChwlhGBs5_E9gkdEM/edit#heading=h.18485mduusn3), it has different problems, particularly with lines of links. (See 3 & 5)

**Comment by mbgower** [comment]
@JAWS-test's example of long, thin, slightly overlapping and slightly unaligned targets would be a real rarity in the wild, but if the "does not overlap" language was removed from spacing, this would pass the target offset language.
I'm still desirous of investigating whether the "overlap" language is causing more problems than it is solving.
![image](https://user-images.githubusercontent.com/14298245/220403537-577767a9-9a0a-4a2a-99d5-79c4b6d2c7f6.png)

**Comment by JAWS-test** [comment]
> do you have an example of this on an actual site?

No.

> Two very thin but long targets 'overlapping' targets that are almost aligned horizontally is a VERY unusual design decision and implementation

They can also be at the same height. I have constructed the example only so that it is visually visible that they overlap

**Comment by alastc** [comment]
The [response above](https://github.com/w3c/wcag/issues/2973#issuecomment-1433758002) was [approved](https://www.w3.org/2023/02/21-ag-minutes#item09).
