### ISSUE TITLE
2.5.8 target size should not have a "lists" exception

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wcag#3051]
This change was slipped in during the last-minute scramble to get to CR. I only noticed it recently. The current inline exception reads as follows:

> Inline: The target is in a sentence, or is in a bulleted or numbered list, or its size is otherwise constrained by the line-height of non-target text;

I think there is a legitimate reason to exempt controls inside blocks of text, as adjusting the height of those controls would increase the line-height, potentially making the text difficult to read. That argument hold for link lists though, and I feel in adding this to the exception we're doing people who need these larger targets a major disservice by this exception.

You can tell this wasn't thought out well, from how "numbered lists" are mentioned, but "lettered lists" are not. Why does this exception apply to 1. 2. 3. but not to A. B. C.?

**Comment by detlevhfischer** [comment]
@WilcoFiers I think of the sake of brevity, "numbered lists" can stand in for "lettered" lists, that is just another type of enumeration. This could be mentioned in the Understanding text. 

As to the substance: The aim was to include lists only where these are part of navigation structures, where they are nearly always used without bullet or number. When links appear in inline content in list items, possibly in the context of other list items that are unlinked, it would be weird and possibly inconsistent to demand the target height (I think that was the argument that led to the exclusion if targets in numbered / bulleted lists).

**Comment by alastc** [comment]
Hmm, don't really agree with 'slipped in' as it was discussed in the [Tuesday meeting](https://www.w3.org/2023/01/10-ag-minutes#t15) and had a [good thread on the list](https://lists.w3.org/Archives/Public/w3c-wai-gl/2023JanMar/thread.html#msg82), and was highlighted as [part of the CFC](https://lists.w3.org/Archives/Public/w3c-wai-gl/2023JanMar/0088.html).

[My comment at the time](https://lists.w3.org/Archives/Public/w3c-wai-gl/2023JanMar/0095.html) was:

We could draw a circle in a Venn diagram of everything that could be a list (in HTML terms) including navigation, images of a product, cards, description lists, as well as simple ordered/unordered lists.
That would be a large circle.

Then a second, smaller circle of things which look like bulleted & numbered lists. The overlap would be the HTML ordered/unordered lists, and the non-overlap would be paragraphs (etc) presented with bullets/numbers.

This exception is intended to cover things which are (or can be) re-flowing text because it is infeasible to include those. We are looking for something that at least correlates with main content area style lists.

If we just say “lists”, that covers things we don’t intend to cover.


> With exceptions for so many things … it might be easier to flip it all and say what IS in scope.

It is getting long, but I think flipping it would be longer. E.g.

  *   Button
  *   Text input
  *   File input
  *   Checkbox
  *   Radio button
  *   Custom select drop-downs
  *   Accordion controls
  *   Slider thumbs (depending on whether you can tap the slider bar)
  *   Spin buttons
  *   Switches
  *   Tabs

Some of those we could group as ‘buttons’, but I’ve probably also missed some from a quick scan of HTML & ARIA controls.

I think we’re better off saying “targets” with some known exceptions, rather than the other way around.

Also, I agree with Detlev that we can generalise the 'numbered' aspect, that fits common sense. Unless there's a general work for numbered and / or lettered?

**Comment by yatil** [comment]
Why not “unordered list” and “ordered list”? That fits into the mental model of many people who are using these guidelines. Otherwise, you always have to use both terms, which gets confusing,

**Comment by alastc** [comment]
I think order/unordered gets you back to thinking about the underlying HTML, rather than the presentation of the text.

Unordered lists have been applied to just about everything. (Remember VoicerOver's heuristic about not announcing lists unless they were styled as lists?)

**Comment by mbgower** [comment]
I would suggest "enumerated" instead of "numbered" as a possible clarification on intent. I had understood we were trying to tackle things that have a symbol or character in front of the listed items, which is very common in body text but highly unusual in navigation.

**Comment by alastc** [comment]
From the WCAG 2.x meeting, suggest we create a PR which is:
- Changing the text to say "enumerated".
- Update understanding doc to say that means things which have a number, letter or numeral.

**Comment by mbgower** [comment]
@WilcoFiers please see #3084
