### ISSUE TITLE
Does a failure of 3.2.2 automatically fail 2.4.3?

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag#3111]
If focus is unexpectedly removed from a control when changing the setting of it that would trigger a 3.2.2 failure, but does that also fail 2.4.3 and why?

**Comment by yatil** [comment]
> **For Reference, here are the mentioned SCs to allow people who have not internalized the numbers to follow:**
> * [SC 3.2.2 On Input](https://www.w3.org/TR/WCAG21/#on-input)
> * [SC 2.4.3 Focus Order](https://www.w3.org/TR/WCAG21/#focus-order)

IMHO, removing an element with focus on input has no direct effect on being able to navigate sequentially the then-existing content.

**Comment by patrickhlauke** [comment]
we (as in me in my last two auditing jobs) have traditionally filed some issues related to "focus isn't correctly managed even following an interaction" under 2.4.3 Focus Order, so I can see the relationship here. it's one of those "cascade of fail" i think, where you need to make a decision if you want to fail every. single. criterion. that. fails... or just file against the root cause and stop there/mention it in passing ("btw this also fails X, but once you fix this, you'll resolve that part as well").

**Comment by anevins12** [comment]
The effect doesn’t have to be made through sequential navigation. That’s
the precondition to the applicability of the criterion. The bit you want to
test is,  “focusable components receive focus in an order that preserves
meaning and operability”

**Comment by anevins12** [comment]
Also thanks for writing out the names of the criteria.
