### ISSUE TITLE
Understanding 3.3.2 Labels or Instructions

### ISSUE THREAD

**Issue by TheUntamed** [w3c/wcag#3141]
I'm trying to find out what is necessary to fulfill this criteria.

I already read some of the other posts here: #864 and #1136

A standard placeholder is not sufficient, but in my case I use Angular Frontend Framework and placeholder text here is pushed upwards above the input instead of being hidden when the user enters text.
Would that already be sufficient?

I also read: https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions on the website and under "Sufficient Techniques" it states: "Providing descriptive labels AND one of the aria-labelledby, aria-describedby, etc" is required to fulfill this criteria. Now I wonder if I need two things and what counts as "descriptive label" and why aria-labelledby or aria-describedby would not be enough.

**Comment by scottaohara** [comment]
if the 'placeholder text' is moved above the input when someone enters text, then that's not placeholder text.  but a label that was positioned atop the input.

Regarding your mention of the sufficient techniques section, you're adding requirements (let alone the word requirement) which are not present.  Rather, the section above your sort of quoted text states (emphasis mine):

>Each numbered item in this section represents a technique or combination of techniques that the WCAG Working Group deems sufficient for meeting this Success Criterion. **However, it is not necessary to use these particular techniques.**

The understanding states (paraphrased) that one can provide labels and instructions and meet the requirements of this criterion, but fail others if the labels and instructions are not appropriately marked up.  For instance 1.3.1 or 4.1.2.   This is where _one way_ to ensure you don't fail those other requirements is to use aria-labelledby or aria-describedby - if those are actually appropriate for your use case.  And, even if it was appropriately marked up - regarding a ''descriptive label' that's why 2.4.6 Headings and Labels is called out.  As if you have a text field that expects someone's first and last name, but the visible / programmatically associated label would lead one to believe they should enter something different, then that's why aria-labelledby wouldn't be enough.

**Comment by detlevhfischer** [comment]
3.3.2 is about the availability of visual labels. This is why placeholder alone would fail since it is not permanently available (disappears during input). If the label floats up when the field gets focus, you would meet 3.3.2 (but you may still fail other Success Criteria like 1.3.1 Info and Relationships or 2.5.3 Label in name).
