### ISSUE TITLE
Broken link on Understanding SC 1.3.5 page

### ISSUE THREAD

**Issue by bounteous-sadia** [w3c/wcag#3204]
On https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose, the link [Input Purposes for user interface components section](https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html#input-purposes) is broken, and should reference instead https://www.w3.org/TR/WCAG21/#input-purposes.

**Comment by alastc** [comment]
The link from the SC text needs to be fixed in the templates.

@michael-n-cooper this could be a problem with all understanding docs? I checked [1.3.5](https://w3c.github.io/wcag/understanding/identify-input-purpose.html#input-purposes) and then a few others, it only seems to be this link for this SC.
