### ISSUE TITLE
Is 2.5.3 Label in Name not applicable where the accName is not present?

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag#3374]
Hello!

If a control contains a visible label but the accessible name is empty, or in other words there is no text in the accessible name, is success criterion 2.5.3 Label in Name not applicable?

[The definition of "name"](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#dfn-name) in this criterion is "text by which software can identify a component within Web content to the user." 

[The definition of "text"](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#dfn-text) in this criterion is "sequence of characters that can be [programmatically determined](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#dfn-programmatically-determined), where the sequence is expressing something in [human language](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html#dfn-human-language)

If 2.5.3 Label is Name is applicable, is that because it's in the spirit of the criterion and that overrules the definition of "Name"?

**Comment by patrickhlauke** [comment]
if the control/element doesn't have an accName, it doesn't have a name, no? 2.5.3 auto-fails since then it can never be true that "the [name](https://www.w3.org/TR/WCAG21/#dfn-name) contains the text that is presented visually."

there is no "name" - nothing can be *programmatically determined* for that control (unless you dive into heuristics a la "maybe the text just before the control could potentially be the name", at which point you're in "desperate error correction done by AT to try and patch broken/incomplete markup")

**Comment by anevins12** [comment]
Right, thanks Patrick. I was misreading the definition.

**Comment by awkawk** [comment]
@patrickhlauke I'd say that for the three main cases:
1. Control with an image/icon showing what the button is for (e.g., a button with a pair of scissors on it to indicate "cut").
If the icon doesn't have text to serve as an alternative, then 2.5.3 doesn't apply since there is no text in the icon (in my scissor example, so the name (which would be null in this case, and a 1.1.1 issue) does include all text that is presented visually. 

2. Control with text on it (e.g., GitHub's "new issue" button).
A button with text on it meets this by default. The accName is set by the text on the button unless there is a higher-priority accName source.

3. Control with text label (e.g., "first name" preceding text and a text input). The control is labeled visually but the accName is null unless there is proper association with the preceding text or there is an aria-label/etc. So, the label is present and includes text, and that text isn't part of the accName and 2.5.3 fails.

@anevins12 Not sure if you are thinking about a different scenario or if this helps.

**Comment by patrickhlauke** [comment]
@awkawk the way I understood @anevins12 question was that it referred to case 3 here

**Comment by patrickhlauke** [comment]
@davidofyork pointed me to https://github.com/w3c/wcag/issues/2045 ... which actually has a follow-up PR by yours truly to clarify this exact scenario (3). would be good if this PR from 2021 could be considered/merged at some point to avoid confusion https://github.com/w3c/wcag/pull/2057
