### ISSUE TITLE
Inconsistent capitalization of "web" in text

### ISSUE THREAD

**Issue by joanlambert** [w3c/wcag#3393]
The word "web" when used outside of proper names is sometimes lowercase and sometimes uppercase. Current style guidelines (since 2016) specify that "web" should be lowercase outside of references to the World Wide Web (the Web) and proper names such as "Web Content Accessibility Guidelines" and "World Wide Web Consortium".

Errors are throughout, but here is an example, from the first paragraph of the abstract:
> Web Content Accessibility Guidelines (WCAG) 2.2 covers a wide range of recommendations for making **Web content** more accessible. Following these guidelines will make content more accessible to a wider range of people with disabilities, including accommodations for blindness and low vision, deafness and hearing loss, limited movement, speech disabilities, photosensitivity, and combinations of these, and some accommodation for learning disabilities and cognitive limitations; but will not address every user need for people with these disabilities. These guidelines address accessibility of **web content** on desktops, laptops, tablets, and mobile devices. Following these guidelines will also often make **Web content** more usable to users in general.

**Comment by awkawk** [comment]
The W3C style is at https://www.w3.org/Guide/manual-of-style/

Agree that it should be consistent. There are 143 mentions of "web" or "Web" and ~20 are "web" (and only one "webpage" as a single word). We used the capitalized version since it is one of the suggested styles and to be consistent with WCAG 2.0 - but apparently not completely.

From the style guide:
Web (on its own)
always capitalize

Web (as part of a phrase)
Either capitalize or lower case "Web" (e.g., Web developer or web developer, Web project or web project, Web page or web page, Web application or web application

**Comment by joanlambert** [comment]
I'd respectfully request that you consider updating or versioning the style guide to match current guidance. The industry standard changed approximately six years ago and is in use by all major organizations I've worked with.

Here is one reference that also includes designation of one- and two-word variations to support this:
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/web-world-wide-web-www

Joan Lambert
Accessibility Manager, Product Experience
Pearson VUE Accessibility
________________________________

**Comment by awkawk** [comment]
We aren't the maintainers of the W3C's style guide, but the W3C did maintain (as the organization created by and led by the guy who invented the Web/web) that Web was a proper noun for a long time. 

There is an email on the W3C Style Guide that would be a better place to comment.
