### ISSUE TITLE
How prescriptive are the ARIA patterns? Can keyboard support be filed under F15?

### ISSUE THREAD

**Issue by kimviens** [w3c/wcag#3516]
For a while now, I have been filing issues under 4.1.2 Name, Role, Value for components that use ARIA but do not correctly implement the keyboard support as described in the [ARIA Patterns](https://www.w3.org/WAI/ARIA/apg/patterns/). In my eyes, not having the proper keyboard support means [failing to implementing custom controls that do not use an accessibility API for the technology, or do so incompletely](https://www.w3.org/WAI/WCAG22/Techniques/failures/F15). I do not file it under 2.1.1 Keyboard because the component is usable, its just weird.

A client of mine made me think that I might be filing these issues wrong. They pointed out that their website includes support documents that teaches users on how to use custom components such as their comboboxes.

Should authors follow the [ARIA Patterns](https://www.w3.org/WAI/ARIA/apg/patterns/)? Am I right to file issues with this kind of keyboard support under 4.1.2 Name, Role, Value?

**Comment by JAWS-test** [comment]
> you can't file an issue under a technique...

If a failure occurs in an application exactly as described in a Failure technique , then it can be filed under the WCAG SC to which the Failure technique belongs. F15 belongs to SC 4.1.2, insofar an error as described in F15 can be considered as a violation of 4.1.2

> 4.1.2 doesn't mandate anything here either.

That's debatable, I think. SC 4.1.2 requires the transmission of a correct role.
* A correct role is important so that the element can be operated with AT. If e.g. the implemented keyboard operation prevents that the element can be operated with AT, it is clearly a violation of 4.1.2.
* A correct role is important so that the AT user knows how to operate the element with the keyboard. In this respect, it can be argued that keyboard operation that does not match the role is a violation of 4.1.2. However, there is unfortunately no guidance for this in the Understanding and Techniques for 4.1.2, so I suspect that most will object to including such issues under 4.1.2. If they don't belong to 2.1.1 either, then WCAG has a gap here.

**Comment by JAWS-test** [comment]
Related: 
* https://github.com/w3c/wcag/issues/878
* https://github.com/w3c/wcag/issues/872

**Comment by kimviens** [comment]
Sorry, I meant that I filed under 4.1.2 and I reference F15.

**Comment by kimviens** [comment]
So if I understand correctly what you are meaning, and from the linked conversations. The most current state of this conversation (what to do with non-standard keyboard operation):

- Its a best practice to implement standard keyboard operations but not a failure. WCAG does not cover this.

**Comment by JAWS-test** [comment]
> Its a best practice to implement standard keyboard operations but not a failure. WCAG does not cover this.

Yes, unfortunately the WCAG does not regulate keyboard operation more. With the exception I mentioned that a non-functioning keyboard operation for technical reasons (e.g. screen reader does not switch to form mode due to wrong role, so that arrow key operation of a widget is not possible), is in my opinion a violation of 4.1.2.
