### ISSUE TITLE
Technique H71: Wording for Legend in fieldset suggests the legend is mandatory

### ISSUE THREAD

**Issue by LaurenceRLewis** [w3c/wcag#3526]
Technique H71 has the sentence "_The first element inside the fieldset **must** be a legend element, which provides a label or description for the group._"
[Technique H71: Providing a description for groups of form controls using fieldset and legend elements](https://www.w3.org/WAI/WCAG21/Techniques/html/H71#:~:text=The%20first%20element%20inside%20the%20fieldset%20must%20be%20a%20legend%20element)

The HTML Living Standard - [4.10.15 The fieldset](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element) element states "Content model: **Optionally** a legend element, followed by flow content."

If must is used it is only if the Legend exists. The wording should change to reflect this or change must to should.

**Comment by awkawk** [comment]
Since the technique is to show how using the fieldset and legend to label a grouped set of controls, I would agree that must is appropriate for the technique. In the procedure, if you don't have a legend then you would fail to meet this technique (although you might meet the SC using a different technique).

**Comment by LaurenceRLewis** [comment]
Thanks @awkawk It just struck me as wrong reading the sentence, however did not consider the bigger picture. I'll close the issue.
