### ISSUE TITLE
What is the difference between a Menu button and a combo box?

### ISSUE THREAD

**Issue by ManojG-Ally** [w3c/wcag#3541]
An element with static label text as "Filter By" and adjacent to it a dropdown with options such as "Date" and "Time"

Is this a Menu button or a combo box? And Can the label of the element be used to identify whether it's a combo box or not?

Lastly, when we have a visible label text but it is not being exposed to the screen reader users- Do we ask for a complete markup change even though the menu button is working well?

**Comment by JAWS-test** [comment]
There are two important differences:

First
* combobox: can have label and value
* menubutton: has only a label

In addition:
* combobox: is a form element, should be used in a form to select a value that is submitted when the form is submitted. Should not be used directly for an action
* menubutton: A button directly triggers an action, is not used to submit a value within a form.

Otherwise combobox and menubutton are very similar. If the menu button has a label that is not in the button, it must be referenced using aria-labelledby (and to the label in the menu button so that both pieces of information can be perceived by screen readers). But this is only a workaround. It would be better to use a combobox

**Comment by bruce-usab** [comment]
@ManojG-Ally please close this issue if you are satisfied with the answer provided.

**Comment by bruce-usab** [comment]
@ManojG-Ally thank you for your interest in accessibility and for closing this issue.
