### ISSUE TITLE
Broken link/need for updated reference on Understanding: Non-text contrast

### ISSUE THREAD

**Issue by matt-t-tinkers** [w3c/wcag#3561]
On the [understanding doc for Non-text contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast), **Figure 10** has a broken link to Focus Appearnace (https://www.w3.org/WAI/WCAG22/22/focus-appearance-minimum.html). 

Also, as Focus Appearance (minimum) is a checkpoint for achieving AAA, it would be particularly useful for clearer guidance how around having a thicker line can pass this checkpoint at AA.

**Comment by mbgower** [comment]
@matt-t-tinkers, originally there were AA and AAA criteria for Focus Appearance, but these were combined into a single AAA criterion due to some difficulties with consistent testing and interpretation.
That [Understanding](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html) document provides good guidance on improving the visibility of focus indicators, regardless of the level of WCAG you are targetting. We will fix the broken URL.

Does that answer you question?
