### ISSUE TITLE
correct WCAG 2.1 -> WCAG 2.2

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wcag#3585]
In https://www.w3.org/WAI/WCAG22/Understanding/refer-to-wcag

**Comment by patrickhlauke** [comment]
Also in most other non-SC-specific docs:

* https://www.w3.org/WAI/WCAG22/Understanding/intro
* https://www.w3.org/WAI/WCAG22/Understanding/
* https://www.w3.org/WAI/WCAG22/Understanding/documenting-accessibility-support
* https://www.w3.org/WAI/WCAG22/Understanding/understanding-metadata

I suspect the cause of this is that the same file may be used to also generate WCAG 2.1's understanding?

I'm fairly sure at some point I suggested just dropping version numbers from those files altogether, so it's a bit more evergreen (i.e. just refer to "WCAG" rather than a specific "WCAG 2.1", "WCAG 2.2", etc unless that number is needed explicitly)

**Comment by patrickhlauke** [comment]
related, on https://www.w3.org/WAI/WCAG22/Understanding/about there's a "Change log"

> A list of significantly updated Understanding documents since WCAG 2.1 was published:

which is woefully pointless since it only lists one change

> Jan 18th 2019: Updated [Understanding Non-text contrast](https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast), based on the changes from [Pull request 550](https://github.com/w3c/wcag/pull/550).

as this is clearly not something that will realistically be kept up-to-date, suggest just pulling that entire section

**Comment by patrickhlauke** [comment]
For info, filed https://github.com/w3c/wcag/pull/3588 (which may or may not be controversial, we'll see)

**Comment by mbgower** [comment]
Removing from project board, since we are now tracking via the PR that resolves.
