### ISSUE TITLE
Understanding SC 1.4.1: Use of Color: Broken link

### ISSUE THREAD

**Issue by yjlucyh** [w3c/wcag#3611]
Page: [Understanding SC 1.4.1: Use of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color)

Issue: The [Guideline 1.3](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color#adaptable), in the Success Criterion (SC) section on the top is a broken link.

**Comment by patrickhlauke** [comment]
@iadawn this is another case of those "if there's a link in the notes for the SC, the links then break when they're added in understanding docs". there's a few other issues reported about similar cases. is this something that could be fixed at build time for the understanding docs? i'd envisage something like "don't just put the SC (and its notes) in here, but also check if there's any relative/in-page links with `href="# ..."` and if so, rewrite them". problem of course will be to rewrite them/send them to the correct version of WCAG

**Comment by iadawn** [comment]
This issue references the Understanding documents for 2.1. Those have republished since June 2023. I suspect I made a mistake in the build process when publishing at that time.

I could republish now and this would address the issue. But it would include changes since June in the Understanding docs... including the In Brief sections.

@alastc any problems with doing a republish of 2.1 Techniques and Understanding?

**Comment by iadawn** [comment]
This isn't a problem with my build... and the problem also exists in:

* [non-text-content](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html)
* [pause-stop-hide](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html)
* [sensory-characteristics](https://www.w3.org/WAI/WCAG21/Understanding/sensory-characteristics.html)

Will need to have more of a look at how to address this.

**Comment by iadawn** [comment]
I *think* I have fixed this. Closing,  but feel free to open if you spot issues related to links in notes or SC details
