### ISSUE TITLE
Should it be "Audio Description" instead of "Video Description" in first Note under Intent section of Understanding SC 1.2.1

### ISSUE THREAD

**Issue by sidnc86** [w3c/wcag#3621]
In the [Understanding 1.2.1](https://www.w3.org/WAI/WCAG22/Understanding/audio-only-and-video-only-prerecorded.html) page, under the Intent section, after couple of paragraphs, first Note appears that states following:

In content pasted below, I've marked the text that needs to be replaced with double parenthesis.
Note
A text equivalent is not required for audio that is provided as an equivalent for video with no audio information. For example, it is not required to caption ((video)) description that is provided as an alternative to a silent movie.

Should the "video description" be replaced with "audio description" instead?

The explanation before the example states that captions aren't needed for audio description present as an alternative for video-only content. In the example though, we are mentioning just captions for video description of silent movie without making mention of audio description of silent movie.

**Comment by cstrobbe** [comment]
That depends on how consistent the Understanding documents need to be. The [definition of audio description](https://www.w3.org/TR/WCAG22/#dfn-audio-descriptions) points out that "video description" and "descriptive narration" are used as synonyms for "audio description". Since there is no link to the above definition in Understanding 1.2.1 and the "audio description" is not listed under "Key Terms", this would be a sensible editorial change.
