### ISSUE TITLE
Does SC 1.2.1 require the alternative for time-based media for video-only to be visible?

### ISSUE THREAD

**Issue by kengdoj** [w3c/wcag#3642]
Hello, 

This question originates from [ACT Rules Issue 1815: Should the text alternative for a video without audio always be visually present?](https://github.com/act-rules/act-rules.github.io/issues/1815)

For reference:

> SC 1.2.1: Prerecorded Video-only
> Either an alternative for time-based media or an audio track is provided that presents equivalent information for prerecorded video-only content.

> [alternative for time-based media](https://www.w3.org/WAI/WCAG22/Understanding/audio-only-and-video-only-prerecorded.html#dfn-alternative-for-time-based-media)
> document including correctly sequenced text descriptions of time-based visual and auditory information and providing a means for achieving the outcomes of any time-based interaction

**Comment by dav-idc** [comment]
Some personal thought that might help? Potentially not.

The alternative for time-based media, when it's in the form of a text transcript is sometimes offered on a separate page or as a separate document, and linked to near the video.

In that case, the alternative is definitely not 'visible' near the video if visibility is interpreted as "can be observed visually".

But, once the transcript is accessed, wherever it lives, I would think that it needs to be available visibly. 

So:
- no, the video alternative doesn't need to be physically visible on the same page as the video
- yes, wherever the video alternative lives it should be available visibly

**Comment by patrickhlauke** [comment]
I'd say, more generally: since for images / non-text content in general, having something like `alt` which is only exposed to AT is an acceptable way to pass 1.1.1, it would logically follow that for video, having an alternative that is only exposed to AT (i.e. not visible in the page, or linked out, or otherwise accessible separately) is a valid way to pass 1.2.1 as well

**Comment by mraccess77** [comment]
The same argument to put things off-screen could be applied to other criteria as well but it's not the intent of the criteria in my opinion.

Putting it another way- for 1.2.1 - an audio file could have off-screen text as the transcript used by people who are deaf or hard of hearing? That wouldn't be acceptable? The flip side is why would low vision folks be excluded from having visible alternative for video only content?

**Comment by patrickhlauke** [comment]
>  The flip side is why would low vision folks be excluded from having visible alternative for video only content?

why should they be excluded from having visible alternative for `<img>` elements? and yet that's kosher under 1.1.1

**Comment by mraccess77** [comment]
I think the different between an image with alt and a media alternative is the length of it.  A media alternative is defined as a document.

**Comment by dav-idc** [comment]
>So due that for alternative for image there is a specific attribute (that can be catched by AT), for transcript or description there are no specific attributes so IMHO shall be percepible not only by people that cannot see video.

I definitely agree that image text alternatives aren't a one-to-one comparison with multimedia text alternatives. 

Text alternative for multimedia (like a transcript) doesn't match well to something like alt text, due to the potential length of the transcript. Having a transcript read out the same way as alt text gets read out by screen readers would be pretty disastrous, as alt text is read out all at once. For an hour long piece of multimedia, there's the potential for several hundred lines of transcript material.

**Comment by rscano** [comment]
> Text alternative for multimedia (like a transcript) doesn't match well to something like alt text, due to the potential length of the transcript. Having a transcript read out the same way as alt text gets read out by screen readers would be pretty disastrous, as alt text is read out all at once. For an hour long piece of multimedia, there's the potential for several hundred lines of transcript material.

We are talking about video-only, not multimedia contents. For multimedia there are usually captions and audio-descriptions.

**Comment by dav-idc** [comment]
> We are talking about video-only, not multimedia contents.

Thanks for the note, I definitely missed that distinction. My bad there!

**Comment by bruce-usab** [comment]
Trying to summarize this thread:
- Yes, text alternative for video-only must be visible to satisfy 1.2.1.
- Caveat is that the text alternative might not be on the same page, but then the UIC for the text alternative would need to be visible.

Please thumbs up, or thumbs down with comment to continue the discussion.

**Comment by dbjorge** [comment]
I think we should be a bit more precise with the terminology. Normatively, "**text alternative**" (as used by 1.1.1) and "**alternative for time-based media**" (as used by 1.2.1) are not (necessarily) the same thing.

For prerecorded video-only time-based media that:
- Doesn't have any associated audio track,
- Isn't a clearly-labelled media alternative for text, and
- Doesn't meet 1.1.1's "Decoration, Formatting, Invisible" exception

... I would interpret the combination of the two SCs like this:

- Authors must provide **both** a "text alternative" (per 1.1.1) **and** an "alternative for time-based media" (per 1.2.1).
- Per 1.2.1, the "**alternative for time-based media**":
    - Must be "provided" somehow (for all users)
        - This implies that it must be visible in order for it to be considered as "provided" to visual users
    - Does not need to be on the same page (I think this is implied by the definition calling it a "document")
        - ...but if it is not, it still must be "provided" (for all users), which would require a visible mechanism providing it
    - Does not need to meet the "programmatically associated" requirements from the "text alternative" definition
        - ...but must be "provided" to AT users somehow, so should be reasonably discoverable
    - Must provide "equivalent information" to the media
    - Must meet the completeness requirements specified by the "**alternative for time-based media**" definition (correct sequencing, etc)
- Per 1.1.1, the "**text alternative**":
    - Must meet the usual requirements from the text alternative definition (especially with regard to being programmatically associated)
        - Per the usual text alternative requirements, does not need to be visible (eg, an `aria-label` would be an acceptable means of providing a text alternative for a `<video>` element)
    - Must "at least provide descriptive identification of the media"
    - Does not need to provide "equivalent information" to the media (but would be allowed to do so)
- The two types of alternative **may** be implemented by the same mechanism, provided it meets all the requirements of both SCs/definitions.
    - eg, an `aria-labelledby` on a `<video>` element which points to a visible text description that provides "equivalent information" to the video
    - Although this is normatively allowed, it is only *recommended* when the "alternative for time-based media" is short and simple. If more than a sentence or two is required, best practice would be to use a separate shorter **text alternative** in addition to a more complete **alternative for time-based media**.

**Comment by bruce-usab** [comment]
Good catch @dbjorge as the context is 1.2.1 and alternative for time-based media.  With the context of the [original question](https://github.com/act-rules/act-rules.github.io/issues/1815#issuecomment-1919580801), I do not agree that 1.2.1 is even applicable.  I would prefer a better real-world example of invisible text used as the alternative for time time-based media, as I am skeptical that it happens.

**Comment by dbjorge** [comment]
> With the context of the https://github.com/act-rules/act-rules.github.io/issues/1815#issuecomment-1919580801, I do not agree that 1.2.1 is even applicable.

Can you explain why you think 1.2.1 wouldn't be applicable to that example? You talked in [this comment](https://github.com/act-rules/act-rules.github.io/issues/1815#issuecomment-1919580801) about the possibility of that example being a "pure decoration", but even if that *was* the case for the example in question, that would only exempt it from 1.1.1, not 1.2.1.

**Comment by WilcoFiers** [comment]
This one surprised me. I very much thought this was required, but thinking through it carefully, I think there is one pretty glaring problem with this; Animated gifs. If 1.2.1 required visible alternatives, then 1. either animated gifs need a visible alternative, or 2. something about animated gifs would make not quality as "video-only" content.

1. It seems generally acceptable that animated gifs can pass WCAG with an alt attribute. I also can't really think of what the benefit for someone with a disability would be. Granted there is the case where some people struggle to process things like social cues from images, but that's as true for still images as it is for short video clips, and it isn't required for still images. So that doesn't seem right.

2. Maybe animated gifs aren't "video-only" content. Looking at the definition of video-only I can't think of an argument for why that might be true. They are a "time-based presentation that contains only video", with video being "the technology of moving or sequenced pictures or images".

**Comment by dbjorge** [comment]
> I very much thought this was required, but thinking through it carefully, I think there is one pretty glaring problem with this; Animated gifs.

I agree - I think normatively 1.2.1 requires visually presented descriptions of animated gifs, which surprises me and strikes me as possibly-unintended.

**Comment by cliffbert** [comment]
Perhaps animated gifs should be treated _according to whether the animations provide information_. If so, we treat them as video-only content. If not, they can be considered images, and sometimes decorative?

e.g. a gif of a car changing colors or driving on a highway - the animations would not provide essential information. But a gif of a car taking a particular route to a restaurant - highway I90, exit 12, left on Bucky Blvd - would be treated per 1.2.1.

**Comment by WilcoFiers** [comment]
@dbjorge I don't think I agree with your conclusion that "provided" means "to all users". 1.2.2 says captions need to be provided. I don't think that means captions need to be accessible to screen readers.

**Comment by dbjorge** [comment]
> @dbjorge I don't think I agree with your conclusion that "provided" means "to all users". 1.2.2 says captions need to be provided. I don't think that means captions need to be accessible to screen readers.

In the case of captions specifically, the "captions" definition explicitly says "visual and/or text alternative" - I think that's the mechanism by which captions are allowed to be visual without a text alternative.

I looked around for other cases where we use "provides" or "provided" in SC text without that sort of qualification and clarify the scope/interpretation in an understanding doc. Some cases are as ambiguous as this one is (eg, 3.3.3), but 3.3.2 is a good example where the SC uses similar language ("Labels or instructions are provided when content requires user input") and [its understanding doc](https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html) clarifies explicitly that our interpretation is that this wording means labels and instructions must be "presented to all users, not just those using assistive technologies." (see 4th paragraph of Intent section)

**Comment by mraccess77** [comment]
> @dbjorge I don't think I agree with your conclusion that "provided" means "to all users". 1.2.2 says captions need to be provided. I don't think that means captions need to be accessible to screen readers.

Since WCAG allows for open captions this may be the case - but captions that are not accessible to screen readers will not be available to people who are deafblind and need them in braille - so this is something should be addressed in WCAG 3.

**Comment by bruce-usab** [comment]
I realize that an appeal to consequences is a logical fallacy, but it cannot be the case that WCAG conformance requires that all animated gifs have an [alternative for time based media](https://www.w3.org/TR/WCAG22/#dfn-alternative-for-time-based-media).

From 1.1.1, emphasis added:
> If non-text content is time-based media, then text alternatives **_at least_ provide descriptive identification** of the non-text content. (Refer to Guideline 1.2 for additional requirements for media.)

If the text alternative provided to meet 1.1.1 <q>serves the equivalent purpose</q> (as the non-text content) it follows that this text is sufficient to also meet 1.2.1.

A text alternative that serves the equivalent purpose is more than what 1.2.1 requires, which is merely <q>text descriptions of time-based visual &hellip; information</q>.  Text equivalents are _better_ than text descriptions.

> Does SC 1.2.1 require the alternative for time-based media for video-only to be visible?

No.  The adjective of <q>visible</q> is not part of that portion of the SC, and not part of the definitions for text, text alternative, nor alternative for time-based media.

**Comment by GreggVan** [comment]
BRUCE, I see the problem you're trying to solve. But I don't follow your logic. According to this, I could just provide a descriptive identification for a movie and it would automatically meet 1.2.1.

There is nothing about the statement in 1.1.1 that says that providing a descriptive identifier"serves equivalent purpose". It only says that you at least need to do that for 1.1.1 knowing that 1.2.1 will be following and require more. And meeting One success criteria of course doesn't mean that all other related success criteria are met.

Having said that, I see the problem you're trying to solve, and, we should try to figure out how to do it. But I don't see how your current logic works without opening up a Pandora's box of unintended consequences for longer clips. Unfortunately, we don't have anything here about the length of the material and I think that is what you're trying to address

Comment back if I'm missing something...

**Comment by bruce-usab** [comment]
> According to this, I could just provide a descriptive identification for a movie and it would automatically meet 1.2.1.

No, descriptive identification is the minimum requirement for not providing a text alternative that serves the equivalent purpose of the the non-text content.

> There is nothing about the statement in 1.1.1 that says that providing a descriptive identifier "serves equivalent purpose".

I concur completely that descriptive identification is not serving the the equivalent purpose.

> Unfortunately, we don't have anything here about the length of the material and I think that is what you're trying to address

@mraccess77 also suggested length of the video might be the trigger for requiring something like a screen play versus something like alt text.  I don't disagree with the practicality of the approach, but its not supported by the normative text.  It is also possible for a few seconds of video-only media to convey a significant amount of information!  This is why I am making the case to assess the quality of the text alternative provided for meeting 1.1.1.  If that text alternative is only providing descriptive identification, that meets 1.1.1 but _not_ 1.2.1.  If that text alternative serves the equivalent purpose, that meets _both_ 1.1.1 _and_ 1.2.1.

**Comment by bruce-usab** [comment]
Getting back to a couple of @dbjorge points:

> ....but even if that _was_ the case for the example in question, that would only exempt it from 1.1.1, not 1.2.1.

I am sure you agree that [pure decoration](https://www.w3.org/TR/WCAG22/#dfn-pure-decoration) is written so that it can be applied to non-text content other than images.  I recognize it is not an exemption within normative phrasing of 1.2, but there are other situations where auditors have to make inference and use common sense.  I am optimistic we might arrive at something that can be added to Understanding without contradicting normative phrasing.
 
> even for 1.1.1, I think the normative text there is actually a bit ambiguous about what the requirement is for something that meets _multiple_ of the special scenarios simultaneously, like a purely decorative video would - I presume the intent is for the "decorative" requirement to take priority, but I don't think that's actually well-specified in the SC.

Agreed on both points.  When I teach 1.1.1, I focus on descriptive identification versus text that serves the equivalent purpose.  Pure decoration is interesting since null alt _is_ the equivalent purpose.  There are also many situations were descriptive identification _is_ the text equivalent.  But that kind of nuance is not part of "wcag 101"!

**Comment by bruce-usab** [comment]
Taking a fresh crack towards proposed response...

From [SC 1.2.1](https://www.w3.org/TR/WCAG22/#audio-only-and-video-only-prerecorded):
> **Prerecorded Video-only:** Either an alternative for time-based media or an audio track is provided that presents equivalent information for prerecorded video-only content.

The definition for [alternative for time-based media](https://www.w3.org/TR/WCAG22/#dfn-alternative-for-time-based-media) (emphasis added):
> document including **correctly sequenced text descriptions** of time-based visual and auditory information and providing a means for achieving the outcomes of any time-based interaction

I am glossing over "document" to focus on "correctly sequenced text descriptions" which is just qualifying that the words of text are in a sensible order and sufficiently descriptive.    

The definition for [text](https://www.w3.org/TR/WCAG22/#dfn-text): 
> sequence of characters that can be programmatically determined, where the sequence is expressing something in human language

Nothing there specifying "visible".  I note that this consistent with alt text not (typically) being visible. 

No, SC 1.2.1 does ***not*** require alternative for time-based media for video-only to be visible.

**Comment by dbjorge** [comment]
> Nothing there specifying "visible". I note that this is consistent with alt text not (typically) being visible.
>
> No, SC 1.2.1 does not require alternative for time-based media for video-only to be visible.

I agree that this probably has to be our interpretation assuming we want to avoid visual alternatives being required for animated gifs, which I think we're in agreement on; I don't think we have any normative mechanism to say "sometimes it needs to be visual and sometimes not".

When we update the understanding doc to clarify this position, it'd be nice to make sure we also clarify with an example that it isn't *required* for the text alternative and the alternative for text based media to be the same thing, and that for videos that are particularly long or complex, it might aid usability to separate them.

**Comment by kengdoj** [comment]
> No, SC 1.2.1 does not require alternative for time-based media for video-only to be visible.

Can ACT move forward this decision?

**Comment by bruce-usab** [comment]
Discussed on TF call 4/12 and, we have consensus on the answer to the substantive questions.  Per our process, TF facilitators won't close this issue until AG WG gets a chance to review.

--- 

On the original question:

> Does SC 1.2.1 require the alternative for time-based media for video-only to be visible?

No, it does not.

> Can ACT move forward this decision?

Yes please.

**Comment by mbgower** [comment]
Closed as a result of the Official Working Group Response being reviewed and adoped

**Comment by mraccess77** [comment]
While audio can be a solution and is not visible - text equivalents    that are beyond a simple description that are hidden would be useless for someone who isn't using a screen reader.  I don't agree with the working group decision that it's ok for a full text transcript to be completely off-screen with CSS and pass WCAG.

For awareness @GreggVan

**Comment by awkawk** [comment]
I believe that this decision is incorrect (sorry, I just became aware of it last week in a discussion with an ACT TF member).

I tried to review the WG decision and there is zero evidence of any. This was mentioned on the WG agenda (https://lists.w3.org/Archives/Public/w3c-wai-gl/2024AprJun/0040.html) and minutes (https://www.w3.org/2024/04/23-ag-minutes#item04) but there was no discussion on it in the minutes and really only a request for WG members to hit thumbs up (without really being clear where) if they agreed.

I don't think that it is likely that the WG members would agree that they made a decision. 

The definition for "alternative for time-based media":

> document including correctly sequenced text descriptions of time-based visual and auditory information and providing a means for achieving the outcomes of any time-based interaction

There's only one alternative for time-based media definition, and it applies to audio-only and video-only, and the WG decided that it doesn't need to be visible??

I see the argument being made that alternative text for images isn't visible, but not only is that information that is specifically targeted to be rendered by AT (and could be rendered visually) but the impact of individual images is much smaller than even a short video. A low-vision user zoomed in to a high magnification can relatively easily pan around a static image and get all of the detail, but panning around a video that is continually changing leaves that same user with questions about what was missed as they looked around.

**Comment by lauracarlson** [comment]
I agree with @awkawk.

The definition of “alternative for time-based media” is key. It describes a *document* with ordered text that allows a user to achieve the same outcome as the video. That points to something users can access, read, and use as content, not something hidden and only exposed to screen readers.

It also says the alternative must **“provide a means for achieving the outcomes.”** That is stronger than just existing in the DOM:

- If the transcript is only available to screen readers, it does not provide a general means  
- It only supports a specific type of assistive technology  
- Many users with disabilities do not use screen readers  

Taken together, this suggests the alternative needs to be available in a way that is broadly usable, not limited to a single access method.

## Why visibility matters

If the transcript is not visible, many users cannot use it in a practical way. This includes low vision users who rely on zoom and visual reading rather than screen readers.

For example, for a low vision user who does not use a screen reader, a visible transcript provides a stable way to access the information. If that transcript is hidden, they lose that ability.

## The alt text comparison does not fit

Comparing this to image `alt` text does not hold up:

- `alt` text should be terse as it is read out as string content.  
- It is designed to be read by assistive tech in one pass. 

A transcript is different:

- It is long.  
- It has order and structure.  
- It is meant to be consumed like regular content.  

Because of that, treating a hidden transcript like `alt` text does not reflect how people actually use it.

## Works across user agents and tools

A visible transcript works across:

- browsers  
- zoom and magnification  
- reading and cognitive support tools  

An off-screen transcript depends on a specific AT path, which limits its usefulness.

## Conclusion

The alternative does not need to be next to the video. It can be on another page or linked nearby. But it should be available in a way people can perceive, find, and use.

If it is only exposed to screen readers, it falls short of being a usable alternative for many users.

## Suggested direction

It would be helpful to:

1. Document the reasoning behind the current position.
2. Clarify whether the  1.2.1 implies visual availability for users who do not use screen readers.
3. Consider narrowing the earlier conclusion to avoid endorsing fully off-screen, AT-only transcripts as sufficient.

**Comment by alastc** [comment]
Going back to [Dan's comment](https://github.com/w3c/wcag/issues/3642#issuecomment-2005349689), I think the issue is whether the alternative is **_required_** to be visible. 

Reading above, it isn't entirely clear from the normative text, and there are examples where we would not wish that to be the case.

In which case the previously agreed response is correct, but we might want to make sure the desirable outcomes are emphasized in the informative docs.

**Comment by awkawk** [comment]
The alternative definition applies to video and audio. This decision would mean that there is no requirement to provide a visible alternative to audio-only content. I agree that it would have been better if we didn't use "document" in the definition for "alternative for time-based media" but there is a clear difference between this type of alternative and alternative text for images. I am 100% confident that the WG did not think when it wrote "document including correctly sequenced text descriptions of time-based visual and auditory information and providing a means for achieving the outcomes of any time-based interaction" that this would be invisible content. We would not be looking to accept a document that was substantially non-conforming with WCAG SC.

In the current Understanding document, the WG discusses benefits of making the alternatives available in text and providing support for a variety of users, some of which are not possible if the text is invisible:

> - This success criterion helps people who have difficulty perceiving visual content. Assistive technology can read text alternatives aloud, present them visually, or convert them to braille.
> - Alternatives for timed-based media that are text based may help some people who have difficulty understanding the meaning of prerecorded video content.
> - People who are deaf, are hard of hearing, or who are having trouble understanding audio information for any reason can read the text presentation. Research is ongoing regarding automatic translation of text into sign language.
> - People who are deaf-blind can read the text in braille.
> - Additionally, text supports the ability to search for non-text content and to repurpose content in a variety of ways.

@GreggVan, any more specific recollections here?

**Comment by GreggVan** [comment]
Being present when this was written -- I can safely say that at no time did we ever think of that alternative not being visually detectable.  It was envisioned as being a document that was text and therefore accessible to and usable by people with any disability - including cognitive (via AT) and deaf-blind (ditto) as well as people who were blind or deaf and could not make sense out of the video - and authors who did not want to create audio descriptions.   It was not as good as AD for enjoying movies but it did ensure access to the information presented.  (kind of like reading a play by reading its "book" vs seeing a play.

**Comment by lauracarlson** [comment]
I think @awkawk’s point about the same definition applying to both video-only and audio-only is important.

If a fully off-screen, screen-reader-only alternative is allowed, that would apply equally to audio-only. That would allow a transcript to be invisible, which does not align with how transcripts are expected to function as usable content.

Picking up on @alastc’s point, I agree the Success Criterion does not explicitly require visibility. But the definition still requires that the alternative **“provide a means for achieving the outcomes.”** That implies practical usability, not just technical presence.

An off-screen transcript:

- works for screen reader users  
- but is not usable for many others, including low vision users who rely on visual access  
- and people with cognitive disabilities who benefit from being able to read and review text  

So the requirement can be met in a technical sense, but not in a way that works well for a broader set of users.

@GreggVan 's clarification reinforces this. The intent was a *document* that could be used by people across disabilities, including cognitive and deaf-blind users, not something hidden. That aligns with the idea of a visible, usable text resource, even if it is not the same experience as audio description.

There is also a mismatch with the term “document.” A document is something users can read, navigate, and return to as content. If it is fully off-screen and only exposed to screen readers, it behaves more like hidden metadata than user-facing content. That makes it difficult to see how it serves as a usable alternative.

More broadly, WCAG does not typically treat “available to one type of assistive technology” as sufficient when that limits access for others. Long-form, structured content that supports understanding or task completion is expected to be usable across different access methods, not restricted to a single path.

It makes sense to clarify this in Understanding. But it would help to be clear that fully off-screen, screen-reader-only alternatives do not meet the intent of providing a usable alternative for a broad range of users.

**Comment by bruce-usab** [comment]
Early [in this thread](#issuecomment-1919543691) I was in the “yes, of course it must be visible” camp.  I was persuaded otherwise by the nuanced discussion.  I’ve recently reread but I won’t pretend to remember my thinking then.  The two data points I find most compelling now:
- Visibility is _not_ explicitly in the normative phrasing.
- An _extremely_ reasonable alternative for a video-only recording is an audio-only recording!

@awkawk wrote:
> I agree that it would have been better if we didn't use “document” in the definition for “alternative for time-based media”…

Agreed!  Let’s fix that!  After we hash out this issue (again), do you object to an erratum to make that correction/clarification?

FWIW, I am of the option that it’s [1.2.8 Media Alternative (Prerecorded) (Level AAA)](https://www.w3.org/WAI/WCAG22/Understanding/media-alternative-prerecorded.html) that requires something visual, and which would accommodate the needs of someone who is deaf-blind.

**Comment by lauracarlson** [comment]
Thanks @bruce-usab, that helps explain how you got there.

On the two points:

> Visibility is not explicitly in the normative phrasing.

I agree it is not stated directly. But the definition still says the alternative must **“provide a means for achieving the outcomes.”** That means it needs to actually work for people, not just technically exist. If something is only usable through one type of assistive technology, that seems like a pretty narrow interpretation of “a means.”

> An extremely reasonable alternative for a video-only recording is an audio-only recording!

I agree an audio version can be a good alternative, and SC 1.2.1 allows that. But I do not think that carries over to transcripts.

An audio alternative:
- can be used directly without needing a specific assistive technology  
- works across different user setups  

A fully off-screen transcript:
- only works if someone is using a screen reader  
- does not work for people who rely on visual access or read text directly  

So they are not equivalent in how broadly usable they are.

Gregg’s comment also helps here. The intent was a *document* that people could use across disabilities, including cognitive and deaf-blind users. That points to something people can actually access and use as content, not something hidden.

> Agreed! Let’s fix that!

I would be careful about removing “document.” That word seems important. It signals that this is meant to be something people can read and use, not just hidden content.

This feels more like a case where we should clarify how to interpret “document” and “provide a means,” rather than remove that wording.

**Comment by mraccess77** [comment]
I don't think we should have an erratum to remove document.  I think we can  keep document. The SC text already allows for audio file or an alternative - so audio or a screen play type equivalent.

"Either an alternative for time-based media or an audio track is provided that presents equivalent information for prerecorded video-only content."

**Comment by MakotoUeki** [comment]
At the "Image and media alternative" subgroup meeting today, Andrew and Laura shared this discussion with me because I was absent last week.

I was participating in the WG for WCAG 2.0 and I've never thought it can be invisible as well. So I agree with Andrew, Laura and Gregg that transcripts must be visible.

> This feels more like a case where we should clarify how to interpret “document” and “provide a means,” rather than remove that wording.

+1 to Laura. We should do it in the Understanding WCAG2.2 without changing normative text if clarification is needed.

**Comment by dbjorge** [comment]
This new discussion since reopening seems completely focused on longer/more substantive media content where a transcript would be the basis of an appropriate alternative. But I want to give a reminder that one of the main bits of reasoning for the initial closure was that WCAG's definition of "video" is so general that it would include short animations, which are *vastly* more common in actual web UIs than longer videos where a transcript would make sense. I don't think it would be a good outcome for us to accidentally normatively require that a static "check" icon and an "check" icon with a 1 second animation have significantly different bars for alt text.

**Comment by awkawk** [comment]
@dbjorge if you are referring to animated gifs, sure, those are more common, but I think that since animated gifs don't operate with a constant frame rate that it is hard to consider these time-based media. Is that the concern or is it more than animated gifs?

**Comment by mraccess77** [comment]
Video alternatives already fall under SC 1.1.1 - so short videos with no additional need for a transcript would already be covered there.

**Comment by dbjorge** [comment]
> I think that since animated gifs don't operate with a constant frame rate that it is hard to consider these time-based media

An individual animated gif *could* (and often does) specify the same frame duration per frame, but even if it didn't, I don't think this would be clear at all; absent a definition of "time-based", I don't see why "a constant frame rate" would necessarily have anything to do with whether such a case would be in scope. I wouldn't expect a long instructional video to become out of scope just because it happens to be implemented using a compression technology that involves dynamic frame rates.

> is it more than animated gifs?

Yes, I think the same concern would apply to an animation that happened to be implemented in terms of CSS transitions/animations of otherwise still images.

> Video alternatives already fall under SC 1.1.1 - so short videos with no additional need for a transcript would already be covered there.

I agree that 1.1.1 is sufficient for requiring alt text appropriately. What I'm saying is that I'm not so sure such cases ought to have *additional* requirements *beyond* 1.1.1 (via 1.2.1)

**Comment by bruce-usab** [comment]
@GreggVan recollection matches my own:
> Being present when this was written -- I can safely say that at no time did we ever think of that alternative not being visually detectable…

But intent and “what were we thinking” doesn’t really matter.  What counts is what we wrote.  Intent gets reflected in Understanding, but it’s not normative.

**Comment by bruce-usab** [comment]
No one has engaged with my observation that a historically good alternative for a silent video recording is an _invisible_ audio recording.

**Comment by awkawk** [comment]
> No one has engaged with my observation that a historically good alternative for a silent video recording is an _invisible_ audio recording.

From a testing perspective, if an audio file is provided for a video-only asset, that's fine, but if text is provided then it needs to be visible. The audio track option feels like a separate question - it is allowed for video-only and yes, it is invisible, but that doesn't mean that text can be invisible.

**Comment by GreggVan** [comment]
@bruce-usab 
To answer your question -- if the alternative is not visible - it is not available.       Audio alternatives that are visible in the player - are visible.     Alternatives intended only for screen readers need to be "visible" in the screen reader.   But alternatives meant for a deaf person  (Not an alternative that is audio - but an alternative to audio) should be visible to the deaf person as they would view the page.  Ditto for deaf-blind person or any other disability.  Alternatives are not "provided" or "available" if the intended users would not perceive them as being there.

**Comment by mraccess77** [comment]
> Alternatives are not "provided" or "available" if the intended users would not perceive them as being there.

And if a low vision user who doesn't use a screen reader can't access the hidden text then it's not available to them.

**Comment by lauracarlson** [comment]
@dbjorge I think that is a fair concern, but I do not think it changes the core issue.

Very short animations and UI icons already fit better under 1.1.1. As @mraccess77 noted, those cases do not usually need a full transcript. So this feels more like a scoping question than a reason to lower expectations for all video-only content.

For cases where 1.2.1 *does* apply, we are back to what the alternative is expected to do. It is meant to provide equivalent information in a usable way. That is a different bar than a short alt text for a simple icon.

@bruce-usab on the audio point, I agree that an audio version is a valid alternative and it is allowed by the SC. But I see that as a different path, not a justification for hidden text.

An audio alternative:
- is directly usable without requiring a specific assistive technology  

A hidden transcript:
- only works through a screen reader  

So the fact that audio can be non-visible does not mean text can be treated the same way. They behave differently in terms of who can actually use them.

More broadly, this comes back to a simple point: WCAG requirements are not just about something existing, but about it working for people. An alternative that only works through one access path is hard to treat as a fully usable equivalent.

**Comment by bruce-usab** [comment]
@GreggVan the link for (downloading) the audio file would (of course) have to be visible, but the link itself isn’t the alternative to the video-only media.  The video description recording (used as an alternative for time-based media) itself is audio-only and thus not visible.   There are other caveats, including “is clearly labeled as such” and probably [CAV](https://www.w3.org/TR/WCAG22/#dfn-conforming-alternate-versions).

@lauracarlson thank you for agreeing that an audio version is a valid alternative and it is allowed by the SC.

> But I see that as a different path, not a justification for hidden text.

I am just opining on the literal text of the SC and the specific yes/no question posed.   WCAG has loopholes, this might be one of them.  I agree that hidden text creates accessibility barriers.

[alternative for time based media](https://www.w3.org/TR/WCAG22/#dfn-alternative-for-time-based-media):
> document including correctly sequenced text descriptions of time-based visual and auditory information and providing a means for achieving the outcomes of any time-based interaction

I would want know more about the specific scenario under contemplation, but I think the fail might actually be against 1.3.1 which catches disconnects between what is happening visually and what is available to screen reading software.

**Comment by lauracarlson** [comment]
Thanks @bruce-usab, that helps clarify your position.

I agree an audio alternative is valid and allowed, and that it does not need to be visible in the same way text does. But that feels like a separate path that the SC already accounts for, not something we can use to generalize about text alternatives.

On the definition, the key part for me is still that it is a *document* that “provides a means for achieving the outcomes.” That suggests something usable as content, not just something technically available through one modality.

To make this concrete, the scenario I have in mind is a video-only video-only (or audio-only) resource where a transcript is provided, but it is hidden off-screen and only available to screen readers. In that case, the alternative exists, but many users cannot access or use it.

One comparison that might help: SC 1.2.2 does not explicitly say captions must be visible either. But if captions were only exposed to screen readers and not usable visually, that would not be considered sufficient. The expectation is that they function as captions in practice.

That feels similar here. The requirement is not just that an alternative exists, but that it works as a usable equivalent.

I also agree there could be overlap with 1.3.1 in some scenarios. But even then, that would only identify that something is wrong. The core question is whether the alternative itself meets the expectation of being a usable equivalent under 1.2.1.

So even if the SC does not explicitly call out visibility, allowing a text alternative that is only available to screen readers still seems like it would not meet what “provide a means” is asking for.

**Comment by GreggVan** [comment]
I have to say -- I  am completely confused by this discussion. 

1)  an audio file is an alternative to a video only file.    But if there is no way for someone to access perceive it...  I'm not sure would count.   Otherwise I  could just keep the alternative on my hard drive and comply.   The alternative has to be accessible to those who need it - to be an alternative.

if one is assuming that it can be invisible and be "perceived"  by people who are blind - then I  think one has forgotten that "most people who are blind - can see".     And that many legally blind do not use screen readers.   

So providing an audio file as an alternative to a video file is NOT and alternative to people who cannot use the video file if the only way to know there is a file is to be using a screen reader which they do not use. 

ditto for a text file. 

So I  think having a requirement for an alternative that requires a screen reader is inherently a failure.  And the requirement that any alternative is discoverable by those that need it I  think is inherent to any SC.   And those with low vision who don't use screen readers are part of the intended audience.

no?

**Comment by dbjorge** [comment]
> @dbjorge I think that is a fair concern, but I do not think it changes the core issue.
>
> Very short animations and UI icons already fit better under 1.1.1. As @mraccess77 noted, those cases do not usually need a full transcript. So this feels more like a scoping question than a reason to lower expectations for all video-only content.
>
> For cases where 1.2.1 does apply, ...

@lauracarlson I agree that short animations and UI icons fit better under 1.1.1 and that my concern about them would be reasonable to handle as a scoping question. The problem I'm trying to raise here is that I don't think those cases are *actually* scoped to 1.1.1 only today, since I don't think it's very clear whether they'd actually qualify as "time-based" or not.

I split off that scoping question to a separate issue (#5155); my preference would be to treat solving it as a *prerequisite* for strengthening 1.2.1 here.

**Comment by lauracarlson** [comment]
@GreggVan I agree, and that helps clarify the core issue.

If an alternative requires a screen reader to even discover or use, then it is not really functioning as an alternative for a significant portion of the intended audience, including many low vision users. That seems hard to reconcile with “provide a means for achieving the outcomes.”

@dbjorge thanks for splitting out the scoping question. That seems like the right place to resolve where short animations fit.

For this issue, my focus is on cases where 1.2.1 clearly does apply. In those cases, the question is whether the alternative actually works for people in practice, not just whether it exists.

**Comment by innoticFR** [comment]
> [@dbjorge](https://github.com/dbjorge) if you are referring to animated gifs, sure, those are more common, but I think that since animated gifs don't operate with a constant frame rate that it is hard to consider these time-based media. Is that the concern or is it more than animated gifs?

I think the term "time-based media" is used here to include all kinds of non-video visual content, such as an automated or interactive visual presentation (historically Flash, or a SMIL presentation, for example), while being totally agnostic about the format. Since this includes interactive elements, it clearly goes beyond traditional, passive multimedia files. Frame rate does not seem to be the defining factor here.
