### ISSUE TITLE
Technique F97: Add related technique G214

### ISSUE THREAD

**Issue by umut-gultekin** [w3c/wcag#3792]
[G214: Using a control to allow access to content in different orientations which is otherwise restricted](https://www.w3.org/WAI/WCAG22/Techniques/general/G214)

**Comment by fstrr** [comment]
@umut-gultekin Did you mean to open this as an issue? If so, could you explain the issue please. If you didn't, please close it. Thanks!

**Comment by umut-gultekin** [comment]
@fstrr I am sorry. I pressed the button under the techniques and assumed this was how I was expected to contribute. Is forking and editing the expected way to contribute?

**Comment by fstrr** [comment]
Hey, @umut-gultekin. My mistake—you're all good. I was lacking caffeine this morning and wasn't thinking straight.

One thing that would be useful in the future would be to link to the technique that you want something changing in. Instead of just having F97 / F86 / F82, etc. in the title, also link to it in the body of the issue—it makes it quicker to get to what's being talked about :)

Sorry for the comment and thanks for the issues!

**Comment by dav-idc** [comment]
Hey @umut-gultekin I've opened a PR that should link F97 and G214 together as you described.

Would you be able to double-check the changes made, as shown in the pull request?
- https://github.com/w3c/wcag/pull/3817/files

**Comment by umut-gultekin** [comment]
Looks good to me. Thanks @dav-idc
