### ISSUE TITLE
Is technique G183 meant to be advisory?

### ISSUE THREAD

**Issue by anevins12** [w3c/wcag#3860]
Technique G183 in Use of Color (SC 1.4.1) talks about it "going beyond the success criterion", yet it is a sufficient technique in the SC:
> To meet success criterion 1.4.1: Use of Color a [relative luminance](https://www.w3.org/TR/WCAG22/#dfn-relative-luminance) (lightness) difference of 3:1 or greater with the text around can be used. This technique goes beyond the success criterion and asks for visual highlights when the user hovers over each link, such as an underline, a change in font style such as bold or italics, or an increase in font size.

https://www.w3.org/WAI/WCAG22/Techniques/general/G183

**Comment by anevins12** [comment]
I realize there is a thread already, but I wasn't entirely sure on the conclusion and didn't want to derail the thread: https://github.com/w3c/wcag/issues/2310

**Comment by mbgower** [comment]
**Draft Working Group Response**

A sufficient technique means that following it will meet the success criterion indicated. While efforts are made to scope sufficient techniques so that they only addresss the specifics of a criterion, sufficient techniques do not need to be restricted to only meeting a bare minimum of the requirement. In this situation, part of the technique listed acknolwedges that it exceeds the specified requirement. That does not make it an advisory technique.

An advisory technique typically lists a technique that is _not_ sufficient for a specific requirement, but may afford an improved user experience. Please see https://www.w3.org/TR/UNDERSTANDING-WCAG20/understanding-techniques.html#ut-understanding-techniques-advisory-head

**Comment by anevins12** [comment]
Right
