### ISSUE TITLE
Accessible name link in Label in Name understanding document goes nowhere

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#3907]
There are two links for "accessible name" in the [Understanding](https://www.w3.org/WAI/WCAG22/Understanding/label-in-name) document.
However, only one of those resolves.

They should both resolve, and it is not clear whether the link should point to https://www.w3.org/TR/accname-1.2/#dfn-accessible-name or https://www.w3.org/TR/wai-aria/#namecalculation

**Comment by patrickhlauke** [comment]
>  it is not clear whether the link should point to https://www.w3.org/TR/accname-1.2/#dfn-accessible-name or https://www.w3.org/TR/wai-aria/#namecalculation

the former seems far more apropos (the definition of accName) than the latter (an explanation of accName *calculation*)

**Comment by patrickhlauke** [comment]
actually, i have a vague memory that at some point we may have discussed having a proper definition (in WCAG) for accessible name. am i misremembering? that clearly didn't happen. i guess since the glossary is normative, it'd be too much of a pain to try and do it "properly" - create a glossary term definition, and change all instances/mentions to link to that

**Comment by patrickhlauke** [comment]
made a PR for the "simpler" solution of linking to the accName spec's definition (there was a similar reference in Consistent Identification
