### ISSUE TITLE
Carry out editorial review for consistent structure

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wcag#398]
_From @mbgower on May 8, 2018 15:53_

Understanding docs should be compared for the amount and type of content in sections (e.g., Intent), and an attempt made to align style and volume. The editorial pass should also consider adding subheadings or moving content to make the Understanding documents more consistent.

_Copied from original issue: w3c/wcag21#904_

**Comment by michael-n-cooper** [comment]
_From @mbgower on May 8, 2018 15:57_

Note: this is a different editorial pass than the straightforward Style Consistency phase, where editors confirm that the same stock headings and other structural material appear in each document (e.g., every Understanding document contains a "Specific Benefits of..." section).

**Comment by alastc** [comment]
Hi @mbgower, 

I'm digging through the old issues... 
As a task, this one is going to sit here for a long time. I think we're better tackling it as we update documents.

The ones I think of as different (e.g. non-text contrast) have good reasons for being different, but could be shortened (maybe) if the techniques are added & improved.

It would be best to open individual issues for an understanding doc at a time, rather than a general issue... re-open if you disagree, I'm just cleaning house.
