### ISSUE TITLE
SC 1.3.5 is not restricted to markup languages but SC 1.3.6 is

### ISSUE THREAD

**Issue by mraccess77** [w3c/wcag#425]
SC 1.3.5 is scoped to technologies that support communicating purpose --so essentially it would appear that SC 1.3.5 is only applicable to HTML content.  Without an exception for other technology like PDF it's unclear if it fails or passes.

**Comment by awkawk** [comment]
Jon, right now since PDF doesn't have any support for "identifying the expected meaning for form input data" a PDF document wouldn't fail this. We should review and make sure that this is clear in the U doc.

**Comment by mbgower** [comment]
I read the second qualifiying bullet
> The content is implemented using technologies with support for identifying the expected meaning for form input data.

as being _more_ precise than simply restricting to markup language. There may be a technology that is not a markup language that can still support meaning (i.e., PDF _could_ add a new field to an input property that provided that ability). I think the status of PDF can be clarified in the Understanding document.

**Comment by awkawk** [comment]
WG is going to update the Understanding document to make this more clear. (per 7/31/2018 call)

**Comment by PhuongHoang1182** [comment]
Hi guys I’m working on this CS for AAA site need to know one thing. To we need to build the site with a ability to upload a icon or have multiple new user interface components icons (build in JavaScript and apply to all the new icon be selected). Support personalization and preferences?

Or 

All we need to do is us microdata (https://www.w3.org/TR/microdata/) in the code and we pass the Conformance for cs 1.3.6?


A website uses ARIA landmarks to identify the regions of the page, and users can hide areas that are not the 'main'.
**The links in the navigation of a website are marked-up so that users can add their own icons.
Icons on a website use are marked-up so that the user can substitute their own icon set into the page.**

**Comment by johnfoliot** [comment]
Editorial re-write here: https://rawgit.com/w3c/wcag/identify-input-purpose-updates/understanding/21/identify-input-purpose.html

**Comment by PhuongHoang1182** [comment]
thanks @johnfoliot for your help.
the new editorial re-write cs 1.3.5 help to clear some off.
To we have any new Editorial re-write for cs 1.3.6 in the work ?

**Comment by alastc** [comment]
It looks like John's re-write has gone into the master and been published, so I'll close this.
A review & update of 1.3.6 is a useful thing, but not covered here.
