### ISSUE TITLE
Decorative vs Meaningful images

### ISSUE THREAD

**Issue by iamrafan** [w3c/wcag#521]
Related to: [SC 1.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html), [F38](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F38)

A couple of questions:

1) Should images with ```alt=""```and ```alt``` without value be considered as decorative images irrespective of the presence of accessible name through ```aria-label, aria-labelledby or title```?

2) Should images without alt attribute be considered as meaningful if they have an accessible name?

Here, are the results from some AT testing I did

Examples tested: https://codepen.io/iamrafan/pen/pxVzMX?editors=1000#

  | AT/Browser | alt="trulli" | alt="" | alt | alt=" " (space) | aria-label="Name 5" & no  alt attribute | Alt=""    & aria-label="Name 6"
-- | -- | -- | -- | -- | -- | -- | --
1 | Edge/Narrator | Image trulli | Ignored by AT | Ignored by AT | Image | Image Name 5 | Ignored by AT
2 | Edge/JAWS | Graphic trulli | Ignored by AT | Ignored by AT | Graphic | Graphic Name 5 | Ignored by AT
3 | Edge/NVDA | Graphic trulli | Ignored by AT | Ignored by AT | Graphic | Graphic Name 5 | Ignored by AT
4 | Chrome/NVDA | Graphic trulli | Ignored by AT | Ignored by AT | Graphic | Graphic Name 5 | Graphic Name 6
5 | Chrome/JAWS | Graphic trulli | Ignored by AT | Ignored by AT | Ignored by AT | Graphic Name 5 | Ignored by AT
6 | IE/JAWS | Graphic trulli | Ignored by AT | Ignored by AT | Ignored by AT | Graphic   Unavailable Name 5 | Ignored by AT
7 | IE/NVDA | Graphic trulli | Ignored by AT | Ignored by AT | Graphic | Graphic Name 5 | Graphic Name 6
8 | Safari/voiceover | Trulli Image | Ignored by AT | Ignored by AT | Ignored by AT | Name 5 Image | Name 6 Image
9 | Firefox/NVDA | Graphic trulli | Ignored by AT | Ignored by AT | Graphic | Graphic Name 5 | Graphic Name 6

**Comment by mraccess77** [comment]
My personal thoughts.... This is a question I asked of the accessible name calculation folks.  Since ARIA naming mechanisms come first it would seem like those take precedence -- however, support by assistive technology and some older browsers may not live up to that expectation.  How alt= " " or aria-label = " " is treated by the name calculation is also something that has been discussed as well but I don't recall the answer on whether this is treated as a empty string and processing continues or it's treated as non-null and therefore space becomes the accessible name.

**Comment by DavidMacDonald** [comment]
I'm dropping this into the aria github repo

**Comment by fstrr** [comment]
It looks as though this can be closed, especially as the related issue on the ARIA repo was closed. If it needs to be re-opened, please do.
