### ISSUE TITLE
Clarification on 2.5.3 Label in Name interpretation

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#592]
I had the following question posed by the IBM team working on an automated rule for comparing the text string to the accessible name. As part of that calculation:

Do we care about punctuation
\<div role="gridcell" id="punctuation" aria-label="Next"> Next... \</div>

Do we flag numeric values or treat it not applicable:
\<div role="gridcell" id="numbers" aria-label="one"> 1 \</div>

Do we ignore all that is not text
\<div role="gridcell" id="notText" aria-label="Next"> -\&gt; \</div>

In other words:

- would "Next" as the accessible name be a failure?
- Can we count on the AT accepting both "Next dot dot dot" and "Next ellipsis" as equivalents if we just make it "Next..."?
- Is the accessible name of "one" acceptable for a text string of "1" (and vice versa)? Is it a failure?
- Does a label that is _only_ punctuation count as text and thus require that same punctuation in the accessible name? And if so, is there value in "->" as an accessible name for the purposes of this SC? 

I believe the answer to these queries is that the accessible name should encompass the text string displayed in all these cases (should be "Next...", "1", and "->", but I'd like to confirm with the group. @KimPatch, please weigh in from your perspective.

**Comment by mbgower** [comment]
I'll also mention colons at the end of input labels as being an inadvertent point of failure.

**Comment by alastc** [comment]
Hi Mike, 

By the SC wording and definition of 'text', I'd have thought:

- Next / Next... is a pass, the text is included. (Text is characters representing human language, so I don't think ... counts)
- One / 1 possibly a fail, but perhaps a false positive?
- Next / -&tg; a pass, the visible thing is a symbol/graphic rather than text (so effectively an NA).

A heuristic using alpha-characters (at least in English) wouldn't be far off.

**Comment by awkawk** [comment]
@alastc In @mbgower's example, the label is "next..." and the name is "next" - so his point is that the label is not in the name in its entirety, unless punctuation doesn't count.

I'd be interested in what @KimPatch says, but I think that we should treat the "&gt;" as a graphic (and same goes for the "X" on a close dialog). If Kim says that the "..." is significant in "next..." then we can go that way but I don't have a strong preference. The "1" and "one" example I would be inclined to pass since the user would voice each the same.

**Comment by alastc** [comment]
@awkawk I got the punctuation difference, but from reading the definitions of [text](https://www.w3.org/TR/WCAG21/#dfn-text) and human language, I wouldn't have included the ellipsis. I.e. we should exclude punctuation.

> The "1" and "one" example I would be inclined to pass since the user would voice each the same.

So would I, but assuming that works, we probably need to add some words to that effect in the understanding, as it looks like a technical fail. Would/should that also apply to words that sound the same? E.g. they're / their.

**Comment by awkawk** [comment]
@alastc ok, so we are in agreement, but your rationale helps clarify that.

Re: 1 vs one - this doesn't apply to homophones like their/they're as the user's AT can allow them to read the text by character and would cause confusion.

**Comment by mbgower** [comment]
@alastc I'm going to suggest that the definition of text
> sequence of characters that can be programmatically determined, where the sequence is expressing something in human language

has to be read creatively to discount punctuation and very creatively to decide that homonyms could pass.

There are two key perspectives to consider here. The first is what is going to work for an automated test. The second, what is going to work for an AT. I think we'd need to have a better understanding of how speech rec handles "Click there button" (and whether it would find "they're" or "their") as well as how demanding we want to get on creators of automated tests.

Treating a ">" as a graphic is convenient, but hard to defend when you consider beyond the confines of this SC. For many criteria, it is not an image of text, it is not a graphic. It is text. So I think it is a lot easier for us to say that for the purposes of this SC, punctuation can be disregarded. Thus, commas, terminal punctuation like colons and punctuation-only labels would be out of the equation as _required_ to be there.

Need to hear from @KimPatch to see if she anticipates this having ramifications. I can see that there are going to be some occasional frustrations whether we insist punctuation must be there or disregard. From an automated test procedure perspective, stripping out punctuation in a string match between a label (whether just doing matches on "for" etc or doing some kind of location-based text search) and the accessible name is a lot cleaner and consistent, I think.

**Comment by awkawk** [comment]
@mbgower My saying to treat the > as a graphic was a little too casual. I think that it is accurate to say that ">" isn't communicating anything in human language. It is communicating something, but that is done by the visual representation of the character.

OTOH, another consideration is that the UI guidelines identify the ellipsis as a convention to indicate that the action being activated requires more information from the user, so that seems like useful information to include so long as speech users aren't required by their tools to always speak that part.

- https://docs.microsoft.com/en-us/windows/desktop/uxguide/cmd-menus#usingellipses
- https://developer.apple.com/design/human-interface-guidelines/macos/buttons/push-buttons/

**Comment by mraccess77** [comment]
If we start to say ">" is human language than icon text which is clearly text could then fall into the bounds of text because it is expression something in human language.  That means icon fonts would then be covered by the text contrast requirements of WCAG 2.0.   So we should make sure to update across the understanding documents if we make such a determination.

**Comment by alastc** [comment]
@awkawk wrote:
> Re: 1 vs one - this doesn't apply to homophones like their/they're as the user's AT can allow them to read the text by character and would cause confusion.

I'm just trying (and failing) to think up a way of explaining that it allows for 1 vs one, but not they're vs their.

@mbgower wrote:

> the definition of text ... has to be read creatively to discount punctuation and very creatively to decide that homonyms could pass.

It was partly text, but also the human language aspect:

> language that is spoken, written or signed (through visual or tactile means) to communicate with humans

Punctuation is essentially lost in translation when going through voice input/output, it is too fragile. 

Punctuation can obviously impact pauses & how something is read out (varies between UAs), but from my (admittedly limited) experience with _voice input_ you have to add punctuation explicitly, and in this scenario the best thing from a user point-of-view is to ignore punctuation.

> stripping out punctuation and case in a string match between a label ... and the accessible name is a lot cleaner and consistent, I think.

My sense is that it would work for voice-input as well, understanding language is such a hard problem they must work around this kind of issue already.

@awkawk wrote:
> ">" isn't communicating anything in human language. It is communicating something, but that is done by the visual representation of the character.

That's what I was trying to say, in addition I don't think an end user should have to know if that's a text or an image, it could be either so doesn't qualify has 'human language' for what it represents.

The better solution would be some guidance (not a guideline, e.g. at a WAI level) that recommends particular terms to put into the accname for common icons, whether they are characters or images.

For example, I recently recommended a client rename their icon from 'hide main menu', to 'close main menu' because I though 'close' would be more common term for an "X" than 'hide'. It's a minor thing, not an ideal solution (compared to a 'show the hidden labels' comment in AT) but hopefully helpful.

**Comment by awkawk** [comment]
> I'm just trying (and failing) to think up a way of explaining that it allows for 1 vs one, but not they're vs their.

With the number it is a direct representation of the word, and it is voiced the same so doesn't impact users speaking or hearing it, and if it is being read character by character it works too. I think that excluding the homophones that are not homonyms is easy.  All that said, I don't want you to think that this is something that I'm going to fight for. :)

**Comment by mbgower** [comment]
Hi folks, I've had some more discussions internally, and I believe I see a possible path forward on this front. I'll have to review the HTML and ARIA acc name specs again to say it with more authority, but I believe I can say with mild confidence that in most situations the areas where we are going to have issues are where the visible label is overridden by the author, and that looks to me to be largely isolated to aria-label, aria-labelledby and, potentially, title.

Of those 3, aria-labelledby is _normally_ going to be pulling a visible string from the screen, so it is still going to match visible text to the accessible name. So we are really talking about aria-label being the culprit here, and the most apropos in regard to questions are punctuation, capitalisation, etc. (And yes, use of "title" may also need to be considered).

So I'm wondering if maybe the meat of all this stuff should be covered in a sufficient technique (with potentially a failure technique as well) on use of aria-label to meet 2.5.3. That would keep a lot of this confusing stuff out of the Understanding document, where I can't help but feel it is going to do more harm than good.

It still doesn't help us easily give guidance where the button is "..." and the aria-label is "show options". but at least it allows us to restrict such considerations to where someone has had to invoke aria-label to backfill crappy design.

**Comment by mbgower** [comment]
@alastc BTW, can you please fix the typo in your [comment](https://github.com/w3c/wcag/issues/592#issuecomment-457963272)

We had someone searching high and low for &tg; I believe you accidentally transposed the t and g and this is supposed to be greater than

**Comment by alastc** [comment]
Hi @mbgower, I'm not sure what you mean? I didn't use either, just the actual symbol.

**Comment by awkawk** [comment]
Proposed WG Response: Thank you for the comment (and all of the hard work updating the Understanding document. The updates include sections on use of characters in a symbolic form and characters used for punctuation and capitalization. In both cases, neither requires that the accessible name includes the exact text from the label because they are not considered to communicate information in human language.

**Comment by awkawk** [comment]
Agreed on March 26 call: https://www.w3.org/2019/03/26-ag-minutes.html#item09
