### ISSUE TITLE
Clarification on user interface components for 2.5.3 Label in name

### ISSUE THREAD

**Issue by cpandhi** [w3c/wcag#593]
Success Criterion 2.5.3 Label in Name For user interface components with labels that include text or images of text, the name contains the text that is presented visually. 
And user interface component is defined as: a part of the content that is perceived by users as a single control for a distinct function. Do we need to check elements with structure roles (not usually interactive ) that do support name from content? (cell, columnheader, heading, row, rowgroup,  rowheader, tooltip) or does it apply to only widget roles.

**Comment by cpandhi** [comment]
Success Criterion 2.5.3 Label in Name
For user interface components with labels that include text or images of text, the name contains the text that is presented visually.

And user interface component is defined as:
a part of the content that is perceived by users as a single control for a distinct function.

Do we need to check elements with structure roles that do support name from content? (cell, columnheader, heading, row, rowgroup, rowheader, tooltip) or does it apply to only widget roles.

**Comment by mbgower** [comment]
I would also like to add <code>scope</code> and <code>headers</code> to this discussion.

**Comment by alastc** [comment]
If something isn't interactive, I don't think it's a control.

If a control (e.g. a button) were in a table and the structure affected the accname, it could be in scope, but I don't think that's the case anywhere?

**Comment by awkawk** [comment]
Agree with Alastair that the definition for UI components is focused on form controls and links, but it includes inactive versions of components (e.g. a disabled button) as well. Short answer to this issue is, I believe, no.

**Comment by mbgower** [comment]
I was thinking specifically of matrix of options in a questionnaire. However, I think I'm comfortable with allowing the requirements for this SC to be quite contained. 
 I will go into this in regard to a matrix in the Understanding doc and see if we can get consensus on that, and then the revised Understanding doc can be the official response to this.

**Comment by mraccess77** [comment]
I've also seen situations where a radio button acts as the visual label for an input such as an "other radio button" acts as a label for an input field that takes other input.

**Comment by alastc** [comment]
Interesting case Jon, I assume it's possible to use one label for two inputs, but what happens when you click on the label, or do that via dragon?!

With this SC in mind, it might be best to have a separate (hidden) label with the same content so that saying "click other" brings up a choice.

**Comment by awkawk** [comment]
@alastc Sounds like this represents a (potentially small) gap in what is covered by WCAG.  Here's a page that shows a screenshot of a control like Jon is describing: https://answers.laserfiche.com/questions/126715/radio-button-other-value-update

With this pattern, we can meet 1.1.1 and 4.1.2 using aria-label, we can argue that we meet 3.3.2 because the text input is labeled by the relationship to the "other" radio button, and we can argue that aria-label="Other" (or aria-labelledby) is descriptive enough for 2.4.6. But will all of this, a speech user may not be able to say a command to switch from the first "other"-labeled control to the next. But, that user will be able to tab once (in this situation) and get to the text input.

It is the same problem that could exist if there are multiple fields with the same label, for example a form which uses grouping relationships to ask for the first name for multiple people and the accessible name is "first name" for each. I'm not sure if a speech user would be able to target the different instances of "first name" or if tabbing through is a typical process in that situation.

As long as these cases are the exceptions we may not be able to do anything unless the speech user agent support can differentiate between these.

**Comment by awkawk** [comment]
Proposed WG Response: Thank you for the comment. We have recently updated the Understanding document (Preview: http://htmlpreview.github.io/?https://github.com/w3c/wcag/blob/master/understanding/21/label-in-name.html). The SC applies to User Interface Components, as you indicated, which generally indicates widget roles that are active for user interaction rather than objects with roles that are non-interactive such as column header, rowgroup, etc.

**Comment by awkawk** [comment]
Agreed on March 26 call: https://www.w3.org/2019/03/26-ag-minutes.html#item09
