### ISSUE TITLE
1.4.13 Content on Hover or Focus - need some clarifications on two points

### ISSUE THREAD

**Issue by kantoche** [w3c/wcag#605]
Hi, 
Here the two points:

1) In the description of Dismissible feature, we can read that 

> the additional content is dismissible without moving pointer or keyboard focus, unless the additional content communicates an input error. 

So, an additional content communicating an input error can’t be dismissed and just disappears when user removes hover or focus from the trigger. Why this behavior that is not explained in the rest of understanding?

2) In the explanation of Dismissible feature, a possible mechanism to dismiss an additional content is to use a closing button.

- Is this closing button located inside the additional content?
- If so, should this additional content be hoverable but also **focusable** to reach the closing button and activate it?

**Comment by detlevhfischer** [comment]
Proposed working group response:
There can be cases where an input error requires attention and should therefore not be easily dismissed. A required field with prior invalid input may display an error message when it is re-focused or hovered above. The SC text simply allows for exceptions in situations where such errors would require attention, explicit confirmation, or remedial action. The working group intends to update the understanding text to cover this situation.
The situation where a close button allows dismissal of content would require that this button sits inside the trigger, not inside the additional content. If it were part of the additional content, activating it would require moving the focus away from the trigger. The close button inside the trigger would only cover content on hover and work for pointer activation only since making it keyboard focusable would imply a change of focus for activation. Such a pointer-only solution is likely to be backed up by a keyboard-operable way of dismissing the content.

**Comment by alastc** [comment]
Noting that this was discussed by the group ([survey](https://www.w3.org/2002/09/wbs/35422/Tech_Und_survey/results#xq18), [discussion](https://www.w3.org/2019/04/30-ag-minutes.html#item04)), and the close button aspect has been removed from the understanding doc (which will be visible on the next publication run).

**Comment by alastc** [comment]
It is not clear where the quoted text comes from, it isn't the SC text or in the understanding document, is it from an old version?

New proposed response:
<hr>

**For question 1:**  There are cases where an input error causes a pop-up message making the user aware of that error. Usually such error messages are displayed when focus moves away from the input (blur event) . Authors may decide to re-display such error messages when inputs in error are re-focused or hovered above. The SC text does not say that such error messages must not be dismissable -- it simply allows for exceptions to dismissal in situations where such errors would require attention, explicit confirmation, or remedial action. 

The working group intends to update the understanding text to cover this situation, the suggested text for that is: 
> "The success criteria allows for input error messages to persist as there are cases that require attention, explicit confirmation or remedial action."

**Question 2:** The close button aspect has been removed, it is theoretically possible that such a technique could work, but the working group is not ready to recommend that.

**Comment by alastc** [comment]
The comment above was accepted as the groups opinion, so I'll close this.

Please re-open if you think it hasn't been answered, thank you for contributing!
