### ISSUE TITLE
definition of presentation in SC 1.3.1

### ISSUE THREAD

**Issue by goetsu** [w3c/wcag#618]
Hi,

current definition of presentation regarding 1.3.1 is 
> presentation : rendering of the content in a form to be perceived by users

Do this definition mean visual rendering ? 

For example if you have visually hidden content available to screenreader used to achieve title of a section or a data table. Will you invalidate 1.3.1 or consider it as not applicable due to the fact that the content isn't visually rendered.

Also if you consider it as a violation of 1.3.1 will require based on 1.3.1 to make it visible for all users or only that the content is correctly structured with hx / caption even if not visually rendered

I think that if 1.3.1 apply only on content that is visually rendered it must be specified in the definition

**Comment by patrickhlauke** [comment]
My understanding is that it's the *visual* rendering, yes. Perhaps this could/should be clarified (though definitions are normative, so not sure how easy/quick it would be to do)

**Comment by patrickhlauke** [comment]
Though, thinking about this further, maybe it's not so clear cut. If you have separate content that's specifically visually hidden, but available to screen reader users, then if that content serves a particular purpose (like acting as the label/title for something) then I could see an argument for dinging it as a fail of 1.3.1 if it lacked the correct markup association....conflicted now.

**Comment by goetsu** [comment]
@patrickhlauke that's why I ask the question. Even if the change can't be done before 2.2 or silver I would like to have the working group consensus on that (at least updated techniques and understanding can be a way to provide clarification on that)

**Comment by awkawk** [comment]
This is my take on this, not the Working Group's:

1.3.1 reads: Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.

The key defined term here is "presentation": rendering of the content in a form to be perceived by users

The SC implies the author's intent in the presentation. The author puts content into a web page or in a web application with the intent that people are able to take view/perceive it. The problems happen when authors do so without understanding that not everyone views content in the same way and offers the content in a manner that is exclusionary. Criteria such as 1.3.1 help by reminding authors that the information contained on a page, as well as the structure and relationships need to be programmatically determinable. 

If an author includes a table with a caption and makes that caption perceivable to assistive technologies but not perceivable visually, the information, structure, and relationships are programmatically determinable so this would meet 1.3.1. The fact that the information is not available to sighted users is not covered by this SC.

This situation may be viewed as follows:  An author who doesn't feel that a table caption is necessary for sighted users to identify a table decides to leave it out. The author then or previously gets feedback from a non-sighted user that the table caption is helpful and as a result includes it in this manner. The author's decision could be viewed as flawed because of the assumptions that are made (e.g. only non-sighted users are using speech to text tools) but WCAG 2.0/2.1 do not require all programmatically determinable information to be visually rendered by default - although users could have assistive technologies that manage the rendering of programmatically determinable information.

In practice, "Presentation" most commonly implies visual presentation, but as indicted in the Understanding document for 1.3.1 (https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) auditory information (or someday, scent or haptic information) that is used to convey information, structure, or relationships needs to ensure that information is able to be programmatically determined.

How does this sound?

**Comment by mraccess77** [comment]
I agree with @awkawk’s reading of the criteria.

**Comment by goetsu** [comment]
I agree too for the case where the visually hidden content is correctly structured 

my question was more when it’s not the case like using just a visually hidden paragraph of text that constitute a caption for a data table but not structured as caption or associated with table using aria labelledby 

Will you consider this case as a violation of 1.3.1

**Comment by awkawk** [comment]
@goetsu I doubt I would wear out my keyboard logging issues of this sort as they wouldn't be very common, but in the specific case you mention I would consider it a 1.3.1 issue because it isn't associated, just as I would consider a paragraph preceding a table insufficient to act as a caption if the paragraph was visible.

**Comment by alastc** [comment]
Andrew's [response above](https://github.com/w3c/wcag/issues/618#issuecomment-463220834) was agreed with the working group so we'll close this issue. @goetsu Please re-open if you disagree or have another point on this specific topic.
