### ISSUE TITLE
The wording of 3.1.2 does not include a requirement for accuracy

### ISSUE THREAD

**Issue by mbgower** [w3c/wcag#651]
>The human language of each passage or phrase in the content can be programmatically determined except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text.

Yes, this has existed for a decade and so doesn't need to get tackled right now, but there is nothing in this SC saying the language of the passage must be _correctly_ determined. When we get to Silver, we should reconsider the wording. It should also include wording that this is a When -- it only applies when language in a passage differs from the page language.

**Comment by awkawk** [comment]
This applies to 3.1.1 as well, but I don't think that there is a problem so much as the ability to be more clear. If you have a phrase in the content that is in the French language, then French is the language of that phrase, and French needs to be what is determined programmatically.

If I have `<p>To say hello in Spanish, say <span lang="ja">Hola</span>.<p>` this is definitely an error under this SC. If Just determining ANY language was ok then we wouldn't even need a 3.1.2 since the language set in 3.1.1 would be picked up for phrases on the page.

**Comment by patrickhlauke** [comment]
> It should also include wording that this is a When -- it only applies when language in a passage differs from the page language.

Currently, in audits, I mark these as a pass for pages that have no changes of language BUT where the language of the page has been correctly set (because the language of each passage or phrase can still be programmatically determined, as it's the language of the page) - and conversely fail if the page lacks it and there's no language change.

**Comment by alastc** [comment]
Proposed response: The requirement for correctness comes from the logic of the statement, if "**_the_** human language" can be "programmatically" determined, an incorrect setting of the language would fail.

**Comment by awkawk** [comment]
Agreed on March 26 call: https://www.w3.org/2019/03/26-ag-minutes.html#item09
