### ISSUE TITLE
Key terms have word "new" preceding definition, 2.5.2: Pointer Cancellation

### ISSUE THREAD

**Issue by jake-abma** [w3c/wcag#708]
Key terms have word "new" preceding definition

see: https://www.w3.org/WAI/WCAG21/Understanding/pointer-cancellation.html#key-terms

> down-event
> new
> platform event that occurs when the trigger stimulus of a pointer is depressed

> single pointer
> new
> pointer input that operates with one point of contact with the screen, including single taps and clicks, double-taps and clicks, long presses, and path-based gestures

> up-event
> new
> platform event that occurs when the trigger stimulus of a pointer is released

**Comment by mbgower** [comment]
I note that in [Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow#key-terms), the "New" is capitalized. 
These Key Terms sections are not actually in the Understanding documents, but generated. @michael-n-cooper, I have made the change under /terms/21.
I note that the dfn for CSS pixel (from Reflow) contains a data-lt attrbute missing from the up-event and down-event. Since other of the new ones also have this, and the -lt attribute seems to be a form of plurality indicator, I didn't touch it here, but wanted to note.
https://github.com/w3c/wcag/pull/711

**Comment by michael-n-cooper** [comment]
I'm not sure but assuming the request here is to suppress the generation of "new" from key terms, which is a hold-over from the working draft stage. I'll put that on my list.

**Comment by jake-abma** [comment]
At 2.5.1: Pointer Gestures we have another one:

https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html#key-terms

> **single pointer**
> new
> pointer input that operates with one point of contact with the screen, including single taps and clicks, double-taps and clicks, long presses, and path-based gestures

**Comment by patrickhlauke** [comment]
@jake-abma a "point" on that key term...noting that a mouse is also a "pointer" and has no "contact with the screen" as such (only in an abstract sense)

**Comment by jake-abma** [comment]
@patrickhlauke thanks, I know, I use Wacom pen, most of the time don't touch anything. But this one is about the word "new", not about the definition :-)

**Comment by patrickhlauke** [comment]
yeah sorry, i knee-jerked there. filed a proper separate issue here https://github.com/w3c/wcag/issues/749
