### ISSUE TITLE
1.4.12 Text Spacing - Clarify `text-overflow: ellipsis` applicability, as well as acceptability

### ISSUE THREAD

**Issue by cscrosati** [w3c/wcag#728]
It is common technique to use the CSS property `text-overflow: ellipsis` to allow text to overflow a container while indicating further text is available that cannot fit the current container area. From there, various web sites determine what mechanism allows to access this overflowing text.

It is unclear from the 1.4.12 Text Spacing criterion if this is allowed or not. As currently spelled out, it appears website would have to always expand any text, which I think isn't the intent.

Could we clarify applicability and acceptability of the usage of the `text-overflow: ellipsis` CSS property? This could lead to publishing a couple new documents:
1. A new Advisory Technique document (where this would be acceptable, with proper ways to show text beyond the ellipsis)
1. A new Failure document due to applying ellipsis without providing ways to access the value of the overflown text.

**Comment by cscrosati** [comment]
I wanted to add an example outside my initial premise to start off this discussion of acceptability and applicability.

On YouTube main page, titles for the linked content is limited to two lines of text under each card. What doesn't fit is cut off with an ellipsis. The full text is exposed on hover via the user-agent exposing the `title` attribute added to the DOM element.

While applying the Text Spacing requirement solely on letter spacing, the instances of overflowing text beyond the ellipsis shown will increase markedly. The exposed mechanism to consume that content is still in place, just more important then before.

Is this sufficient? Is this allowable?

**Comment by patrickhlauke** [comment]
My gut feeling on this would initially be that no, that sort of approach (eliding text more) would not pass. The whole point of the SC is that certain users have difficulty reading the text as the page sets it, so need to be able to adapt spacing etc to help them read it better. If, trying to do that, text simply gets chopped (or chopped even further), that defeats the purpose. While having the `title` attribute shown on mouse hover is at least a somewhat helpful, it would not help for anything other than fairly short bits of text that have been elided, and won't help keyboard users at all at this stage.

But perhaps there's a nuance of "how much text" here. If it's just the a title (and other content adapts correctly), AND if the full title is still available if the user clicks through to the page...maybe that's a mitigating factor? Users that need the extra spacing will still be disadvantaged/inconvenienced a bit, but at least they can, with an extra step through to the actual page, still see the full title? (However, if the title has the same behaviour in the page you then click through, then it feels like we're back to iffy territory of reliance on title hover)

**Comment by alastc** [comment]
I'd point to the crux of the SC:
> no loss of content or functionality occurs...

So my interpretation of the examples above would be:
- If text is not generally truncated, but it is when text is spaced, and there is no mechanism to show it: fails the SC.
- If the truncated text is available onclick(/keypress) and passes other criteria (e.g. 1.4.13), I'd pass that.
- If the truncated text is available on the page you click thorugh to, I'd pass that. (Same principle as Reflow, which had a lot of discussion along those lines.)

The trickier example is when text is sometimes/always truncated by default, but the degree of truncation is more when text-spaced. I think I'd still use the examples above - it needs to be available somehow.

**Comment by cscrosati** [comment]
Thanks for your replies. Both of you seem to acquiesce that elided text is within the spirit of the criterion, as long as the full text is available in some ways from that UI. 

This is what I wanted clarified. :) Quoting myself:
>...allow text to overflow a container while indicating further text is available _[...]_. From there, various web sites determine what mechanism allows to access this overflowing text.

If eliding long text was disallowed, a lot of current website would already fail, without much room to succeed, especially when the UI design is constrained in two dimensions.

With the three steps check enumerated by @alastc, this would clarify this well, at least for me. Adding that to the understanding doc seems fitting. Would it not still need a failure technique (due to not providing text in full)?

I initially started this thread because it is common to work with design constraints that limits the amount of text that can be displayed. A few common examples of such designs taken from our website:
1. Multi-column data grid with single line per entry, sometimes with user defined content of unbounded length.
1. Card UI, where both height and width are fixed.
1. Flexible text section with 'reveal' action ('show more / read more')

Using the three steps verification, I can confirm success or failure of Text Spacing on our current website as follow:
1. Data grids have resizable columns, and in many cases, have navigable content that displays the content in a different form. In many cases, `title` attribute or other hover content is available to help too.
1. Card UI is navigable and opens up content with the text in full. Here too hover UI is available.
1. Flexible text section already provide toggle to expand/collapse the overflowing text. Hover content isn't available due to the text length which would make it impractical.

**Comment by patrickhlauke** [comment]
> If others agree, I think it warrants an update to the understanding doc (a line in the intent, an example), rather than new techniques.

a late +1 on this from me

**Comment by mbgower** [comment]
Just ran into an example of this in the left navigation area, where I think there are obvious reasons the design would NOT want to keep making the left navigation width wider to prevent content being truncated.
In this case, ellipses were used. The user can execute on the left nav links which opens the page, and the heading of the page provides the information.
So I think this overall approach cuts down on the problem space.

**Comment by mbgower** [comment]
Since @cscrosati mentioned the truncation in youtube, I thought I'd paste a screen detail to help with what might be a more pointed discussion now that I've made a PR for this
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/14298245/205725411-98be7800-8892-4f03-8725-16863fc463cf.png">
In the image, there are two of four videos which have their heading text truncated:
- one is an ad which reads "$5,000 Grant and $40,000 Government Loan. 0 Interest Rate. Install Energy-Savin..."
- one is a regular video which reads "The BIGGEST Mistkes DIYers Don't Know They Are Making..."

So, basically youtube has made a design decision that they will only expose 2-lines of the video heading in their landing page view.

In another example, the online Outlook tool provides a narrow window for displaying the inbox view, where every messages is truncated to a single short line
<img width="636" alt="image" src="https://user-images.githubusercontent.com/14298245/205726209-c250fdb2-2d82-400b-aee8-7bc8acbc9247.png">

Outlook provides the ability to resize this window so that less of the subject lines are truncated. I would call that a mechanism to display truncated text. But it's not difficult to picture a scenario where for the sake of a compact inbox preview, the design decision makes sense to not have a 10 line subject list shown.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/14298245/205726800-70bc14cc-e1e3-4ed8-9f9e-1a90b133793c.png">

So the question becomes, is there a scenario where this elided text approach that is okay for stand interactions, would become disallowed when accommodating increased text spacing? I think that would be a pretty hard argument to make successfully (but anyone feel free to make the argument).

So, now moving to

**Comment by mbgower** [comment]
Discounting the use of elided text for a moment, the question becomes what are the results of this is we disallow it? It means that text would either be forced to break over multiple very short lines  or that the defined widths would automatically expand. Both could cause more potential problems for readability than the elided text.

**Comment by JAWS-test** [comment]
@mbgower Limiting the exception to the use of an ellipsis seems nonsensical to me, since I can truncate text without an ellipsis.

I think the exception in PR is too broad. I agree with the exceptions, if the text is already abbreviated anyway (as in your Youtube or Outlook example) and more is abbreviated after adjusting the spacing, I can live with that, even if I don't find it optimal. Then it would be worth considering whether a similar exception should also apply to 1.4.4 and 1.4.10.

But if the text is not abbreviated in the normal state and after adjusting the spacing it is abbreviated, I think only one variant is acceptable: If I can adjust the width of the page area so that I can read all text content completely again. But if I have to hover over the text contents individually or even click the links all individually to read the texts on the new page, I have such a significant additional effort in operation that I do not consider this acceptable.

**Comment by JAWS-test** [comment]
In general, I don't think it's a good idea to define exceptions to WCAG 2.1 years after it was adopted, which are contrary to the SCs intentions. The SCs were discussed extensively when 2.1 was created - the techniques we are talking about already existed when WCAG 2.1 was adopted and were not uncommon even then. If no one saw the need to define such an exception back then - why should it suddenly exist now. This also applies for https://github.com/w3c/wcag/issues/2795

**Comment by JAWS-test** [comment]
Also, I think the non-normative Understandings can't just add or take away requirements from the SC. If we want exceptions, we should define them in the SC. This is how it is handled in the new SCs of WCAG 2.2

**Comment by JAWS-test** [comment]
In the end, however, the same applies as to https://github.com/w3c/wcag/issues/2795. I would not find such a change good, but the lack of clarity on how to deal with truncated text even worse. I.e. an explanation in the Understanding (no matter how it turns out) provides uniformity in the evaluation of problems when adjusting text spacing and is welcomed by me in any case.

**Comment by JAWS-test** [comment]
@alastc 

>  It isn't an "exception" being added in the understanding document, it is showing how to assess the SC in the context of WCAG, which allows for multiple mechanisms to do things.

I don't find anything in WCAG that allows for any SC that I somehow otherwise find a solution to my accessibility problem, even if the solution involves significant extra work. Where does it say that in WCAG? 

The only thing I can find is the conforming alternate version. This is not exactly defined, but clicking on links to be able to read truncated texts is not meant by this in my opinion.

**Comment by alastc** [comment]
@JAWS-test firstly from the SC itself, "no loss of content", so if the content is available, that isn't a fail.

Secondly from the [conforming alternative version](https://www.w3.org/WAI/WCAG22/Understanding/conformance#conforming-alt-versions), so the full text would be available and "in the same human language, and is as up to date as the non-conforming content, and ... can be reached from the non-conforming page".

**Comment by alastc** [comment]
This was surveyed and [agreed by the group](https://www.w3.org/2023/05/30-ag-minutes#t04) based on merging #2827
