### ISSUE TITLE
When content is, and isn't, "web content"

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/wcag#827]
as part of https://github.com/w3c/wcag/issues/814#issuecomment-513131162 i've prodded the "web content" aspect again (as has been discussed previously on the mailing list, though i can't locate the thread just now). wondering if we can get some more clarity in general about when something is, and isn't, considered "web content"...

1) a PDF that is displayed directly in the browser's built-in PDF viewer
2) a PDF that is displayed directly in the browser via an installed plugin/extension (e.g. Adobe Reader)
3) a PDF that, when accessed, loads a standalone version of a PDF application (which runs outside of the browser, and loads the PDF from a local copy the browser had to download - even if it is in the browser's cache/the system's "temp" directory)
4) a video that plays directly in the browser's `<video>` player
5) a video that plays in another web-based player (e.g. using flash/silverlight/other plugin)
6) a video that, when accessed, loads a standalone version of a video player application like VLC and plays a locally downloaded version of the file
7) a video that, when accessed, loads a standalone version of a video player that connects directly to the hosted video online (using TCP or UDP and some form of video transfer protocol like MMS, RTP, ...)
8) a file in some exotic format which happens to be hosted on the web, but when accessed is downloaded and opened only in a third party standalone application (think, aeh, a photoshop .psd file, a 3D Studio Max .3ds file, or similar)
9) a file in some exotic format, for which however there exists a plugin (though not very commonly present on users' machines) that can display it inside the browser

My view on these is that 1, 2, 4, 5 and potentially 7 and 9 are "web content", while 3, 6 and 8 aren't.

(also, feel free to think "Word document" or similar for the PDF examples)

**Comment by mraccess77** [comment]
I believe one of the things that defines web content was that it is delivered through a web url and not embedded in an app and not from a file on an ftp or users machine.

**Comment by patrickhlauke** [comment]
@mraccess77 fancy giving an answer to the various examples above of which ones you'd say are and aren't web content?

**Comment by mraccess77** [comment]
1, 2, 4, 5, 8, 9 are web content IMO.      Web content includes Silverlight, Java, Flash, etc. when loaded from a url.

Web page
a non-embedded resource obtained from a single URI using HTTP plus any other resources that are used in the rendering or intended to be rendered together with it by a user agent

NOTE
Although any "other resources" would be rendered together with the primary resource, they would not necessarily be rendered simultaneously with each other.

NOTE
For the purposes of conformance with these guidelines, a resource must be "non-embedded" within the scope of conformance to be considered a Web page.

**Comment by patrickhlauke** [comment]
> 1, 2, 4, 5, 8, 9 are web content IMO

8 is the file that gets downloaded locally and then opened in a separate application ... assuming that's a mistake?

as for the WCAG 2.1 definition, the "non-embedded" note is always a bit odd, because you could argue that flash/silverlight content or similar plugin-based stuff is "embedded" inside an HTML container page ... (and there's no definition for "embedded" / "non-embedded")

**Comment by electronicwoft** [comment]
What about the contents of inline frames? Is this embedded content )(despite having a unique URL) or a second webpage?

**Comment by mraccess77** [comment]
We had a discussion maybe 5 years ago with Gregg V. I believe and people seemed to agree that an iFrame was not a separate piece of web content in terms of looking at page titles as it was an embedded resource and therefore fell under the containing page's requirements for a page title.

**Comment by WayneEDick** [comment]
It is really good that we are no longer the Web Content Accessibility
Guidelines Working Group and are just the Accessibility Guidelines Working
Group. We don't have to split this hair anymore.

**Comment by patrickhlauke** [comment]
Wayne,  as long as the output is still the "Web Content Accessibility Guidelines", I'm afraid that hair needs to remain split. Also, this still needs to fall within the remit of WAI and W3C, which is clearly "Web"

**Comment by WayneEDick** [comment]
More seriously:

The question as posed wrong. How a user actually access content has little
to do with whether it is web content.

The question is this. How does content we get from a site participate in
the to the purpose of the site? This may take some work to define, but here
two some operational examples:

A university system has all its policy statements listed on one site. Each
statement is a secure linked PDF file. All of these files are web content
even if a user with low vision will probably view them using desktop
software that is not necessarily a formal assistive technology.

A utility company has a list of videos that describe how to address
different dangers that occur in an earthquake. These videos are linked to
the website. The videos are web content because they demonstrate how to
cope utility issues associated with an earthquake, the purpose of the site.

**Comment by patrickhlauke** [comment]
I'd sugges then that in future versions of WCAG or whatever, this gets clarified a lot more. currently, the guidelines talk about "web content" extensively, and define it in the normative glossary as

> content (Web content)
> information and sensory experience to be communicated to the user by means of a user agent, including code or markup that defines the content's structure, presentation, and interactions
https://www.w3.org/TR/WCAG21/#dfn-content

and 

>user agent
> any software that retrieves and presents Web content for users
> Note: web browsers, media players, plug-ins, and other programs — including assistive technologies — that help in retrieving, rendering, and interacting with Web content.

https://www.w3.org/TR/WCAG21/#dfn-user-agents

if we take the much more lax view that you seem to be proposing, that we shouldn't care about whether it's "web content" or not, we end up with guidelines that are created at the World Wide Web Consortium, under the Web Accessibility Initiative, but purport to be universal guidelines that aim to cover any sort of digital content. That's not the scope of W3C/WAI. The consortium's patch does not extend beyond what we can justifiably claim is "web", IMO anyway...

also, by the same logic, ANY file that happens to be hosted on the web and then gets downloaded and opened in an external program would end up falling under the guidelines. photoshop files? CAD files? 3D Studio Max scenes/models? it's a slippery slope ...

**Comment by bruce-usab** [comment]
The three of us agree that 1, 2, 4, 5, 9 are web content.

Notably, we agree that 3 is not web content.  But I think 3 is problematic because, from a content authoring perspective, 1, 2, _and 3_ are indistinguishable from each other!  So I am inclined to argue that we should treat those three cases all the same, and not try to split that particular hair.

FWIW, with the 508 refresh, we addressed the paradox with  around this by scoping.  So documents (PDF, Word, etc.) posted to the Internet are covered, whereas documents posted on a http-based file share _might_ not be.  For “electronic content” we have a [list](http://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/text-of-the-standards-and-guidelines#E205-content) of what is covered, but I will be the first to admit that the last item (I, intranet content designed as a Web page) is a little subjective.  I do not think WCAG should adopt this sort of scoping.

I would argue that 7 is _not_ web content, mostly for an [appeal to consequences](http://en.wikipedia.org/wiki/appeal_to_consequences), but I am happy to go with Jon’s argument nothing in the stack (TCP/UDP/MMS/RTP, etc.) is really close enough to http to count as web content.

**Comment by access401** [comment]
I appreciate this conversation, greatly.   We need this clarification, badly.
I am a teacher who started teaching 15 years ago online in an impoverished part of the country.  I knew nothing about the online accessibility at that point, I only knew this: that the only way some of my students would be able to attend school is if I were to put their homework online so that they could download the files and do their homework at home, since they could not afford cars to get to class, or babysitters to watch the six kids.  Online was their only way to education.   I uploaded CAD files, among others, and the students downloaded files at home and then processed them locally using CAD software on their home computers.   They were able to finish school this way.    
As I started to teach myself the ways and means of online accessibility, I started doing things like putting H1, H2, etc. headings in the document because I was "supposed" to do that, not understanding that only certain assistive technology could read the headings.    I was able to get to a point to where my documents passed accessibility criteria, but they were useless to someone who was blind.   The "real" assistive technology for my students was anything that worked to enlarge the images. But such "informal" assistive technology did not "count" as such.    For a blind student, we would "build" 3-D representations as necessary.
Fast forward to today.  I'm not working with CAD files, but I am in a position where I am trying to help the math teachers, so @WayneEDick I am extremely interested in your thoughts on this.  
When I first arrived, I found that many teachers were using Microsoft's "Equation Editor", "MathType", and LaTeX.   I would like to focus on the LaTeX example.   These PDF files, generated from LaTeX were inaccessible, of course, to screen readers, and we fixed the LaTeX -generated PDFs by adding all the things you are supposed to for screen readers.  When it came to actually reading the math, only "simple", "flat' , "linear" math was read in correct order.   And that includes after we used Adobe Acrobat Pro's "formula" option.   Anything with matrices, denominators, etc were read out-of-order for the math.  Technically speaking, screen readers could read it, but it was garbage.  I later talked to a blind man who had wanted to pursue higher mathematics, but said the technology for reading it accurately just doesn't exist.  Upon researching a little further, I found that LaTeX was actually used by blind people for math.  It's a simple mark-up language, but it needs specialized equipment to export it to a pdf.
As far as I can tell, we have a direct way to teach higher math to students using LaTeX.    They need the special software to do it.   And, I am actually pushing this as a "path to math" so that blind students can pursue higher mathematics.    Yet, these files are considered "inaccessible" as web content and the teachers that are trying to support this get penalized for accessibility because of the way "accessibility" is measured.  I want to be able to point to something official in the W3C that says, "just because it is on the web, does not mean it is necessarily web content".
@WayneEDick for our low-vision users, we are pursuing the use of MathType.  Apparently, it uses a vector format to render its images (although not svg, as I understand it) thus enabling low vision users to see the math.   It is also screen-reader accessible by NVDA with a MathPlayer add-in, but this is specialized equipment, again, to read it.   It works.  Yet, by the book, we have to add alt-attributes AGAIN, as in, a second time, because to common accessibility checkers, these vector images don't "show" the alt-attributes built into them.
I understand this is a slippery slope.  But we definitely need guidance, and I really appreciate what everyone is doing here.   
I do not think item 8 is web content, and I'm hoping we can explore this a little more.   Thank you so much for all everyone is doing.

**Comment by Myndex** [comment]
Well this is an interesting topic

## CONTENT

- Visual Content

**Comment by awkawk** [comment]
I agree that 1,2,4,5,9 are treated as web pages under WCAG 2.x.

More and more we are seeing situations like #8 where the 3rd party application using the source file's information is itself a web-based application, so the information that is rendered from the source file would be presented as content within that web app, so would be covered. But if the file is downloaded and then used by the stand-alone application, I think that 8 is out of scope for WCAG.

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
