### ISSUE TITLE
Scope of "Third Party Content"

### ISSUE THREAD

**Issue by MakotoUeki** [w3c/wcag#89]
# Statement of Partial Conformance - Third Party Content

We need specific examples which can be applied to "[Third Party Content](http://www.w3.org/TR/WCAG20/#conformance-partial)".

## 1. Social plugins

Examples of issues including, but not limited to:

* When Windows high contarst mode is on, the logo (icon) and/or the button label is invisible.
* When it uses the &lt;iframe&gt;, the title attribute is not provided or the value of the title attribute doesn't describe the contents of inline frame.
* When "Timeline" widget is embedded in a web page and it includes an image, ALT text is not provided for the image.

## 2. Video player

Examples of issues including, but not limited to:

* Controls (play/pause button, volume control slider, etc.) are not keyboard accessible, or
* Label/ALT text is not provided for each control, or
* Controls are invisible when Windows high contrast mode is on.

## 3. Map

* Controls of the interactive map that is embedded in a web page is not keyboard accessible.

## 4. Update Issue (added on April 28th)

These plugins, players and widgets can be updated without notice. The update is also not under author's control.

For example, an author embedded a third party's widget which was conforming to WCAG in a website and the website made a conformance claim at that time. After that, the widget was updated by the third party and the updated version has an issue which fails a success criterion. 

If the widget is considered to be a "Third Party Content", "Statement of Partial Conformance - Third Party Content" could be made. If not, the website won't be able to make a partial conformance claim as well as a conformance claim due to the failure.

## Question (modified on April 28th)
In many cases, they are not content that are under the author's control. Authors don't have any alternatives as the codes are officially provided from the third party they are using. For example, when they are using Twitter, there is no option. Authors have no choice but to use the plugin which is officially provided by Twitter even if they already found an issue to be fixed.

As a precondition of "Statement of Partial Conformance - Third Party Content", WCAG says "it is not possible to know at the time of original posting what the uncontrolled content of the pages will be."  Actually authors can check if the third party content is WCAG conformant before they use it. But "it is not possible to know at the time of original posting what the uncontrolled content (= upcoming version of the third party content) of the pages will be". 

Can we apply "Statement of Partial Conformance - Third Party Content" to these plugins, players and widgets? 

We should have specific examples in "Understanding WCAG 2.0" to clarify what would be included and what would not be included. 

The followings are just images. It doesn't mean that they fail under WCAG SC.

![social button](https://cloud.githubusercontent.com/assets/8966912/7258716/4a3ca084-e899-11e4-9a79-b4a59c940cd2.png)
![tw-timeline fw](https://cloud.githubusercontent.com/assets/8966912/7258738/5dcf308a-e899-11e4-99a5-560b46a4099a.png)
![video](https://cloud.githubusercontent.com/assets/8966912/7258744/64be879c-e899-11e4-9fea-7b0479717de0.jpg)
![map fw](https://cloud.githubusercontent.com/assets/8966912/7258882/3f9c63ac-e89a-11e4-9e82-e0b91a76dfca.png)

**Comment by DavidMacDonald** [comment]
I have provided fixes for developes for the like... I've asked developers to add the title attribute to the youtube iframe

**Comment by joshueoconnor** [comment]
Focussing on the business case primarily and saying to anyone who is providing TPC that it must meet a certain standard before it will be included. This could be as simple as making titles mandatory on iFrames (as DavidMcD points out) - to captioning video etc. My point is make it about the business case, and not explicitly about a11y - this is a way to get a11y in via the backdoor.

**Comment by MakotoUeki** [comment]
> If they can't fix it I'd say it is a statement of non conformance which means it does not conform but it would if these things were removed... here's the statement.

That is the point. If we could make a partial conformance claim (= non conformance), we can use these things even if they have an accessibility issue. If not, we may have to give up using these things in order to make a conformance claim or eliminate the web pages from the scope for the conformance claim.

WCAG is ambiguous and it results in different interpretations. Some developers say "This is not under our control and can be updated automatically without notice. So we can regard it as the Third Party Content". Other developers say "If we find an accessibility isuue, we should fix it. If we can't, we won't make even a partial conformance claim and we have to give up using this."

I'd like the working group to draw a line and add some specific examples to the Understanding document to clarify the line.

**Comment by awkawk** [comment]
I think that the has drawn the line with the partial conformance statement that David cites. To conform to WCAG you can't have non-compliant content for any reason, but for partial conformance you can have non-compliant content provided that it is truly out of your control. Whether a particular country's policy allows partial conformance is up to the policy makers in that country.

Looking at a specific example, a developer needs to evaluate whether a facebook "share" button is developer-configurable and can be made accessible, or if it is 3rd party content that they can't control.

https://developers.facebook.com/docs/plugins/share-button has the information and it tells me that I need to add a div that contains a reference to the Facebook script source, and that I also need to add a div which will ultimately contain the button, but then at runtime the button div is modified by the script at runtime.

It seems that even if your average author could make modifications to the resulting code that is generated in order to improve the accessibility, he wouldn't know if or when the code that is generated might change and possibly break the improvements.

On the other hand, a developer who uses the Facebook API to build accessible buttons (or uses an alternate 3rd party solution) should be able to avoid accessibility problems.

The question seems to be "what level of pragmatism is appropriate for allowing authors to claim partial conformance?"

**Comment by MakotoUeki** [comment]
> The question seems to be "what level of pragmatism is appropriate for allowing authors to claim partial conformance?"

What about the following?

When a third party content (e.g. social plugin, video player, interactive map)  has an accessibility issue and an author want to embed it in a web page;
- If an author fix it, then conformance claim can be made.
- If an author can't fix it or use it as it is, then the statement of partial conformance (= non conformance) can be made.

It seems to be almost impossible for us to define "level of pragmatism". So this could be a simple solution. If you want to make a conformance claim, you must fix it by yourself. If partial conformance is acceptable for you, you can use the code provided by a third party as it is and make the statement of partial conformance.

**Comment by joshueoconnor** [comment]
Loretta has taken an action item to draft response to this:

http://www.w3.org/WAI/GL/track/actions/308

**Comment by lorettaguarino** [comment]
Proposed response:
We are adding a new section to Understanding Conformance to discuss partial conformance - third party content. The proposed addition can be found at https://www.w3.org/WAI/GL/wiki/Understanding_Partial_Conformance_-_Third_Party_Content

**Comment by joshueoconnor** [comment]
RESOLUTION: Understanding Partial Conformance - Third Party Content[edit]
When an author makes a decision to use a third party implementation, they should choose products that meet WCAG requirements.
However, WCAG defines a statement of partial conformance when the page does not conform to WCAG only for reasons that are legitimately outside the author's control. It is important to recognize that this is a statement of non-conformance and there are users who will not be able to access some of the content this page.
One reason that content may be outside the author's control is because it is being provided by a third party (blogs, portals, news sites). Web pages may also include content via third party libraries, plugins, or widgets.
In practice, it may be possible to claim conformance for web pages that contain third party content. A platform or tool may provide guidance for how to address conformance problems when including it in another web page. Filtering third third party content so that only conforming content is allowed could help raise the bar.
Be sure to monitor any content that can change without approval from the web page author, as a page which once conformed may suddenly fail to conform. If it is not possible to monitor and repair the third party content, it may be possible to identify the non-conforming parts of the page to users. If the rest of the web page conforms to WCAG, such a page qualifies for a statement of partial conformance, third party content. 

https://www.w3.org/WAI/GL/wiki/Understanding_Partial_Conformance_-_Third_Party_Content#Understanding_Partial_Conformance_-_Third_Party_Content

**Comment by awkawk** [comment]
Add section to: http://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html 

Section to be in "Understanding conformance claims section and immediately precede "Information about any additional steps taken that go beyond the Success Criteria" heading.

https://github.com/w3c/wcag/commit/aa797025a8ba72a6ab92dd553a8086f8b0dd11de?diff=split
