### ISSUE TITLE
Scoping issue: Treatment of sub-domain content

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#982]
We are struggling with scoping in evaluations of public sector websites that have subdomains with stuff that the customer may want to exclude from scope because it is inaccessible / cannot easily be made accessible. I believe [Conformance requirement 5.2.3 Complete processes](https://www.w3.org/TR/WCAG21/#x5-2-3-complete-processes) gives us a good rationale not to accept exclusions when content in the site leads on to processes (like a merchandise shop) in such a subdomain (or even an in an entirely different domain). 

It is not clear if a subdomain  (with stuff preventing conformance) can be excluded if it basically looks & behaves like the parent domain simply for the fact that it **is** a subdomain.

It is also not clear whether a subdomian can be excluded if it is quite distinct in terms of function, structure, content, style, and no processes happen across main domain and subdomain.

[WCAG EM's definition of enclosure](https://www.w3.org/TR/WCAG-EM/#enclosure) and its somewhat vague talk of "distinct areas" leaves it open how these relate to subdomains. My hunch is that distinctness here hinges more on separation of content than the domain structure. Thoughts?

**Comment by jake-abma** [comment]
@detlevhfischer I think it's not "sub domain" related at all, it just depends on if it's included in the process, also the Understanding hint clearly at this:

> Understanding Conformance Requirements
> There are five requirements that must be met in order for content to be classified as 'conforming' to WCAG 2.0.
> 
> 1. Conformance Level: All information on a page conforms or has a conforming alternate version that is available from the page. For Level AA conformance, the Web page satisfies all the Level A and Level AA Success Criteria.
> 
> 2. Full pages: This provision simply requires that the whole page conform. Statements about "part of a page conforming" cannot be made. A full page includes each variation of the page, e.g. variations in a responsive Web page.
> 
> 3. Complete processes: When a Web page is one of a series of Web pages presenting a process, all Web pages in the process conform at the specified level or better. 
> 
> 4. Only Accessibility-Supported Ways of Using Technologies: Something can be done in the Web content that would make it possible for assistive technologies to successfully present the content's information to the user.
> 
> Accessibility supported: supported by users' assistive technologies as well as the accessibility features in browsers and other user agents.
> 
> 5. Non-Interference: technologies that are not accessibility supported can be used, as long as all the information is also available using technologies that are accessibility supported and as long as the non-accessibility-supported material does not interfere. The following are mandatory because failure to meet them could interfere with any use of the page:
> 
> 1.4.2 - Audio Control,
> 2.1.2 - No Keyboard Trap,
> 2.3.1 - Three Flashes or Below Threshold, and
> 2.2.2 - Pause, Stop, Hide.

So " Full Pages" and "Complete processes" MUST be conforming otherwise there's only the "Partial conformance claim" option.

**Comment by detlevhfischer** [comment]
Thanks @jake-abma - in my view, the full pages requirement has no relevance for the question of scoping in / scoping out of subdomains?

**Comment by mraccess77** [comment]
From a strict WCAG conformance statement -- if you exclude ads you can only claim partial conformance unless there is an alternative that can be reached from that page.

From the standpoint of creating conformance statements that are not "formal statements of conformance" we often do have to separate out things -- but generally even then we do it on a page basis.  We wouldn't exclude a feature on it's own page just because it's not accessible -- but we might not include a page in a sample of pages if the functionality in the page was a total separate thing like - an admin interface when we are only testing a standard user interface or an app embedded into another app for ease of use when the other app can be accessed outside of the embedded situation.    

I'd also point out that ads on a site might be your own ads -- and those ads not being accessible may discriminate -- regardless of where the ads are hosted.

For third party ads I can see scoping them out of a non-formal claim or taking a partial conformance claim as long as the non-interference item's are met and users can move past them.

**Comment by detlevhfischer** [comment]
@mraccess77 - could it be that you wantend to comment on https://github.com/w3c/wcag/issues/983 (Treatment of ad content)? This issue is focused on the scoping in or out of subdomains...

**Comment by alastc** [comment]
I'm not sure that looking at WCAG conformance is going to help, it is up to the 'owner' what they are making a conformance claim for.

However, with public sector bodies I've been including everything they own/control unless it meets one of the exceptions in the legislation. That's how our PSB clients have been interpreting it. How they divide up the conformance cliams is up to them, but they should cover everything that isn't excluded.

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
