### ISSUE TITLE
Treatment of ad content

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wcag#983]
I wonder whether there is a clear working group position regarding ad content on web pages. I have some assumptions and would like to get feedback as to whether you agree or disagree:

1. [the four SCs under 5.2.5 Non-Interference](https://www.w3.org/TR/WCAG21/#x5-2-5-non-interference) mean that any page which has animated ads that cannot be stopped will fail (same for auto-playing sound, larger flickering areas etc.)
2. there is a requirement that ad content is semantically distinct (e.g. in a section or iframe labelled "advertisement") or at the very least marked by a preceding text labelling ad content as advertisement
3. ad content that is **not** hidden from non-visual users will need alternative texts
4. it is OK to hide ad content from non-visual users (e.g. via `aria-hidden`) because it is not an integral part of the content

Agree?

**Comment by jake-abma** [comment]
1. agree, see also Understanding => A Web advertisement: An advertisement blinks to get viewers attention but stops after 5 seconds => https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html#examples

2. not agree => where can I find this requirement?

3. agree => IF image then => 1.1.1. https://www.w3.org/WAI/WCAG21/Understanding/non-text-content IF text, no need for also alternative text :-)

4. not agree => it's NOT "decorative"

**Comment by detlevhfischer** [comment]
>     2\. not agree => where can I find this requirement?

1.3.1?

**Comment by jake-abma** [comment]
I've always seen 1.3.1. as the semantic need for code structure, not explaining what the content "is".

Recently we've had the same suggestion in the WG call for important controls and still think we should not start "judging" the content on "what it is" / purpose and place it under 1.3.1.

We'll end up with "the semantic code is OK, headings = headings / links = links BUT you forgot to add an attribute OR extra label / name SO a fail under 1.3.1. 'info and relationship"

My opinion would be that we need 2 different SC for that IF we want to judge that way.

- One for semantic / programmatic determinable
- One for (subjective) meaning or purpose (if at all this one)

Cheers!

**Comment by jake-abma** [comment]
see also:

> programmatically determined (programmatically determinable)
> determined by software from author-supplied data provided in a way that different user agents, including assistive technologies, can extract and present this information to users in different modalities
> 
> Example 1: Determined in a markup language from elements and attributes that are accessed directly by commonly available assistive technology.
> 
> Example 2: Determined from technology-specific data structures in a non-markup language and exposed to assistive technology via an accessibility API that is supported by commonly available assistive technology.

**Comment by jake-abma** [comment]
ow, of course UNLESS there will be an <advertisement> element :-)

**Comment by alastc** [comment]
I'd hope the working group can have a clear position on the conformance aspects, but there are legal/moral issues here as well which aren't really in our scope.

FWIW:
* Agree.
* Arguable, although if it is a 'section' then I agree it should have some sort of title / heading.
* Agree.
* Disagree, although many people wouldn't want the ads (whether they have a disability or not) it could be seen as discriminatory to remove them for users with disabilities. E.g. A UK supermarket got sued because their 'accessible' version didn't contain the same offers as the default version. (This was a while ago.)

The Public sector bodies legislation does give sites an 'out' if the ads are 3rd party provided, but otherwise I'd consider them part of the content.

>  UNLESS there will be an <advertisement> element :-)

Ha! Never going to happen, it would be making the ad-blockers task too easy! (See also '[don't use sponsors](https://alastairc.uk/2006/03/dont-use-spnsors/)'

**Comment by detlevhfischer** [comment]
On second thoughts regarding my point 4, I agree that it is **not** OK to hide ad content from non-visual users (e.g. via `aria-hidden`) - we want equal access even to undesirable stuff.

**Comment by fstrr** [comment]
This issue looks like it can be closed. If it needs to be re-opened, please do that and convert it to a Discussion.
